import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import test from 'node:test'

const root = path.resolve(new URL('../..', import.meta.url).pathname)
const source = fs.readFileSync(path.join(root, 'pages/resource/detail.vue'), 'utf8')
const pagesConfig = JSON.parse(fs.readFileSync(path.join(root, 'pages.json'), 'utf8'))

test('resource detail gallery uses banner swiper and full screen preview', () => {
  assert.match(source, /const selectedGalleryIndex = ref\(0\)/)
  assert.match(source, /<swiper[\s\S]*v-if="galleryImages\.length > 1"[\s\S]*duration="450"[\s\S]*easing-function="easeInOutCubic"[\s\S]*@change="handleGalleryChange"/)
  assert.doesNotMatch(source, /:current="selectedGalleryIndex"/)
  assert.match(source, /<swiper-item[\s\S]*v-for="\(\s*url,\s*index\s*\) in galleryImages"/)
  assert.match(source, /@click="previewGalleryImage\(index\)"/)
  assert.match(source, /v-else-if="mainImage"[\s\S]*@click="previewGalleryImage\(0\)"/)
  assert.match(source, /function handleGalleryChange\(event\) \{[\s\S]*selectedGalleryIndex\.value = current[\s\S]*\}/)
  assert.match(source, /function previewGalleryImage\(index = selectedGalleryIndex\.value\) \{[\s\S]*uni\.previewImage\(\{[\s\S]*current,[\s\S]*urls: galleryImages\.value[\s\S]*\}\)/)
  assert.equal(source.includes('gallery-strip'), false)
  assert.equal(source.includes('gallery-thumb'), false)
  assert.equal(source.includes('selectGalleryImage'), false)
})

test('resource detail replaces empty image area with an informative no-image cover', () => {
  assert.match(source, /import \{[\s\S]*buildResourceDetailPresentation[\s\S]*\} from '\.\.\/\.\.\/common\/resourceDetailState'/)
  assert.match(source, /<view v-else :class="\['gallery-main', 'gallery-placeholder', isDemandResource \? 'demand' : ''\]">/)
  assert.match(source, /<text class="placeholder-badge">\{\{ noImageBadgeText \}\}<\/text>/)
  assert.match(source, /<text class="placeholder-type">\{\{ detailPresentation\.typeName \}\}<\/text>/)
  assert.match(source, /<text class="placeholder-title">\{\{ noImageStateTitle \}\}<\/text>/)
  assert.match(source, /<button v-if="canEditOwnResourceWithoutImage" class="placeholder-edit-button" @click\.stop="openPublishEditor">补充图片<\/button>/)
  assert.match(source, /const detailPresentation = computed\(\(\) => buildResourceDetailPresentation\(resource\.value\)\)/)
  assert.match(source, /const isDemandResource = computed\(\(\) => detailPresentation\.value\.isDemand\)/)
  assert.match(source, /const noImageStateTitle = computed\(\(\) => `\$\{resourceNoun\.value\}暂无图片`\)/)
  assert.match(source, /重点\$\{resourceNoun\.value\}信息已整理在下方详情中/)
  assert.match(source, /\.gallery-placeholder \{[\s\S]*height: auto;[\s\S]*min-height: 240rpx;[\s\S]*\}/)
  assert.equal(source.includes('noImageSummaryItems'), false)
  assert.equal(source.includes('placeholder-summary'), false)
  assert.equal(source.includes('可先联系发布方确认品类、数量、预算和交付时间'), false)
  assert.equal(source.includes('联系商家前，建议确认实物、数量、价格和交付方式'), false)
  assert.equal(source.includes("{{ resource.category || '供应实拍' }}"), false)
})

test('resource detail updates navigation title by supply or demand direction', () => {
  const detailPage = pagesConfig.pages.find((item) => item.path === 'pages/resource/detail')

  assert.equal(detailPage?.style?.navigationBarTitleText, '供应详情')
  assert.equal(source.includes('供需详情'), false)
  assert.equal(JSON.stringify(detailPage).includes('供需详情'), false)
  assert.match(source, /function updateNavigationTitle\(\) \{[\s\S]*uni\.setNavigationBarTitle\(\{[\s\S]*title: isDemandResource\.value \? '需求详情' : '供应详情'[\s\S]*\}\)[\s\S]*\}/)
  assert.match(source, /resource\.value = isOwnResource\.value \? await getOwnResource[\s\S]*updateNavigationTitle\(\)/)
  assert.match(source, /async function loadOwnResourceIfCurrentMerchant\(resourceId\) \{[\s\S]*resource\.value = await getOwnResource[\s\S]*updateNavigationTitle\(\)/)
  assert.match(source, /async function reloadOwnResource\(\) \{[\s\S]*resource\.value = await getOwnResource[\s\S]*updateNavigationTitle\(\)/)
  assert.match(source, /onReady\(\(\) => \{[\s\S]*if \(resource\.value\.id\) updateNavigationTitle\(\)[\s\S]*\}\)/)
})

test('resource detail keeps contact reminder friendly and visually quiet', () => {
  assert.match(source, /<text class="section-title">友情提示<\/text>/)
  assert.match(source, /<text class="section-content contact-tip-content">联系\{\{ resourceNoun \}\}方前，建议先确认实物、价格、数量和交付方式。<\/text>/)
  assert.match(source, /\.contact-tip-content \{[\s\S]*font-size: 26rpx;[\s\S]*line-height: 1\.5;[\s\S]*\}/)
  assert.equal(source.includes('平台已记录联系行为'), false)
  assert.equal(source.includes('<text class="section-title">联系提示</text>'), false)
})

test('resource detail only shows merchant home entry after merchant profile is completed', () => {
  assert.match(source, /const showMerchantHomeEntry = computed\(\(\) => \{[\s\S]*merchantInfo\.value\.profileStatus === 'completed'[\s\S]*\}\)/)
  assert.match(source, /<view v-if="showMerchantHomeEntry" class="merchant-card" @click="openMerchant">/)
  assert.match(source, /function openMerchant\(\) \{[\s\S]*if \(!showMerchantHomeEntry\.value\) return[\s\S]*uni\.navigateTo\(\{ url: `\/pages\/merchant\/detail\?id=\$\{merchantId\}` \}\)/)
})

test('resource detail does not show merchant endorsement copy in the description card', () => {
  assert.doesNotMatch(source, /const isVIPMerchant = computed/)
  assert.doesNotMatch(source, /<text v-if="isVIPMerchant" class="tag vip">VIP<\/text>/)
  assert.doesNotMatch(source, /平台核实/)
  assert.doesNotMatch(source, /认证商家/)
})

test('resource detail keeps publish status out of the description card', () => {
  assert.doesNotMatch(source, /<text v-if="isOwnResource && resource\.status" class="tag">/)
  assert.doesNotMatch(source, /<text v-if="resource\.status" class="tag">/)
  assert.match(source, /const managementTitle = computed\(\(\) => statusText\[resource\.value\.status\] \|\| `\$\{resourceNoun\.value\}管理`\)/)
})

test('resource detail places automatic summary before description, specs, and merchant', () => {
  const summaryIndex = source.indexOf('class="detail-summary-card"')
  const descriptionIndex = source.indexOf('class="description-card"')
  const merchantIndex = source.indexOf('class="merchant-card"')
  const specIndex = source.indexOf('详细参数')

  assert.ok(summaryIndex >= 0)
  assert.ok(descriptionIndex > summaryIndex)
  assert.ok(specIndex > descriptionIndex)
  assert.ok(merchantIndex > specIndex)
  assert.match(source, /<text class="summary-title">\{\{ detailPresentation\.headline \}\}<\/text>/)
  assert.match(source, /v-for="item in detailPresentation\.facts"/)
})

test('resource detail displays only publish feature tags in the automatic summary card', () => {
  assert.match(source, /const resourceFeatureTags = computed\(\(\) => normalizeResourceFeatureTags\(resource\.value\.tags\)\)/)
  assert.doesNotMatch(source, /const hasDetailTags = computed/)
  assert.match(source, /<view class="detail-summary-card">[\s\S]*<view v-if="resourceFeatureTags\.length" class="tag-row">/)
  assert.match(source, /<text v-for="tag in resourceFeatureTags" :key="tag" class="tag feature">\{\{ tag \}\}<\/text>/)
  assert.doesNotMatch(source, /<text v-if="resource\.refreshedAt" class="tag">/)
  assert.doesNotMatch(source, /<text v-if="isOwnResource && resource\.status" class="tag">/)
  assert.match(source, /function normalizeResourceFeatureTags\(tags = \[\]\)/)
  assert.match(source, /\.tag \{[\s\S]*border: 1rpx solid rgba\(100, 116, 139, 0\.22\);[\s\S]*font-weight: 700;/)
  assert.match(source, /\.tag\.feature \{[\s\S]*background: #fff7ed;[\s\S]*color: \$wplink-warning;/)
})

test('resource detail displays user description as a supplemental section below automatic summary', () => {
  const galleryIndex = source.indexOf('class="detail-gallery"')
  const summaryIndex = source.indexOf('class="detail-summary-card"')
  const descriptionIndex = source.indexOf('class="description-card"')

  assert.ok(summaryIndex > galleryIndex)
  assert.ok(descriptionIndex > summaryIndex)
  assert.match(source, /<view v-if="resource\.description" class="description-card">[\s\S]*<text class="section-title">补充说明<\/text>[\s\S]*<text class="desc">\{\{ resource\.description \}\}<\/text>/)
  assert.match(source, /\.desc \{[\s\S]*background: #f8fafc;[\s\S]*font-size: 28rpx;[\s\S]*line-height: 1\.6;/)
  assert.equal(source.includes('class="favorite-button"'), false)
  assert.equal(source.includes('.favorite-button'), false)
  assert.equal(source.includes('.detail-head-row'), false)
  assert.equal(source.includes('.title-row'), false)
  assert.equal(source.includes('.price {'), false)
})

test('own resource detail keeps share and management actions in the bottom bar', () => {
  assert.match(source, /<view v-if="isOwnResource" class="owner-action-bar">/)
  assert.match(source, /<button class="share-button" @click="shareOwnResource" :open-type="canShareOwnResource \? 'share' : ''">分享<\/button>/)
  assert.match(source, /const canShareOwnResource = computed\(\(\) => resource\.value\.status === 'published' && !isExpiredResource\.value && !resource\.value\.dealtAt\)/)
  assert.match(source, /<button class="primary-button" @click="openManagementSheet">管理<\/button>/)
  assert.match(source, /<view v-else-if="!isDealtResource" class="contact-bar">/)
  assert.match(source, /<view v-else class="completed-action-bar">/)
  assert.doesNotMatch(source, /这是你发布的供需信息，可在我的发布中管理/)
})

test('pending own resource management sheet explains automatic safety state', () => {
  assert.match(source, /const contentAuditStatuses = new Set\(\['pending', 'manual_review', 'audit_retry'\]\)/)
  assert.match(source, /const managementNotice = computed\(\(\) => \{[\s\S]*resource\.value\.status === 'pending'[\s\S]*\$\{resourceNoun\.value\}正在自动安全检测[\s\S]*\}\)/)
  assert.match(source, /resource\.value\.status === 'audit_retry'[\s\S]*系统正在自动重试安全检测/)
  assert.match(source, /resource\.value\.status === 'manual_review'[\s\S]*\$\{resourceNoun\.value\}处于异常处理中/)
  assert.match(source, /const managementActions = computed\(\(\) => \{[\s\S]*if \(isContentAuditStatus\(resource\.value\.status\)\) return \[\][\s\S]*\}\)/)
  assert.match(source, /<view v-if="showManagementSheet" class="sheet-mask" @click="closeManagementSheet">/)
  assert.match(source, /<text class="sheet-title">\{\{ managementTitle \}\}<\/text>/)
  assert.match(source, /<text v-if="!managementActions\.length" class="sheet-desc">\{\{ managementNotice \}\}<\/text>/)
  assert.match(source, /<view v-if="managementActions\.length" class="management-actions">/)
  assert.match(source, /<text v-else class="empty-management">暂无可操作功能<\/text>/)
  assert.doesNotMatch(source, /<text class="sheet-desc">\{\{ managementNotice \}\}<\/text>/)
  assert.doesNotMatch(source, /查看我的发布/)
  assert.doesNotMatch(source, /返回列表/)
})

test('own resource management sheet does not expose deal action', () => {
  assert.doesNotMatch(source, /标记成交/)
  assert.doesNotMatch(source, /key: 'deal'/)
  assert.doesNotMatch(source, /markOwnResourceDealt/)
  assert.doesNotMatch(source, /markResourceDeal/)
})

test('resource detail unlocks contact through backend before copy or call', () => {
  assert.match(source, /import \{ requireLogin \} from '\.\.\/\.\.\/common\/auth'/)
  assert.match(source, /if \(isContactUnlockAction\(action\) && !requireLogin\(\)\) return false/)
  assert.match(source, /function isContactUnlockAction\(action\) \{[\s\S]*return action === 'phone' \|\| action === 'wechat'[\s\S]*\}/)
  assert.match(source, /const resp = await recordResourceContact\(resource\.value\.id, action\)/)
  assert.match(source, /return resp \|\| \{\}/)
  assert.match(source, /uni\.setClipboardData\(\{ data: resp\.wechat \}\)/)
  assert.match(source, /uni\.makePhoneCall\(\{ phoneNumber: resp\.phone \}\)/)
  assert.match(source, /微信号已复制/)
  assert.equal(source.includes('已记录联系，完整微信由平台保护'), false)
  assert.equal(source.includes('已记录联系，完整电话由平台保护'), false)
})

test('resource detail uses short phone action text in bottom bar', () => {
  assert.match(source, /const contactButtonText = computed\(\(\) => '拨打电话'\)/)
  assert.doesNotMatch(source, /contactAccess\.value\.actionText \|\| '联系商家'/)
  assert.doesNotMatch(source, />登录后免费查看</)
  assert.doesNotMatch(source, />查看联系方式</)
})

test('resource detail groups low-frequency contact actions behind more sheet', () => {
  const contactBar = source.match(/<view v-else-if="!isDealtResource" class="contact-bar">[\s\S]*?<\/view>/)?.[0] || ''

  assert.match(source, /const showContactMoreSheet = ref\(false\)/)
  assert.match(source, /<view v-if="showContactMoreSheet" class="sheet-mask" @click="closeContactMoreSheet">/)
  assert.match(source, /<text class="sheet-desc">收藏、分享给同行或反馈问题资源。<\/text>/)
  assert.match(source, /<button class="management-action" @click="favoriteResourceFromMore">\{\{ favorited \? '取消收藏' : '收藏' \}\}<\/button>/)
  assert.match(source, /<button class="management-action primary" open-type="share" @click="shareResourceFromMore">分享给朋友<\/button>/)
  assert.match(source, /<button class="management-action danger" @click="reportResourceFromMore">举报<\/button>/)
  assert.match(source, /async function favoriteResourceFromMore\(\) \{[\s\S]*const success = await toggleFavorite\(\)[\s\S]*if \(success\) closeContactMoreSheet\(\)[\s\S]*\}/)
  assert.match(source, /async function shareResourceFromMore\(\) \{[\s\S]*await shareResource\(\)[\s\S]*closeContactMoreSheet\(\)[\s\S]*\}/)
  assert.match(source, /async function reportResourceFromMore\(\) \{[\s\S]*closeContactMoreSheet\(\)[\s\S]*openResourceReportPage\(\)[\s\S]*\}/)
  assert.match(contactBar, /@click="copyWechat"/)
  assert.match(contactBar, /@click="callPhone"/)
  assert.match(contactBar, /@click="openContactMoreSheet"/)
  assert.ok(contactBar.indexOf('openContactMoreSheet') < contactBar.indexOf('copyWechat'))
  assert.ok(contactBar.indexOf('copyWechat') < contactBar.indexOf('callPhone'))
  assert.equal(contactBar.includes('open-type="share"'), false)
  assert.equal(contactBar.includes('reportCurrentResource'), false)
  assert.match(source, /grid-template-columns: 104rpx minmax\(0, 1fr\) minmax\(0, 1\.35fr\);/)
  assert.equal(source.includes('grid-template-columns: repeat(4, 1fr);'), false)
})

test('resource detail renders related resources with the market feed card variant', () => {
  assert.match(source, /<view v-if="relatedResources\.length" class="related-section">[\s\S]*<ResourceList[\s\S]*:resources="relatedResources"[\s\S]*variant="feed"[\s\S]*@open="openRelatedResource"/)
})

test('resource detail opens dedicated report page from more sheet', () => {
  assert.match(source, /function openResourceReportPage\(\) \{[\s\S]*if \(!resource\.value\.id \|\| isOwnResource\.value\) return[\s\S]*if \(!requireLogin\(\)\) return[\s\S]*resourceId=\$\{encodeURIComponent\(resource\.value\.id\)\}[\s\S]*\/pages\/resource\/report\?\$\{params\.join\('&'\)\}[\s\S]*\}/)
  assert.doesNotMatch(source, /reportResource\(resource\.value\.id/)
  assert.doesNotMatch(source, /chooseResourceReportReason/)
  assert.doesNotMatch(source, /collectResourceReportContact/)
})

test('resource detail handles paid contact unlock flow', () => {
  const apiSource = fs.readFileSync(path.join(root, 'api/resource.js'), 'utf8')

  assert.match(source, /contactAccess/)
  assert.match(source, /createContactUnlockOrder/)
  assert.match(source, /createContactUnlockPayment/)
  assert.match(source, /PAYMENT_REQUIRED/)
  assert.match(source, /requestPayment/)
  assert.match(apiSource, /createContactUnlockOrder/)
  assert.match(apiSource, /createContactUnlockPayment/)
})

test('resource detail supports WeChat group and timeline sharing with generated cover image', () => {
  assert.match(source, /import \{ onLoad, onReady, onShareAppMessage, onShareTimeline \} from '@dcloudio\/uni-app'/)
  assert.match(source, /buildResourceSharePayload/)
  assert.match(source, /buildResourceTimelinePayload/)
  assert.match(source, /buildResourceSharePosterModel/)
  assert.match(source, /RESOURCE_SHARE_COVER_CANVAS_ID/)
  assert.match(source, /RESOURCE_SHARE_COVER_SIZE/)
  assert.match(source, /const shareImageUrl = ref\(''\)/)
  assert.match(source, /<canvas[\s\S]*canvas-id="resourceShareCoverCanvas"[\s\S]*class="share-cover-canvas"[\s\S]*:width="shareCoverCanvasSize\.width"[\s\S]*:height="shareCoverCanvasSize\.height"/)
  assert.match(source, /uni\.showShareMenu\(\{[\s\S]*menus: \['shareAppMessage', 'shareTimeline'\][\s\S]*\}\)/)
  assert.match(source, /uni\.canvasToTempFilePath\(\{[\s\S]*canvasId: RESOURCE_SHARE_COVER_CANVAS_ID[\s\S]*success: \(res\) => resolve\(res\.tempFilePath \|\| ''\)/)
  assert.match(source, /onShareAppMessage\(\(shareEvent\) => \{[\s\S]*buildResourceSharePayload\(resource\.value, shareImageUrl\.value\)[\s\S]*\}\)/)
  assert.match(source, /onShareTimeline\(\(\) => \{[\s\S]*buildResourceTimelinePayload\(resource\.value, shareImageUrl\.value\)[\s\S]*\}\)/)
  assert.match(source, /\.share-cover-canvas \{[\s\S]*position: fixed;[\s\S]*left: -9999px;[\s\S]*width: 600px;[\s\S]*height: 480px;/)
})

test('resource detail renders configured attribute items as specs', () => {
  assert.match(source, /const attributeSpecItems = computed\(\(\) =>/)
  assert.match(source, /resource\.value\.attributeItems \|\| \[\]/)
  assert.match(source, /!addressAttributeKeys\.value\.has\(item\.key\)/)
  assert.match(source, /label: item\.label/)
  assert.match(source, /value: item\.value/)
  assert.doesNotMatch(source, /summaryFactItems/)
  assert.doesNotMatch(source, /summarySpecCompareValues/)
  assert.doesNotMatch(source, /isDuplicateSummarySpecItem/)
  assert.doesNotMatch(source, /const summarySpecItems = computed\(\(\) =>/)
  assert.doesNotMatch(source, /const attributeSpecValues = computed\(\(\) =>/)
  assert.match(source, /const specItems = computed\(\(\) => buildDetailSpecItems\(attributeSpecItems\.value\)\)/)
  assert.doesNotMatch(source, /\.\.\.summarySpecItems\.value/)
  assert.doesNotMatch(source, /\{ label: '更新时间', value: resource\.value\.refreshedAt \|\| '近期更新' \}/)
  assert.doesNotMatch(source, /\{ label: '刷新', value: resource\.value\.refreshedAt/)
  assert.match(source, /:class="\['spec-item', item\.fullWidth \? 'full-width' : ''\]"/)
  assert.match(source, /\.spec-item\.full-width \{[\s\S]*grid-column: 1 \/ -1;/)
})

test('resource detail renders address attributes as a dedicated navigation section', () => {
  assert.match(source, /<view v-if="resourceAddressLocations\.length" class="address-section">/)
  assert.match(source, /<text class="section-title">地址<\/text>/)
  assert.equal(source.includes('位置与导航'), false)
  assert.match(source, /<view class="resource-address-main">[\s\S]*<view class="resource-address-copy">[\s\S]*<text class="resource-address-text">\{\{ item\.address \}\}<\/text>[\s\S]*<button v-if="item\.hasGps" class="address-action" @click="openResourceAddressLocation\(item\)">导航<\/button>/)
  assert.match(source, /<button v-if="item\.hasGps" class="address-action" @click="openResourceAddressLocation\(item\)">导航<\/button>/)
  assert.match(source, /<button v-else class="address-action secondary" @click="copyResourceAddress\(item\)">复制<\/button>/)
  assert.match(source, /<text class="resource-address-text">\{\{ item\.address \}\}<\/text>[\s\S]*<map[\s\S]*v-if="item\.hasGps"[\s\S]*class="resource-address-map"[\s\S]*:latitude="item\.latitude"[\s\S]*:longitude="item\.longitude"[\s\S]*@tap="openResourceAddressLocation\(item\)"/)
  assert.match(source, /const resourceAddressLocations = computed\(\(\) => \{[\s\S]*Object\.entries\(attributes\)[\s\S]*buildResourceAddressLocation/)
  assert.match(source, /const addressAttributeKeys = computed\(\(\) => new Set\(resourceAddressLocations\.value\.map\(\(item\) => item\.key\)\)\)/)
  assert.match(source, /function buildResourceAddressLocation\(key, value, index\) \{[\s\S]*isResourceAddressAttributeValue\(value\)[\s\S]*const hasGps = Number\.isFinite\(latitude\) && Number\.isFinite\(longitude\)[\s\S]*if \(!hasGps\) return item[\s\S]*markers/)
  assert.match(source, /function isResourceAddressAttributeValue\(value\) \{[\s\S]*\['address', 'name', 'latitude', 'longitude', 'lat', 'lng'\]/)
  assert.match(source, /function openResourceAddressLocation\(item\) \{[\s\S]*uni\.openLocation\(\{[\s\S]*latitude: item\.latitude[\s\S]*longitude: item\.longitude[\s\S]*scale: 18/)
  assert.match(source, /function copyResourceAddress\(item, title = '地址已复制'\)/)
  assert.match(source, /导航打开失败，已复制地址/)
  assert.match(source, /\.resource-address-main \{[\s\S]*grid-template-columns: minmax\(0, 1fr\) 96rpx;/)
  assert.match(source, /\.resource-address-map \{[\s\S]*height: 220rpx;/)
  assert.match(source, /\.resource-address-text \{[\s\S]*display: block;[\s\S]*font-size: 27rpx;[\s\S]*word-break: break-word;/)
})

test('resource detail restores top voucher management action', () => {
  assert.match(source, /import \{ listTopVouchers, redeemTopVoucher \} from '\.\.\/\.\.\/api\/entitlement'/)
  assert.match(source, /import \{ createQuotaPackOrder, createVIPPayment, listQuotaPacks \} from '\.\.\/\.\.\/api\/vip'/)
  assert.match(source, /\$\{resourceNoun\.value\}展示中，可按需刷新、置顶或下架。/)
  assert.match(source, /key: 'top'/)
  assert.match(source, /label: '置顶'/)
  assert.match(source, /async function topOwnResource\(\)/)
  assert.match(source, /listTopVouchers\(ownerMerchantId\.value\)/)
  assert.match(source, /redeemTopVoucher\(voucher\.id, resource\.value\.id, ownerMerchantId\.value\)/)
  assert.match(source, /async function purchaseTopService\(\)/)
  assert.match(source, /createQuotaPackOrder\(ownerMerchantId\.value, pack\.code, \{ resourceId: resource\.value\.id \}\)/)
  assert.match(source, /createVIPPayment\(ownerMerchantId\.value, order\.orderId\)/)
  assert.match(source, /购买置顶服务/)
  assert.match(source, /saleLabel: '置顶 1 天'/)
  assert.match(source, /function topServiceSaleLabel\(item\)/)
  assert.match(source, /function topServicePurchaseText\(item\)/)
  assert.match(source, /function isTopServiceDiscounted\(item\)/)
  assert.match(source, /topServicePurchaseText\(item\)\.join\(' · '\)/)
  assert.match(source, /topServicePurchaseText\(pack\)\.join\('，'\)/)
  assert.doesNotMatch(source, /暂无可用置顶券，请先购买/)
  assert.doesNotMatch(source, /tab=top/)
})
