import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { spawnSync } from 'node:child_process'
import { fileURLToPath } from 'node:url'

import { parseAPIContracts, routeFingerprint } from './api_route_inventory.mjs'

const requiredGoctlVersion = '1.7.5'
const scriptDir = path.dirname(fileURLToPath(import.meta.url))
const backendDir = path.resolve(scriptDir, '..')
const apiDir = path.join(backendDir, 'app/api')
const templateHome = path.join(backendDir, 'app/goctl')
const handlerDir = path.join(backendDir, 'app/internal/handler')
const goKeywords = new Set([
  'break', 'default', 'func', 'interface', 'select',
  'case', 'defer', 'go', 'map', 'struct',
  'chan', 'else', 'goto', 'package', 'switch',
  'const', 'fallthrough', 'if', 'range', 'type',
  'continue', 'for', 'import', 'return', 'var',
])

function runCommand(command, args, options = {}) {
  const result = spawnSync(command, args, {
    cwd: options.cwd || backendDir,
    env: options.env || process.env,
    encoding: 'utf8',
  })
  if (result.error) {
    throw new Error(`无法执行 ${command}: ${result.error.message}`)
  }
  if (result.status !== 0) {
    const detail = [result.stdout, result.stderr].filter(Boolean).join('\n').trim()
    throw new Error(`${command} 执行失败${detail ? `:\n${detail}` : ''}`)
  }
  return `${result.stdout || ''}${result.stderr || ''}`.trim()
}

function verifyGoctlVersion() {
  const output = runCommand('goctl', ['--version'])
  const actualVersion = output.match(/\bgoctl version ([^\s]+)/)?.[1]
  if (actualVersion !== requiredGoctlVersion) {
    throw new Error(`goctl 版本不匹配，需要 ${requiredGoctlVersion}，当前为 ${actualVersion || '未知版本'}`)
  }
}

function listGoFiles(directory) {
  if (!fs.existsSync(directory)) {
    return []
  }
  const files = []
  for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
    const entryPath = path.join(directory, entry.name)
    if (entry.isDirectory()) {
      files.push(...listGoFiles(entryPath))
    } else if (entry.name.endsWith('.go')) {
      files.push(entryPath)
    }
  }
  return files.sort()
}

function handlerFunctionName(source) {
  return source.match(/\bfunc\s+([A-Za-z0-9_]+Handler)\s*\(/)?.[1] || ''
}

function existingHandlerFunctions() {
  const functions = new Set()
  for (const filePath of listGoFiles(handlerDir)) {
    const source = fs.readFileSync(filePath, 'utf8')
    for (const match of source.matchAll(/\bfunc\s+([A-Za-z0-9_]+Handler)\s*\(/g)) {
      functions.add(match[1])
    }
  }
  return functions
}

function goString(value) {
  return JSON.stringify(String(value))
}

function buildRoutesManifest() {
  const routes = parseAPIContracts(apiDir).sort((left, right) => {
    const leftKey = `${routeFingerprint(left)}\u0000${left.handler}\u0000${left.group}`
    const rightKey = `${routeFingerprint(right)}\u0000${right.handler}\u0000${right.group}`
    return leftKey < rightKey ? -1 : leftKey > rightKey ? 1 : 0
  })
  const entries = routes.map((route) => `\t\t{Method: ${goString(route.method)}, Path: ${goString(route.path)}, Handler: ${goString(route.handler)}, Group: ${goString(route.group)}},`).join('\n')

  return `// Code generated by scripts/api_codegen.mjs. DO NOT EDIT.

package handler

// ContractRoute 描述 app/api 中声明的单条 HTTP 路由，供运行时门禁核对注册结果。
type ContractRoute struct {
\tMethod  string
\tPath    string
\tHandler string
\tGroup   string
}

// ContractRoutes 返回按 method、path、handler、group 稳定排序的契约路由副本。
func ContractRoutes() []ContractRoute {
\treturn []ContractRoute{
${entries}
\t}
}
`
}

function formatGoFiles(files, cwd) {
  if (files.length === 0) {
    return
  }
  runCommand('gofmt', ['-w', ...files], { cwd })
}

function normalizeKeywordHandlerPackages(generatedHandlerDir) {
  const routesPath = path.join(generatedHandlerDir, 'routes.go')
  let routesSource = fs.readFileSync(routesPath, 'utf8')

  for (const entry of fs.readdirSync(generatedHandlerDir, { withFileTypes: true })) {
    if (!entry.isDirectory() || !goKeywords.has(entry.name)) {
      continue
    }
    const safePackageName = `${entry.name}handler`
    for (const filePath of listGoFiles(path.join(generatedHandlerDir, entry.name))) {
      const source = fs.readFileSync(filePath, 'utf8')
      fs.writeFileSync(filePath, source.replace(
        new RegExp(`^package\\s+${entry.name}\\b`, 'm'),
        `package ${safePackageName}`,
      ))
    }
    routesSource = routesSource
      .replace(
        new RegExp(`^\\s*${entry.name}\\s+("[^"]+/handler/${entry.name}")`, 'm'),
        `\t${safePackageName} $1`,
      )
      .replace(new RegExp(`\\b${entry.name}\\.`, 'g'), `${safePackageName}.`)
  }
  fs.writeFileSync(routesPath, routesSource)
}

function generateIntoTemporaryModule() {
  const temporaryDir = fs.mkdtempSync(path.join(os.tmpdir(), 'wplink-api-codegen-'))
  try {
    fs.writeFileSync(path.join(temporaryDir, 'go.mod'), 'module wplink/backend\n\ngo 1.23.0\n')
    fs.mkdirSync(path.join(temporaryDir, 'app'), { recursive: true })
    fs.cpSync(apiDir, path.join(temporaryDir, 'app/api'), { recursive: true })

    // --home 与隔离后的 GOCTL_HOME 双重限定模板来源，避免本机用户模板影响生成结果。
    const isolatedEnv = {
      ...process.env,
      GOCTL_HOME: templateHome,
    }
    runCommand('goctl', ['api', 'validate', '--api', 'app/api/app.api'], {
      cwd: temporaryDir,
      env: isolatedEnv,
    })
    runCommand('goctl', [
      'api', 'go',
      '--api', 'app/api/app.api',
      '--dir', 'app',
      '--home', templateHome,
      '--style', 'go_zero',
    ], {
      cwd: temporaryDir,
      env: isolatedEnv,
    })

    const generatedHandlerDir = path.join(temporaryDir, 'app/internal/handler')
    const manifestPath = path.join(generatedHandlerDir, 'routes_manifest_gen.go')
    fs.writeFileSync(manifestPath, buildRoutesManifest())
    // goctl 1.7.5 会直接把 group 当作包名；map 等关键字需在同步前统一转成合法别名。
    normalizeKeywordHandlerPackages(generatedHandlerDir)
    const generatedGoFiles = [
      path.join(temporaryDir, 'app/internal/types/types.go'),
      ...listGoFiles(generatedHandlerDir),
    ]
    formatGoFiles(generatedGoFiles, temporaryDir)

    for (const filePath of generatedGoFiles) {
      if (fs.readFileSync(filePath, 'utf8').includes('zmall/')) {
        throw new Error(`仓库模板生成了禁止的 zmall import: ${path.relative(temporaryDir, filePath)}`)
      }
    }
    return temporaryDir
  } catch (error) {
    fs.rmSync(temporaryDir, { recursive: true, force: true })
    throw error
  }
}

function synchronizeFile(sourcePath, destinationPath, mode, staleFiles) {
  const expected = fs.readFileSync(sourcePath)
  const current = fs.existsSync(destinationPath) ? fs.readFileSync(destinationPath) : null
  if (current && current.equals(expected)) {
    return
  }
  if (mode === '--check') {
    staleFiles.push(path.relative(backendDir, destinationPath))
    return
  }
  fs.mkdirSync(path.dirname(destinationPath), { recursive: true })
  fs.writeFileSync(destinationPath, expected)
}

function synchronizeMissingHandlers(generatedHandlerDir, mode, staleFiles) {
  const existingFunctions = existingHandlerFunctions()
  for (const generatedPath of listGoFiles(generatedHandlerDir)) {
    if (path.dirname(generatedPath) === generatedHandlerDir) {
      continue
    }
    const source = fs.readFileSync(generatedPath, 'utf8')
    const functionName = handlerFunctionName(source)
    if (!functionName || existingFunctions.has(functionName)) {
      continue
    }

    const relativePath = path.relative(generatedHandlerDir, generatedPath)
    const destinationPath = path.join(handlerDir, relativePath)
    if (mode === '--check') {
      staleFiles.push(`${path.relative(backendDir, destinationPath)}（缺少 ${functionName}）`)
      continue
    }
    if (fs.existsSync(destinationPath)) {
      throw new Error(`无法生成 ${functionName}：目标文件已存在 ${path.relative(backendDir, destinationPath)}`)
    }
    fs.mkdirSync(path.dirname(destinationPath), { recursive: true })
    fs.writeFileSync(destinationPath, source)
    existingFunctions.add(functionName)
  }
}

function run(mode) {
  if (mode !== '--write' && mode !== '--check') {
    throw new Error('用法: node scripts/api_codegen.mjs --write|--check')
  }
  verifyGoctlVersion()
  const temporaryDir = generateIntoTemporaryModule()
  try {
    const generatedAppDir = path.join(temporaryDir, 'app')
    const staleFiles = []
    synchronizeFile(
      path.join(generatedAppDir, 'internal/types/types.go'),
      path.join(backendDir, 'app/internal/types/types.go'),
      mode,
      staleFiles,
    )
    synchronizeFile(
      path.join(generatedAppDir, 'internal/handler/routes.go'),
      path.join(handlerDir, 'routes.go'),
      mode,
      staleFiles,
    )
    synchronizeFile(
      path.join(generatedAppDir, 'internal/handler/routes_manifest_gen.go'),
      path.join(handlerDir, 'routes_manifest_gen.go'),
      mode,
      staleFiles,
    )
    synchronizeMissingHandlers(path.join(generatedAppDir, 'internal/handler'), mode, staleFiles)

    if (staleFiles.length > 0) {
      throw new Error(`API 生成文件已过期，请运行 node scripts/api_codegen.mjs --write:\n- ${staleFiles.join('\n- ')}`)
    }
    console.log(mode === '--write' ? 'API 生成文件已更新' : 'API 生成文件为最新')
  } finally {
    fs.rmSync(temporaryDir, { recursive: true, force: true })
  }
}

try {
  run(process.argv[2])
} catch (error) {
  console.error(`API 代码生成失败: ${error.message}`)
  process.exitCode = 1
}
