WITH zhili AS (
  INSERT INTO city_stations (code, name, province, city, primary_category, status, config)
  VALUES (
    'zhili',
    '织里',
    '浙江省',
    '湖州市',
    '童装',
    'active',
    '{
      "enabledTypeCodes": ["factory_direct","spot_wholesale","stock_clearance","buy_kids_goods","fabric_supply","accessory_supply","processing_accept","find_factory","production_support","job_hiring","job_seeking","sample_rental","shop_office_rental","shop_sale","seek_shop_office","apartment_rental","housing_sale","seek_housing","factory_warehouse_rental","workshop_rental","factory_sale","seek_factory_warehouse","secondhand_sale","secondhand_buy","education_training","appliance_repair","moving_cleaning","other_local_service"],
      "primaryCategories": ["童装批发","面料辅料","加工生产","招聘求职","商铺办公","住宅公寓","厂房仓库","本地服务"]
    }'::jsonb
  )
  ON CONFLICT (code) DO UPDATE
  SET
    name = EXCLUDED.name,
    province = EXCLUDED.province,
    city = EXCLUDED.city,
    primary_category = EXCLUDED.primary_category,
    status = EXCLUDED.status,
    config = EXCLUDED.config,
    updated_at = now()
  RETURNING id
)
INSERT INTO resource_type_configs (
  city_station_id,
  type_code,
  type_name,
  direction,
  field_schema,
  required_fields,
  filter_fields,
  display_template,
  review_rules,
  sort_weights,
  message_rules,
  default_valid_days,
  status
)
SELECT
  zhili.id,
  cfg.type_code,
  cfg.type_name,
  cfg.direction,
  cfg.field_schema::jsonb,
  cfg.required_fields::jsonb,
  cfg.filter_fields::jsonb,
  cfg.display_template::jsonb,
  cfg.review_rules::jsonb,
  cfg.sort_weights::jsonb,
  cfg.message_rules::jsonb,
  cfg.default_valid_days,
  'active'
FROM zhili
CROSS JOIN (
  VALUES
    ('factory_direct', '工厂直批', 'supply', '{"fields":[{"key":"productCategory","label":"童装品类","type":"select","required":true,"filterable":true,"displayIn":["detail"],"options":["卫衣","套装","裙装","裤装","婴童","中大童"],"allowCustom":true},{"key":"factoryPriceText","label":"出厂价","type":"text","required":true,"filterable":false,"displayIn":["detail"]},{"key":"minOrderText","label":"起批量","type":"text","required":true,"filterable":false,"displayIn":["detail"]},{"key":"factoryAdvantage","label":"工厂优势","type":"select","required":false,"filterable":true,"displayIn":["detail"],"options":["源头工厂","小单快反","来样定制","长期供货"],"allowCustom":true},{"key":"supportsDropship","label":"支持一件代发","type":"boolean","required":false,"filterable":true,"displayIn":["detail"]},{"key":"deliveryArea","label":"发货区域","type":"text","required":false,"filterable":true,"displayIn":["detail"]}]}', '["title","productCategory","factoryPriceText","minOrderText","contactPhone"]', '["productCategory","factoryAdvantage","supportsDropship","deliveryArea"]', '{"group":{"code":"kids_wholesale","name":"童装批发","sort":10},"summary":{"category":"productCategory","quantityText":"minOrderText","priceText":"factoryPriceText"},"list":["priceText","quantityText","district"],"detail":["productCategory","factoryPriceText","minOrderText","factoryAdvantage","supportsDropship","deliveryArea"],"fields":[{"source":"productCategory","label":"童装品类","role":"core","layout":"half","order":10},{"source":"factoryPriceText","label":"出厂价","role":"core_price","layout":"half","order":20},{"source":"minOrderText","label":"起批量","role":"core","layout":"half","order":30},{"source":"factoryAdvantage","label":"工厂优势","role":"detail","layout":"half","order":40},{"source":"supportsDropship","label":"支持一件代发","role":"detail","layout":"half","order":50},{"source":"deliveryArea","label":"发货区域","role":"detail","layout":"half","order":60}]}', '{"resubmitOnChange":["title","productCategory","factoryPriceText","minOrderText","contactPhone"]}', '{"verified":20,"refreshedAt":10,"contactCount":5}', '{"expiringSoonDays":5}', 15),
    ('spot_wholesale', '尾货批发', 'supply', '{"fields":[{"key":"stockCategory","label":"尾货品类","type":"select","required":true,"filterable":true,"displayIn":["detail"],"options":["卫衣","套装","裙装","裤装","外套","混款"],"allowCustom":true},{"key":"stockQuantityText","label":"尾货数量","type":"text","required":true,"filterable":false,"displayIn":["detail"]},{"key":"wholesalePriceText","label":"批发价","type":"text","required":true,"filterable":false,"displayIn":["detail"]},{"key":"season","label":"季节","type":"select","required":false,"filterable":true,"displayIn":["detail"],"options":["春季","夏季","秋季","冬季"],"allowCustom":false},{"key":"sizeRange","label":"尺码段","type":"text","required":false,"filterable":true,"displayIn":["detail"]},{"key":"allowSample","label":"支持拿样","type":"boolean","required":false,"filterable":true,"displayIn":["detail"]}]}', '["title","stockCategory","stockQuantityText","wholesalePriceText","contactPhone"]', '["stockCategory","season","sizeRange","allowSample"]', '{"group":{"code":"kids_wholesale","name":"童装批发","sort":10},"summary":{"category":"stockCategory","quantityText":"stockQuantityText","priceText":"wholesalePriceText"},"list":["priceText","quantityText","district"],"detail":["stockCategory","stockQuantityText","wholesalePriceText","season","sizeRange","allowSample"],"fields":[{"source":"stockCategory","label":"尾货品类","role":"core","layout":"half","order":10},{"source":"stockQuantityText","label":"尾货数量","role":"core","layout":"half","order":20},{"source":"wholesalePriceText","label":"批发价","role":"core_price","layout":"half","order":30},{"source":"season","label":"季节","role":"detail","layout":"half","order":40},{"source":"sizeRange","label":"尺码段","role":"detail","layout":"half","order":50},{"source":"allowSample","label":"支持拿样","role":"detail","layout":"half","order":60}]}', '{"resubmitOnChange":["title","stockCategory","stockQuantityText","wholesalePriceText","contactPhone"]}', '{"verified":20,"refreshedAt":10,"contactCount":5}', '{"expiringSoonDays":5}', 10),
    ('stock_clearance', '库存出售', 'supply', '{"fields":[{"key":"clearanceCategory","label":"库存品类","type":"select","required":true,"filterable":true,"displayIn":["detail"],"options":["童装","女童","男童","婴童","中大童","面辅料"],"allowCustom":true},{"key":"stockQuantityText","label":"库存数量","type":"text","required":true,"filterable":false,"displayIn":["detail"]},{"key":"packagePriceText","label":"打包价","type":"text","required":true,"filterable":false,"displayIn":["detail"]},{"key":"stockCondition","label":"库存状态","type":"select","required":false,"filterable":true,"displayIn":["detail"],"options":["整包","散货","断码","轻瑕","尾季"],"allowCustom":true},{"key":"warehouseLocation","label":"仓库位置","type":"address","required":false,"filterable":true,"displayIn":["detail"]},{"key":"allowMixedLot","label":"接受混批","type":"boolean","required":false,"filterable":true,"displayIn":["detail"]}]}', '["title","clearanceCategory","stockQuantityText","packagePriceText","contactPhone"]', '["clearanceCategory","stockCondition","warehouseLocation","allowMixedLot"]', '{"group":{"code":"kids_wholesale","name":"童装批发","sort":10},"summary":{"category":"clearanceCategory","quantityText":"stockQuantityText","priceText":"packagePriceText"},"list":["priceText","quantityText","district"],"detail":["clearanceCategory","stockQuantityText","packagePriceText","stockCondition","warehouseLocation","allowMixedLot"],"fields":[{"source":"clearanceCategory","label":"库存品类","role":"core","layout":"half","order":10},{"source":"stockQuantityText","label":"库存数量","role":"core","layout":"half","order":20},{"source":"packagePriceText","label":"打包价","role":"core_price","layout":"half","order":30},{"source":"stockCondition","label":"库存状态","role":"detail","layout":"half","order":40},{"source":"allowMixedLot","label":"接受混批","role":"detail","layout":"half","order":60}]}', '{"resubmitOnChange":["title","clearanceCategory","stockQuantityText","packagePriceText","contactPhone"]}', '{"verified":20,"refreshedAt":10,"contactCount":5}', '{"expiringSoonDays":5}', 7),
    ('buy_kids_goods', '求购尾货', 'demand', '{"fields":[{"key":"targetCategory","label":"求购品类","type":"select","required":true,"filterable":true,"displayIn":["detail"],"options":["卫衣","套装","裙装","裤装","外套","混款"],"allowCustom":true},{"key":"demandQuantityText","label":"求购数量","type":"text","required":true,"filterable":false,"displayIn":["detail"]},{"key":"budgetRange","label":"预算范围","type":"text","required":false,"filterable":false,"displayIn":["detail"]},{"key":"expectedDelivery","label":"期望交付","type":"text","required":false,"filterable":true,"displayIn":["detail"]},{"key":"acceptTailStock","label":"接受尾货/断码","type":"boolean","required":false,"filterable":true,"displayIn":["detail"]},{"key":"purchaseArea","label":"收货区域","type":"text","required":false,"filterable":true,"displayIn":["detail"]}]}', '["title","targetCategory","demandQuantityText","contactPhone"]', '["targetCategory","expectedDelivery","acceptTailStock","purchaseArea"]', '{"group":{"code":"kids_wholesale","name":"童装批发","sort":10},"summary":{"category":"targetCategory","quantityText":"demandQuantityText","priceText":"budgetRange"},"list":["priceText","quantityText","district"],"detail":["targetCategory","demandQuantityText","budgetRange","expectedDelivery","acceptTailStock","purchaseArea"],"fields":[{"source":"targetCategory","label":"求购品类","role":"core","layout":"half","order":10},{"source":"demandQuantityText","label":"求购数量","role":"core","layout":"half","order":20},{"source":"budgetRange","label":"预算范围","role":"core_price","layout":"half","order":30},{"source":"expectedDelivery","label":"期望交付","role":"detail","layout":"half","order":40},{"source":"acceptTailStock","label":"接受尾货/断码","role":"detail","layout":"half","order":50},{"source":"purchaseArea","label":"收货区域","role":"detail","layout":"half","order":60}]}', '{"resubmitOnChange":["title","targetCategory","demandQuantityText","contactPhone"]}', '{"freshDemand":20,"refreshedAt":10}', '{"expiringSoonDays":3}', 7),
    ('fabric_supply', '最新面料', 'supply', '{"fields":[{"key":"fabricType","label":"面料类型","type":"select","required":true,"filterable":true,"displayIn":["detail"],"options":["针织","梭织","卫衣布","罗纹","牛仔","功能面料"],"allowCustom":true},{"key":"fabricComposition","label":"成分","type":"text","required":false,"filterable":false,"displayIn":["detail"]},{"key":"widthWeight","label":"门幅/克重","type":"text","required":true,"filterable":true,"displayIn":["detail"]},{"key":"fabricPriceText","label":"报价","type":"text","required":true,"filterable":false,"displayIn":["detail"]},{"key":"inStockText","label":"现货数量","type":"text","required":false,"filterable":false,"displayIn":["detail"]},{"key":"colorCount","label":"颜色数","type":"number","required":false,"filterable":true,"displayIn":["detail"]}]}', '["title","fabricType","widthWeight","fabricPriceText","contactPhone"]', '["fabricType","widthWeight","colorCount"]', '{"group":{"code":"materials","name":"面料辅料","sort":20},"summary":{"category":"fabricType","quantityText":"inStockText","priceText":"fabricPriceText"},"list":["priceText","quantityText","district"],"detail":["fabricType","fabricComposition","widthWeight","fabricPriceText","inStockText","colorCount"],"fields":[{"source":"fabricType","label":"面料类型","role":"core","layout":"half","order":10},{"source":"fabricComposition","label":"成分","role":"detail","layout":"half","order":20},{"source":"widthWeight","label":"门幅/克重","role":"detail","layout":"half","order":30},{"source":"fabricPriceText","label":"报价","role":"core_price","layout":"half","order":40},{"source":"inStockText","label":"现货数量","role":"core","layout":"half","order":50},{"source":"colorCount","label":"颜色数","role":"detail","layout":"half","order":60}]}', '{"resubmitOnChange":["title","fabricType","widthWeight","fabricPriceText","contactPhone"]}', '{"verified":20,"refreshedAt":10,"contactCount":5}', '{"expiringSoonDays":5}', 15),
    ('accessory_supply', '辅料配饰', 'supply', '{"fields":[{"key":"accessoryType","label":"辅料类型","type":"select","required":true,"filterable":true,"displayIn":["detail"],"options":["纽扣","拉链","织带","吊牌","洗标","包装袋","花边"],"allowCustom":true},{"key":"materialSpec","label":"规格材质","type":"text","required":false,"filterable":false,"displayIn":["detail"]},{"key":"stockQuantityText","label":"库存数量","type":"text","required":true,"filterable":false,"displayIn":["detail"]},{"key":"accessoryPriceText","label":"价格方式","type":"text","required":false,"filterable":false,"displayIn":["detail"]},{"key":"minOrderText","label":"起订量","type":"text","required":false,"filterable":false,"displayIn":["detail"]}]}', '["title","accessoryType","stockQuantityText","contactPhone"]', '["accessoryType","materialSpec"]', '{"group":{"code":"materials","name":"面料辅料","sort":20},"summary":{"category":"accessoryType","quantityText":"stockQuantityText","priceText":"accessoryPriceText"},"list":["priceText","quantityText","district"],"detail":["accessoryType","materialSpec","stockQuantityText","accessoryPriceText","minOrderText"],"fields":[{"source":"accessoryType","label":"辅料类型","role":"core","layout":"half","order":10},{"source":"materialSpec","label":"规格材质","role":"detail","layout":"half","order":20},{"source":"stockQuantityText","label":"库存数量","role":"core","layout":"half","order":30},{"source":"accessoryPriceText","label":"价格方式","role":"core_price","layout":"half","order":40},{"source":"minOrderText","label":"起订量","role":"detail","layout":"half","order":50}]}', '{"resubmitOnChange":["title","accessoryType","stockQuantityText","contactPhone"]}', '{"verified":20,"refreshedAt":10,"contactCount":5}', '{"expiringSoonDays":5}', 15),
    ('processing_accept', '承接加工', 'supply', '{"fields":[{"key":"processCategory","label":"加工品类","type":"select","required":true,"filterable":true,"displayIn":["detail"],"options":["童装","卫衣","套装","针织","梭织","羽绒服"],"allowCustom":true},{"key":"dailyCapacity","label":"日产能","type":"text","required":true,"filterable":true,"displayIn":["detail"]},{"key":"processingMode","label":"加工方式","type":"select","required":false,"filterable":true,"displayIn":["detail"],"options":["包工包料","来料加工","清加工","可沟通"],"allowCustom":true},{"key":"processingPriceText","label":"工价范围","type":"text","required":false,"filterable":false,"displayIn":["detail"]},{"key":"availableSchedule","label":"空档期","type":"select","required":false,"filterable":true,"displayIn":["detail"],"options":["本周可排","下周可排","本月可排","需沟通"],"allowCustom":true},{"key":"acceptSmallOrders","label":"接小单","type":"boolean","required":false,"filterable":true,"displayIn":["detail"]}]}', '["title","processCategory","dailyCapacity","contactPhone"]', '["processCategory","dailyCapacity","processingMode","availableSchedule","acceptSmallOrders"]', '{"group":{"code":"production","name":"加工生产","sort":30},"summary":{"category":"processCategory","quantityText":"dailyCapacity","priceText":"processingPriceText"},"list":["priceText","quantityText","district"],"detail":["processCategory","dailyCapacity","processingMode","processingPriceText","availableSchedule","acceptSmallOrders"],"fields":[{"source":"processCategory","label":"加工品类","role":"core","layout":"half","order":10},{"source":"dailyCapacity","label":"日产能","role":"core","layout":"half","order":20},{"source":"processingMode","label":"加工方式","role":"detail","layout":"half","order":30},{"source":"processingPriceText","label":"工价范围","role":"core_price","layout":"half","order":40},{"source":"availableSchedule","label":"空档期","role":"detail","layout":"half","order":50},{"source":"acceptSmallOrders","label":"接小单","role":"detail","layout":"half","order":60}]}', '{"resubmitOnChange":["title","processCategory","dailyCapacity","contactPhone"]}', '{"verified":20,"refreshedAt":10,"contactCount":5}', '{"expiringSoonDays":5}', 15),
    ('find_factory', '招加工厂', 'demand', '{"fields":[{"key":"targetCategory","label":"加工品类","type":"select","required":true,"filterable":true,"displayIn":["detail"],"options":["童装","卫衣","套装","针织","梭织","羽绒服"],"allowCustom":true},{"key":"orderQuantity","label":"订单数量","type":"text","required":true,"filterable":true,"displayIn":["detail"]},{"key":"deliveryDeadline","label":"交期要求","type":"text","required":true,"filterable":true,"displayIn":["detail"]},{"key":"processingMode","label":"期望方式","type":"select","required":false,"filterable":true,"displayIn":["detail"],"options":["包工包料","来料加工","清加工","可沟通"],"allowCustom":true},{"key":"budgetRange","label":"预算范围","type":"text","required":false,"filterable":false,"displayIn":["detail"]},{"key":"sampleRequired","label":"需要打样","type":"boolean","required":false,"filterable":true,"displayIn":["detail"]}]}', '["title","targetCategory","orderQuantity","deliveryDeadline","contactPhone"]', '["targetCategory","orderQuantity","deliveryDeadline","processingMode","sampleRequired"]', '{"group":{"code":"production","name":"加工生产","sort":30},"summary":{"category":"targetCategory","quantityText":"orderQuantity","priceText":"budgetRange"},"list":["priceText","quantityText","district"],"detail":["targetCategory","orderQuantity","deliveryDeadline","processingMode","budgetRange","sampleRequired"],"fields":[{"source":"targetCategory","label":"加工品类","role":"core","layout":"half","order":10},{"source":"orderQuantity","label":"订单数量","role":"core","layout":"half","order":20},{"source":"deliveryDeadline","label":"交期要求","role":"detail","layout":"full","order":30},{"source":"processingMode","label":"期望方式","role":"detail","layout":"half","order":40},{"source":"budgetRange","label":"预算范围","role":"core_price","layout":"half","order":50},{"source":"sampleRequired","label":"需要打样","role":"detail","layout":"half","order":60}]}', '{"resubmitOnChange":["title","targetCategory","orderQuantity","deliveryDeadline","contactPhone"]}', '{"freshDemand":20,"refreshedAt":10}', '{"expiringSoonDays":3}', 10),
    ('production_support', '生产配套', 'supply', '{"fields":[{"key":"supportType","label":"配套类型","type":"select","required":true,"filterable":true,"displayIn":["detail"],"options":["裁床","整烫","印花","绣花","包装","检品","物流"],"allowCustom":true},{"key":"serviceArea","label":"服务范围","type":"text","required":true,"filterable":true,"displayIn":["detail"]},{"key":"supportPriceText","label":"价格方式","type":"text","required":false,"filterable":false,"displayIn":["detail"]},{"key":"responseTime","label":"响应时效","type":"text","required":false,"filterable":false,"displayIn":["detail"]},{"key":"equipmentAvailable","label":"设备可预约","type":"boolean","required":false,"filterable":true,"displayIn":["detail"]}]}', '["title","supportType","serviceArea","contactPhone"]', '["supportType","serviceArea","equipmentAvailable"]', '{"group":{"code":"production","name":"加工生产","sort":30},"summary":{"category":"supportType","quantityText":"serviceArea","priceText":"supportPriceText"},"list":["priceText","quantityText","district"],"detail":["supportType","serviceArea","supportPriceText","responseTime","equipmentAvailable"],"fields":[{"source":"supportType","label":"配套类型","role":"core","layout":"half","order":10},{"source":"serviceArea","label":"服务范围","role":"core","layout":"half","order":20},{"source":"supportPriceText","label":"价格方式","role":"core_price","layout":"half","order":30},{"source":"responseTime","label":"响应时效","role":"detail","layout":"full","order":40},{"source":"equipmentAvailable","label":"设备可预约","role":"detail","layout":"half","order":50}]}', '{"resubmitOnChange":["title","supportType","serviceArea","contactPhone"]}', '{"verified":20,"refreshedAt":10,"contactCount":5}', '{"expiringSoonDays":5}', 15),
    ('job_hiring', '招聘员工', 'supply', '{"fields":[{"key":"position","label":"岗位","type":"select","required":true,"filterable":true,"displayIn":["detail"],"options":["平车工","拷边工","裁剪工","后道","包装工","主播","客服"],"allowCustom":true},{"key":"payText","label":"薪资/工价","type":"text","required":true,"filterable":true,"displayIn":["detail"]},{"key":"headcount","label":"招聘人数","type":"number","required":true,"filterable":false,"displayIn":["detail"]},{"key":"workLocation","label":"工作地点","type":"address","required":true,"filterable":true,"displayIn":["detail"]},{"key":"includeMealsHousing","label":"包吃住","type":"boolean","required":false,"filterable":true,"displayIn":["detail"]},{"key":"settlementMode","label":"结算方式","type":"select","required":false,"filterable":true,"displayIn":["detail"],"options":["计件","日结","月结","面议"],"allowCustom":true}]}', '["title","position","payText","headcount","workLocation","contactPhone"]', '["position","payText","workLocation","includeMealsHousing","settlementMode"]', '{"group":{"code":"jobs","name":"招聘求职","sort":40},"summary":{"category":"position","quantityText":"headcount","priceText":"payText"},"list":["priceText","quantityText","district"],"detail":["position","payText","headcount","workLocation","includeMealsHousing","settlementMode"],"fields":[{"source":"position","label":"岗位","role":"core","layout":"half","order":10},{"source":"payText","label":"薪资/工价","role":"core_price","layout":"half","order":20},{"source":"headcount","label":"招聘人数","role":"core","layout":"half","order":30},{"source":"includeMealsHousing","label":"包吃住","role":"detail","layout":"half","order":50},{"source":"settlementMode","label":"结算方式","role":"detail","layout":"half","order":60}]}', '{"resubmitOnChange":["title","position","payText","headcount","workLocation","contactPhone"]}', '{"verified":20,"refreshedAt":10,"contactCount":5}', '{"expiringSoonDays":5}', 15),
    ('job_seeking', '我要求职', 'demand', '{"fields":[{"key":"desiredPosition","label":"求职岗位","type":"select","required":true,"filterable":true,"displayIn":["detail"],"options":["平车工","拷边工","裁剪工","后道","包装工","主播","客服"],"allowCustom":true},{"key":"expectedPayText","label":"期望薪资","type":"text","required":false,"filterable":false,"displayIn":["detail"]},{"key":"experienceYears","label":"经验年限","type":"text","required":false,"filterable":true,"displayIn":["detail"]},{"key":"availableTime","label":"到岗时间","type":"text","required":false,"filterable":false,"displayIn":["detail"]},{"key":"expectedLocation","label":"期望地点","type":"text","required":false,"filterable":true,"displayIn":["detail"]}]}', '["title","desiredPosition","contactPhone"]', '["desiredPosition","experienceYears","expectedLocation"]', '{"group":{"code":"jobs","name":"招聘求职","sort":40},"summary":{"category":"desiredPosition","quantityText":"experienceYears","priceText":"expectedPayText"},"list":["priceText","quantityText","district"],"detail":["desiredPosition","expectedPayText","experienceYears","availableTime","expectedLocation"],"fields":[{"source":"desiredPosition","label":"求职岗位","role":"core","layout":"half","order":10},{"source":"expectedPayText","label":"期望薪资","role":"core_price","layout":"half","order":20},{"source":"experienceYears","label":"经验年限","role":"core","layout":"half","order":30},{"source":"availableTime","label":"到岗时间","role":"detail","layout":"half","order":40},{"source":"expectedLocation","label":"期望地点","role":"detail","layout":"half","order":50}]}', '{"resubmitOnChange":["title","desiredPosition","contactPhone"]}', '{"freshDemand":20,"refreshedAt":10}', '{"expiringSoonDays":3}', 15),
    ('sample_rental', '挂样出租', 'supply', '{"fields":[{"key":"sampleRoomType","label":"挂样空间","type":"select","required":true,"filterable":true,"displayIn":["detail"],"options":["档口墙面","样衣间","展厅","共享展位"],"allowCustom":true},{"key":"areaText","label":"面积/位置","type":"text","required":true,"filterable":false,"displayIn":["detail"]},{"key":"rentText","label":"租金/费用","type":"text","required":true,"filterable":false,"displayIn":["detail"]},{"key":"locationText","label":"详细位置","type":"address","required":true,"filterable":true,"displayIn":["detail"]},{"key":"displayCapacity","label":"可挂数量","type":"text","required":false,"filterable":false,"displayIn":["detail"]}]}', '["title","sampleRoomType","areaText","rentText","locationText","contactPhone"]', '["sampleRoomType","locationText"]', '{"group":{"code":"shop_office","name":"商铺办公","sort":50},"summary":{"category":"sampleRoomType","quantityText":"areaText","priceText":"rentText"},"list":["priceText","quantityText","district"],"detail":["sampleRoomType","areaText","rentText","locationText","displayCapacity"],"fields":[{"source":"sampleRoomType","label":"挂样空间","role":"core","layout":"half","order":10},{"source":"areaText","label":"面积/位置","role":"core","layout":"half","order":20},{"source":"rentText","label":"租金/费用","role":"core_price","layout":"half","order":30},{"source":"displayCapacity","label":"可挂数量","role":"detail","layout":"half","order":50}]}', '{"resubmitOnChange":["title","sampleRoomType","areaText","rentText","locationText","contactPhone"]}', '{"verified":20,"refreshedAt":10,"contactCount":5}', '{"expiringSoonDays":5}', 15),
    ('shop_office_rental', '商铺/办公出租', 'supply', '{"fields":[{"key":"spaceType","label":"空间类型","type":"select","required":true,"filterable":true,"displayIn":["detail"],"options":["商铺","办公室","档口","展厅"],"allowCustom":true},{"key":"areaText","label":"面积","type":"text","required":true,"filterable":true,"displayIn":["detail"]},{"key":"rentText","label":"租金","type":"text","required":true,"filterable":true,"displayIn":["detail"]},{"key":"locationText","label":"位置","type":"address","required":true,"filterable":true,"displayIn":["detail"]},{"key":"floor","label":"楼层","type":"text","required":false,"filterable":true,"displayIn":["detail"]},{"key":"availableTime","label":"可入驻时间","type":"text","required":false,"filterable":false,"displayIn":["detail"]}]}', '["title","spaceType","areaText","rentText","locationText","contactPhone"]', '["spaceType","areaText","rentText","locationText","floor"]', '{"group":{"code":"shop_office","name":"商铺办公","sort":50},"summary":{"category":"spaceType","quantityText":"areaText","priceText":"rentText"},"list":["priceText","quantityText","district"],"detail":["spaceType","areaText","rentText","locationText","floor","availableTime"],"fields":[{"source":"spaceType","label":"空间类型","role":"core","layout":"half","order":10},{"source":"areaText","label":"面积","role":"core","layout":"half","order":20},{"source":"rentText","label":"租金","role":"core_price","layout":"half","order":30},{"source":"floor","label":"楼层","role":"detail","layout":"half","order":50},{"source":"availableTime","label":"可入驻时间","role":"detail","layout":"half","order":60}]}', '{"resubmitOnChange":["title","spaceType","areaText","rentText","locationText","contactPhone"]}', '{"verified":20,"refreshedAt":10,"contactCount":5}', '{"expiringSoonDays":5}', 30),
    ('shop_sale', '商铺出售', 'supply', '{"fields":[{"key":"saleType","label":"出售类型","type":"select","required":true,"filterable":true,"displayIn":["detail"],"options":["商铺","档口","办公室","展厅"],"allowCustom":true},{"key":"areaText","label":"面积","type":"text","required":true,"filterable":true,"displayIn":["detail"]},{"key":"salePriceText","label":"售价","type":"text","required":true,"filterable":true,"displayIn":["detail"]},{"key":"locationText","label":"位置","type":"address","required":true,"filterable":true,"displayIn":["detail"]},{"key":"certificateStatus","label":"产权情况","type":"select","required":false,"filterable":true,"displayIn":["detail"],"options":["有证","合同转让","可过户","需沟通"],"allowCustom":true}]}', '["title","saleType","areaText","salePriceText","locationText","contactPhone"]', '["saleType","areaText","salePriceText","locationText","certificateStatus"]', '{"group":{"code":"shop_office","name":"商铺办公","sort":50},"summary":{"category":"saleType","quantityText":"areaText","priceText":"salePriceText"},"list":["priceText","quantityText","district"],"detail":["saleType","areaText","salePriceText","locationText","certificateStatus"],"fields":[{"source":"saleType","label":"出售类型","role":"core","layout":"half","order":10},{"source":"areaText","label":"面积","role":"core","layout":"half","order":20},{"source":"salePriceText","label":"售价","role":"core_price","layout":"half","order":30},{"source":"certificateStatus","label":"产权情况","role":"detail","layout":"half","order":50}]}', '{"resubmitOnChange":["title","saleType","areaText","salePriceText","locationText","contactPhone"]}', '{"verified":20,"refreshedAt":10,"contactCount":5}', '{"expiringSoonDays":5}', 45),
    ('seek_shop_office', '我要求租', 'demand', '{"fields":[{"key":"desiredSpaceType","label":"求租类型","type":"select","required":true,"filterable":true,"displayIn":["detail"],"options":["商铺","办公室","档口","展厅"],"allowCustom":true},{"key":"expectedAreaText","label":"期望面积","type":"text","required":false,"filterable":true,"displayIn":["detail"]},{"key":"budgetRentText","label":"预算租金","type":"text","required":false,"filterable":true,"displayIn":["detail"]},{"key":"preferredDistrict","label":"期望区域","type":"text","required":true,"filterable":true,"displayIn":["detail"]},{"key":"usagePurpose","label":"用途","type":"text","required":false,"filterable":false,"displayIn":["detail"]}]}', '["title","desiredSpaceType","preferredDistrict","contactPhone"]', '["desiredSpaceType","expectedAreaText","budgetRentText","preferredDistrict"]', '{"group":{"code":"shop_office","name":"商铺办公","sort":50},"summary":{"category":"desiredSpaceType","quantityText":"expectedAreaText","priceText":"budgetRentText"},"list":["priceText","quantityText","district"],"detail":["desiredSpaceType","expectedAreaText","budgetRentText","preferredDistrict","usagePurpose"],"fields":[{"source":"desiredSpaceType","label":"求租类型","role":"core","layout":"half","order":10},{"source":"expectedAreaText","label":"期望面积","role":"core","layout":"half","order":20},{"source":"budgetRentText","label":"预算租金","role":"core_price","layout":"half","order":30},{"source":"preferredDistrict","label":"期望区域","role":"detail","layout":"half","order":40},{"source":"usagePurpose","label":"用途","role":"detail","layout":"half","order":50}]}', '{"resubmitOnChange":["title","desiredSpaceType","preferredDistrict","contactPhone"]}', '{"freshDemand":20,"refreshedAt":10}', '{"expiringSoonDays":3}', 15),
    ('apartment_rental', '套房/公寓出租', 'supply', '{"fields":[{"key":"housingType","label":"房源类型","type":"select","required":true,"filterable":true,"displayIn":["detail"],"options":["套房","公寓","宿舍","单间"],"allowCustom":true},{"key":"roomLayout","label":"户型","type":"text","required":false,"filterable":true,"displayIn":["detail"]},{"key":"rentText","label":"租金","type":"text","required":true,"filterable":true,"displayIn":["detail"]},{"key":"locationText","label":"位置","type":"address","required":true,"filterable":true,"displayIn":["detail"]},{"key":"moveInTime","label":"可入住时间","type":"text","required":false,"filterable":false,"displayIn":["detail"]},{"key":"furnished","label":"家具家电齐全","type":"boolean","required":false,"filterable":true,"displayIn":["detail"]}]}', '["title","housingType","rentText","locationText","contactPhone"]', '["housingType","roomLayout","rentText","locationText","furnished"]', '{"group":{"code":"housing","name":"住宅公寓","sort":60},"summary":{"category":"housingType","quantityText":"roomLayout","priceText":"rentText"},"list":["priceText","quantityText","district"],"detail":["housingType","roomLayout","rentText","locationText","moveInTime","furnished"],"fields":[{"source":"housingType","label":"房源类型","role":"core","layout":"half","order":10},{"source":"roomLayout","label":"户型","role":"core","layout":"half","order":20},{"source":"rentText","label":"租金","role":"core_price","layout":"half","order":30},{"source":"moveInTime","label":"可入住时间","role":"detail","layout":"half","order":50},{"source":"furnished","label":"家具家电齐全","role":"detail","layout":"half","order":60}]}', '{"resubmitOnChange":["title","housingType","rentText","locationText","contactPhone"]}', '{"verified":20,"refreshedAt":10,"contactCount":5}', '{"expiringSoonDays":5}', 30),
    ('housing_sale', '住宅出售', 'supply', '{"fields":[{"key":"housingType","label":"住宅类型","type":"select","required":true,"filterable":true,"displayIn":["detail"],"options":["商品房","公寓","自建房","排屋"],"allowCustom":true},{"key":"areaText","label":"面积","type":"text","required":true,"filterable":true,"displayIn":["detail"]},{"key":"salePriceText","label":"售价","type":"text","required":true,"filterable":true,"displayIn":["detail"]},{"key":"locationText","label":"位置","type":"address","required":true,"filterable":true,"displayIn":["detail"]},{"key":"certificateStatus","label":"产权情况","type":"select","required":false,"filterable":true,"displayIn":["detail"],"options":["有证","可过户","按揭中","需沟通"],"allowCustom":true}]}', '["title","housingType","areaText","salePriceText","locationText","contactPhone"]', '["housingType","areaText","salePriceText","locationText","certificateStatus"]', '{"group":{"code":"housing","name":"住宅公寓","sort":60},"summary":{"category":"housingType","quantityText":"areaText","priceText":"salePriceText"},"list":["priceText","quantityText","district"],"detail":["housingType","areaText","salePriceText","locationText","certificateStatus"],"fields":[{"source":"housingType","label":"住宅类型","role":"core","layout":"half","order":10},{"source":"areaText","label":"面积","role":"core","layout":"half","order":20},{"source":"salePriceText","label":"售价","role":"core_price","layout":"half","order":30},{"source":"certificateStatus","label":"产权情况","role":"detail","layout":"half","order":50}]}', '{"resubmitOnChange":["title","housingType","areaText","salePriceText","locationText","contactPhone"]}', '{"verified":20,"refreshedAt":10,"contactCount":5}', '{"expiringSoonDays":5}', 45),
    ('seek_housing', '求租求购', 'demand', '{"fields":[{"key":"desiredHousingType","label":"需求类型","type":"select","required":true,"filterable":true,"displayIn":["detail"],"options":["套房","公寓","宿舍","住宅购买"],"allowCustom":true},{"key":"expectedAreaText","label":"期望面积","type":"text","required":false,"filterable":false,"displayIn":["detail"]},{"key":"budgetRentText","label":"预算","type":"text","required":false,"filterable":false,"displayIn":["detail"]},{"key":"preferredDistrict","label":"期望区域","type":"text","required":true,"filterable":true,"displayIn":["detail"]},{"key":"moveInTime","label":"入住/购买时间","type":"text","required":false,"filterable":false,"displayIn":["detail"]}]}', '["title","desiredHousingType","preferredDistrict","contactPhone"]', '["desiredHousingType","preferredDistrict"]', '{"group":{"code":"housing","name":"住宅公寓","sort":60},"summary":{"category":"desiredHousingType","quantityText":"expectedAreaText","priceText":"budgetRentText"},"list":["priceText","quantityText","district"],"detail":["desiredHousingType","expectedAreaText","budgetRentText","preferredDistrict","moveInTime"],"fields":[{"source":"desiredHousingType","label":"需求类型","role":"core","layout":"half","order":10},{"source":"expectedAreaText","label":"期望面积","role":"core","layout":"half","order":20},{"source":"budgetRentText","label":"预算","role":"core_price","layout":"half","order":30},{"source":"preferredDistrict","label":"期望区域","role":"detail","layout":"half","order":40},{"source":"moveInTime","label":"入住/购买时间","role":"detail","layout":"half","order":50}]}', '{"resubmitOnChange":["title","desiredHousingType","preferredDistrict","contactPhone"]}', '{"freshDemand":20,"refreshedAt":10}', '{"expiringSoonDays":3}', 15),
    ('factory_warehouse_rental', '厂房/仓库出租', 'supply', '{"fields":[{"key":"placeType","label":"场地类型","type":"select","required":true,"filterable":true,"displayIn":["detail"],"options":["厂房","仓库","一楼仓","楼上仓"],"allowCustom":true},{"key":"areaText","label":"面积","type":"text","required":true,"filterable":true,"displayIn":["detail"]},{"key":"rentText","label":"租金","type":"text","required":true,"filterable":true,"displayIn":["detail"]},{"key":"locationText","label":"位置","type":"address","required":true,"filterable":true,"displayIn":["detail"]},{"key":"powerCapacity","label":"电力/配套","type":"text","required":false,"filterable":false,"displayIn":["detail"]},{"key":"truckAccess","label":"货车可进","type":"boolean","required":false,"filterable":true,"displayIn":["detail"]}]}', '["title","placeType","areaText","rentText","locationText","contactPhone"]', '["placeType","areaText","rentText","locationText","truckAccess"]', '{"group":{"code":"factory_warehouse","name":"厂房仓库","sort":70},"summary":{"category":"placeType","quantityText":"areaText","priceText":"rentText"},"list":["priceText","quantityText","district"],"detail":["placeType","areaText","rentText","locationText","powerCapacity","truckAccess"],"fields":[{"source":"placeType","label":"场地类型","role":"core","layout":"half","order":10},{"source":"areaText","label":"面积","role":"core","layout":"half","order":20},{"source":"rentText","label":"租金","role":"core_price","layout":"half","order":30},{"source":"powerCapacity","label":"电力/配套","role":"detail","layout":"half","order":50},{"source":"truckAccess","label":"货车可进","role":"detail","layout":"half","order":60}]}', '{"resubmitOnChange":["title","placeType","areaText","rentText","locationText","contactPhone"]}', '{"verified":20,"refreshedAt":10,"contactCount":5}', '{"expiringSoonDays":5}', 30),
    ('workshop_rental', '加工间出租', 'supply', '{"fields":[{"key":"workshopType","label":"加工间类型","type":"select","required":true,"filterable":true,"displayIn":["detail"],"options":["裁剪间","缝制间","后道间","综合加工间"],"allowCustom":true},{"key":"equipmentIncluded","label":"带设备","type":"boolean","required":false,"filterable":true,"displayIn":["detail"]},{"key":"areaText","label":"面积","type":"text","required":true,"filterable":false,"displayIn":["detail"]},{"key":"rentText","label":"租金","type":"text","required":true,"filterable":false,"displayIn":["detail"]},{"key":"locationText","label":"位置","type":"address","required":true,"filterable":true,"displayIn":["detail"]}]}', '["title","workshopType","areaText","rentText","locationText","contactPhone"]', '["workshopType","equipmentIncluded","locationText"]', '{"group":{"code":"factory_warehouse","name":"厂房仓库","sort":70},"summary":{"category":"workshopType","quantityText":"areaText","priceText":"rentText"},"list":["priceText","quantityText","district"],"detail":["workshopType","equipmentIncluded","areaText","rentText","locationText"],"fields":[{"source":"workshopType","label":"加工间类型","role":"core","layout":"half","order":10},{"source":"equipmentIncluded","label":"带设备","role":"detail","layout":"half","order":20},{"source":"areaText","label":"面积","role":"core","layout":"half","order":30},{"source":"rentText","label":"租金","role":"core_price","layout":"half","order":40}]}', '{"resubmitOnChange":["title","workshopType","areaText","rentText","locationText","contactPhone"]}', '{"verified":20,"refreshedAt":10,"contactCount":5}', '{"expiringSoonDays":5}', 30),
    ('factory_sale', '厂房出售', 'supply', '{"fields":[{"key":"placeType","label":"厂房类型","type":"select","required":true,"filterable":true,"displayIn":["detail"],"options":["独栋厂房","园区厂房","仓储厂房","综合楼"],"allowCustom":true},{"key":"areaText","label":"面积","type":"text","required":true,"filterable":true,"displayIn":["detail"]},{"key":"salePriceText","label":"售价","type":"text","required":true,"filterable":true,"displayIn":["detail"]},{"key":"locationText","label":"位置","type":"address","required":true,"filterable":true,"displayIn":["detail"]},{"key":"certificateStatus","label":"产权情况","type":"select","required":false,"filterable":true,"displayIn":["detail"],"options":["有证","可过户","合同转让","需沟通"],"allowCustom":true},{"key":"powerCapacity","label":"电力容量","type":"text","required":false,"filterable":false,"displayIn":["detail"]}]}', '["title","placeType","areaText","salePriceText","locationText","contactPhone"]', '["placeType","areaText","salePriceText","locationText","certificateStatus"]', '{"group":{"code":"factory_warehouse","name":"厂房仓库","sort":70},"summary":{"category":"placeType","quantityText":"areaText","priceText":"salePriceText"},"list":["priceText","quantityText","district"],"detail":["placeType","areaText","salePriceText","locationText","certificateStatus","powerCapacity"],"fields":[{"source":"placeType","label":"厂房类型","role":"core","layout":"half","order":10},{"source":"areaText","label":"面积","role":"core","layout":"half","order":20},{"source":"salePriceText","label":"售价","role":"core_price","layout":"half","order":30},{"source":"certificateStatus","label":"产权情况","role":"detail","layout":"half","order":50},{"source":"powerCapacity","label":"电力容量","role":"detail","layout":"half","order":60}]}', '{"resubmitOnChange":["title","placeType","areaText","salePriceText","locationText","contactPhone"]}', '{"verified":20,"refreshedAt":10,"contactCount":5}', '{"expiringSoonDays":5}', 45),
    ('seek_factory_warehouse', '我要求租', 'demand', '{"fields":[{"key":"desiredPlaceType","label":"求租类型","type":"select","required":true,"filterable":true,"displayIn":["detail"],"options":["厂房","仓库","加工间","一楼仓"],"allowCustom":true},{"key":"expectedAreaText","label":"期望面积","type":"text","required":false,"filterable":true,"displayIn":["detail"]},{"key":"budgetRentText","label":"预算租金","type":"text","required":false,"filterable":true,"displayIn":["detail"]},{"key":"preferredDistrict","label":"期望区域","type":"text","required":true,"filterable":true,"displayIn":["detail"]},{"key":"powerRequirement","label":"电力需求","type":"text","required":false,"filterable":false,"displayIn":["detail"]},{"key":"truckAccessRequired","label":"需要货车进出","type":"boolean","required":false,"filterable":true,"displayIn":["detail"]}]}', '["title","desiredPlaceType","preferredDistrict","contactPhone"]', '["desiredPlaceType","expectedAreaText","budgetRentText","preferredDistrict","truckAccessRequired"]', '{"group":{"code":"factory_warehouse","name":"厂房仓库","sort":70},"summary":{"category":"desiredPlaceType","quantityText":"expectedAreaText","priceText":"budgetRentText"},"list":["priceText","quantityText","district"],"detail":["desiredPlaceType","expectedAreaText","budgetRentText","preferredDistrict","powerRequirement","truckAccessRequired"],"fields":[{"source":"desiredPlaceType","label":"求租类型","role":"core","layout":"half","order":10},{"source":"expectedAreaText","label":"期望面积","role":"core","layout":"half","order":20},{"source":"budgetRentText","label":"预算租金","role":"core_price","layout":"half","order":30},{"source":"preferredDistrict","label":"期望区域","role":"detail","layout":"half","order":40},{"source":"powerRequirement","label":"电力需求","role":"detail","layout":"half","order":50},{"source":"truckAccessRequired","label":"需要货车进出","role":"detail","layout":"half","order":60}]}', '{"resubmitOnChange":["title","desiredPlaceType","preferredDistrict","contactPhone"]}', '{"freshDemand":20,"refreshedAt":10}', '{"expiringSoonDays":3}', 15),
    ('secondhand_sale', '二手转让', 'supply', '{"fields":[{"key":"itemType","label":"物品类型","type":"select","required":true,"filterable":true,"displayIn":["detail"],"options":["设备","货架","办公家具","电器","车辆","杂项"],"allowCustom":true},{"key":"conditionLevel","label":"成色","type":"select","required":false,"filterable":true,"displayIn":["detail"],"options":["全新","九成新","正常使用","需维修"],"allowCustom":true},{"key":"secondhandPriceText","label":"转让价","type":"text","required":true,"filterable":false,"displayIn":["detail"]},{"key":"secondhandQuantityText","label":"数量","type":"text","required":false,"filterable":false,"displayIn":["detail"]},{"key":"pickupLocation","label":"取货位置","type":"address","required":false,"filterable":true,"displayIn":["detail"]}]}', '["title","itemType","secondhandPriceText","contactPhone"]', '["itemType","conditionLevel","pickupLocation"]', '{"group":{"code":"local_services","name":"本地服务","sort":80},"summary":{"category":"itemType","quantityText":"secondhandQuantityText","priceText":"secondhandPriceText"},"list":["priceText","quantityText","district"],"detail":["itemType","conditionLevel","secondhandPriceText","secondhandQuantityText","pickupLocation"],"fields":[{"source":"itemType","label":"物品类型","role":"core","layout":"half","order":10},{"source":"conditionLevel","label":"成色","role":"detail","layout":"half","order":20},{"source":"secondhandPriceText","label":"转让价","role":"core_price","layout":"half","order":30},{"source":"secondhandQuantityText","label":"数量","role":"core","layout":"half","order":40}]}', '{"resubmitOnChange":["title","itemType","secondhandPriceText","contactPhone"]}', '{"verified":20,"refreshedAt":10,"contactCount":5}', '{"expiringSoonDays":5}', 20),
    ('secondhand_buy', '二手求购', 'demand', '{"fields":[{"key":"wantedItemType","label":"求购物品","type":"select","required":true,"filterable":true,"displayIn":["detail"],"options":["设备","货架","办公家具","电器","车辆","杂项"],"allowCustom":true},{"key":"budgetRange","label":"预算范围","type":"text","required":false,"filterable":false,"displayIn":["detail"]},{"key":"demandQuantityText","label":"需求数量","type":"text","required":false,"filterable":false,"displayIn":["detail"]},{"key":"pickupArea","label":"期望区域","type":"text","required":false,"filterable":true,"displayIn":["detail"]},{"key":"acceptUsedCondition","label":"接受旧货","type":"boolean","required":false,"filterable":true,"displayIn":["detail"]}]}', '["title","wantedItemType","contactPhone"]', '["wantedItemType","pickupArea","acceptUsedCondition"]', '{"group":{"code":"local_services","name":"本地服务","sort":80},"summary":{"category":"wantedItemType","quantityText":"demandQuantityText","priceText":"budgetRange"},"list":["priceText","quantityText","district"],"detail":["wantedItemType","budgetRange","demandQuantityText","pickupArea","acceptUsedCondition"],"fields":[{"source":"wantedItemType","label":"求购物品","role":"core","layout":"half","order":10},{"source":"budgetRange","label":"预算范围","role":"core_price","layout":"half","order":20},{"source":"demandQuantityText","label":"需求数量","role":"core","layout":"half","order":30},{"source":"pickupArea","label":"期望区域","role":"detail","layout":"half","order":40},{"source":"acceptUsedCondition","label":"接受旧货","role":"detail","layout":"half","order":50}]}', '{"resubmitOnChange":["title","wantedItemType","contactPhone"]}', '{"freshDemand":20,"refreshedAt":10}', '{"expiringSoonDays":3}', 15),
    ('education_training', '教育辅导', 'supply', '{"fields":[{"key":"courseType","label":"课程类型","type":"select","required":true,"filterable":true,"displayIn":["detail"],"options":["童装制版","电商运营","直播培训","文化辅导","技能培训"],"allowCustom":true},{"key":"targetAudience","label":"适合对象","type":"text","required":true,"filterable":false,"displayIn":["detail"]},{"key":"coursePriceText","label":"费用","type":"text","required":false,"filterable":false,"displayIn":["detail"]},{"key":"classTime","label":"上课时间","type":"text","required":false,"filterable":false,"displayIn":["detail"]},{"key":"serviceArea","label":"服务区域","type":"text","required":false,"filterable":true,"displayIn":["detail"]}]}', '["title","courseType","targetAudience","contactPhone"]', '["courseType","serviceArea"]', '{"group":{"code":"local_services","name":"本地服务","sort":80},"summary":{"category":"courseType","quantityText":"targetAudience","priceText":"coursePriceText"},"list":["priceText","quantityText","district"],"detail":["courseType","targetAudience","coursePriceText","classTime","serviceArea"],"fields":[{"source":"courseType","label":"课程类型","role":"core","layout":"half","order":10},{"source":"targetAudience","label":"适合对象","role":"core","layout":"half","order":20},{"source":"coursePriceText","label":"费用","role":"core_price","layout":"half","order":30},{"source":"classTime","label":"上课时间","role":"detail","layout":"half","order":40},{"source":"serviceArea","label":"服务区域","role":"detail","layout":"half","order":50}]}', '{"resubmitOnChange":["title","courseType","targetAudience","contactPhone"]}', '{"verified":20,"refreshedAt":10,"contactCount":5}', '{"expiringSoonDays":5}', 30),
    ('appliance_repair', '家电维修', 'supply', '{"fields":[{"key":"applianceType","label":"维修类型","type":"select","required":true,"filterable":true,"displayIn":["detail"],"options":["空调","洗衣机","冰箱","缝纫设备","热水器","综合维修"],"allowCustom":true},{"key":"serviceArea","label":"服务区域","type":"text","required":true,"filterable":true,"displayIn":["detail"]},{"key":"repairPriceText","label":"收费方式","type":"text","required":false,"filterable":false,"displayIn":["detail"]},{"key":"responseTime","label":"上门时效","type":"text","required":false,"filterable":false,"displayIn":["detail"]}]}', '["title","applianceType","serviceArea","contactPhone"]', '["applianceType","serviceArea"]', '{"group":{"code":"local_services","name":"本地服务","sort":80},"summary":{"category":"applianceType","quantityText":"serviceArea","priceText":"repairPriceText"},"list":["priceText","quantityText","district"],"detail":["applianceType","serviceArea","repairPriceText","responseTime"],"fields":[{"source":"applianceType","label":"维修类型","role":"core","layout":"half","order":10},{"source":"serviceArea","label":"服务区域","role":"core","layout":"half","order":20},{"source":"repairPriceText","label":"收费方式","role":"core_price","layout":"half","order":30},{"source":"responseTime","label":"上门时效","role":"detail","layout":"full","order":40}]}', '{"resubmitOnChange":["title","applianceType","serviceArea","contactPhone"]}', '{"verified":20,"refreshedAt":10,"contactCount":5}', '{"expiringSoonDays":5}', 20),
    ('moving_cleaning', '搬家保洁', 'supply', '{"fields":[{"key":"serviceType","label":"服务类型","type":"select","required":true,"filterable":true,"displayIn":["detail"],"options":["搬家","仓库搬运","开荒保洁","日常保洁","拆装"],"allowCustom":true},{"key":"serviceArea","label":"服务区域","type":"text","required":true,"filterable":true,"displayIn":["detail"]},{"key":"movingPriceText","label":"收费方式","type":"text","required":false,"filterable":false,"displayIn":["detail"]},{"key":"appointmentTime","label":"可预约时间","type":"text","required":false,"filterable":false,"displayIn":["detail"]}]}', '["title","serviceType","serviceArea","contactPhone"]', '["serviceType","serviceArea"]', '{"group":{"code":"local_services","name":"本地服务","sort":80},"summary":{"category":"serviceType","quantityText":"serviceArea","priceText":"movingPriceText"},"list":["priceText","quantityText","district"],"detail":["serviceType","serviceArea","movingPriceText","appointmentTime"],"fields":[{"source":"serviceType","label":"服务类型","role":"core","layout":"half","order":10},{"source":"serviceArea","label":"服务区域","role":"core","layout":"half","order":20},{"source":"movingPriceText","label":"收费方式","role":"core_price","layout":"half","order":30},{"source":"appointmentTime","label":"可预约时间","role":"detail","layout":"half","order":40}]}', '{"resubmitOnChange":["title","serviceType","serviceArea","contactPhone"]}', '{"verified":20,"refreshedAt":10,"contactCount":5}', '{"expiringSoonDays":5}', 20),
    ('other_local_service', '其他服务', 'supply', '{"fields":[{"key":"serviceType","label":"服务类型","type":"select","required":true,"filterable":true,"displayIn":["detail"],"options":["跑腿代办","广告制作","摄影拍摄","车辆服务","其他"],"allowCustom":true},{"key":"serviceArea","label":"服务区域","type":"text","required":true,"filterable":true,"displayIn":["detail"]},{"key":"localServicePriceText","label":"收费方式","type":"text","required":false,"filterable":false,"displayIn":["detail"]},{"key":"responseTime","label":"响应时效","type":"text","required":false,"filterable":false,"displayIn":["detail"]}]}', '["title","serviceType","serviceArea","contactPhone"]', '["serviceType","serviceArea"]', '{"group":{"code":"local_services","name":"本地服务","sort":80},"summary":{"category":"serviceType","quantityText":"serviceArea","priceText":"localServicePriceText"},"list":["priceText","quantityText","district"],"detail":["serviceType","serviceArea","localServicePriceText","responseTime"],"fields":[{"source":"serviceType","label":"服务类型","role":"core","layout":"half","order":10},{"source":"serviceArea","label":"服务区域","role":"core","layout":"half","order":20},{"source":"localServicePriceText","label":"收费方式","role":"core_price","layout":"half","order":30},{"source":"responseTime","label":"响应时效","role":"detail","layout":"full","order":40}]}', '{"resubmitOnChange":["title","serviceType","serviceArea","contactPhone"]}', '{"verified":20,"refreshedAt":10,"contactCount":5}', '{"expiringSoonDays":5}', 20)
) AS cfg(
  type_code,
  type_name,
  direction,
  field_schema,
  required_fields,
  filter_fields,
  display_template,
  review_rules,
  sort_weights,
  message_rules,
  default_valid_days
)
ON CONFLICT (city_station_id, type_code) WHERE city_station_id IS NOT NULL
DO UPDATE SET
  type_name = EXCLUDED.type_name,
  field_schema = EXCLUDED.field_schema,
  required_fields = EXCLUDED.required_fields,
  filter_fields = EXCLUDED.filter_fields,
  display_template = EXCLUDED.display_template,
  review_rules = EXCLUDED.review_rules,
  sort_weights = EXCLUDED.sort_weights,
  message_rules = EXCLUDED.message_rules,
  default_valid_days = EXCLUDED.default_valid_days,
  status = EXCLUDED.status,
  direction = EXCLUDED.direction,
  updated_at = now();

-- 发布标签使用 resources.tags 持久化；可选项挂在类型 field_schema 顶层，供小程序发布页渲染多选标签。
UPDATE resource_type_configs rtc
SET field_schema = rtc.field_schema || cfg.tag_config::jsonb,
    updated_at = now()
FROM (
  VALUES
    ('factory_direct', '{"tagOptions":["源头工厂","小单快反","来样定制","长期供货","现货","支持拿样"],"maxTags":8}'),
    ('spot_wholesale', '{"tagOptions":["现货","可混批","支持拿样","整包","断码","尾季"],"maxTags":8}'),
    ('stock_clearance', '{"tagOptions":["现货","可混批","支持看货","整包","断码","轻瑕"],"maxTags":8}'),
    ('buy_kids_goods', '{"tagOptions":["急采","可接受断码","可接受尾货","长期采购","预算明确","可自提"],"maxTags":8}'),
    ('fabric_supply', '{"tagOptions":["现货","可寄样","支持定制","小单起订","颜色齐全","长期供货"],"maxTags":8}'),
    ('accessory_supply', '{"tagOptions":["现货","可寄样","支持定制","小单起订","款式齐全","长期供货"],"maxTags":8}'),
    ('processing_accept', '{"tagOptions":["小单快反","来样加工","包工包料","可打样","交期稳定","长期合作"],"maxTags":8}'),
    ('find_factory', '{"tagOptions":["急找工厂","小单优先","包工包料","来样加工","长期合作","交期明确"],"maxTags":8}'),
    ('production_support', '{"tagOptions":["上门服务","快速响应","长期合作","可开票","支持定制"],"maxTags":8}'),
    ('job_hiring', '{"tagOptions":["急招","包吃住","计件工资","长期招聘","熟练工优先"],"maxTags":8}'),
    ('job_seeking', '{"tagOptions":["随时到岗","熟练工","接受计件","可长期","可夜班"],"maxTags":8}'),
    ('sample_rental', '{"tagOptions":["交通便利","带车位","靠近商圈","可短租","随时入驻","拎包可用"],"maxTags":8}'),
    ('shop_office_rental', '{"tagOptions":["交通便利","带车位","靠近商圈","电梯房","一楼临街","可短租","随时入驻"],"maxTags":8}'),
    ('shop_sale', '{"tagOptions":["一楼临街","交通便利","带车位","靠近商圈","产权清晰","可议价"],"maxTags":8}'),
    ('seek_shop_office', '{"tagOptions":["交通便利","带车位","靠近商圈","电梯房","一楼临街","急租","可长期租"],"maxTags":8}'),
    ('apartment_rental', '{"tagOptions":["交通便利","带车位","靠近商圈","电梯房","家具家电齐全","拎包入住","可短租"],"maxTags":8}'),
    ('housing_sale', '{"tagOptions":["交通便利","带车位","靠近商圈","电梯房","采光好","南北通透","产权清晰"],"maxTags":8}'),
    ('seek_housing', '{"tagOptions":["交通便利","带车位","靠近商圈","电梯房","拎包入住","急租","可长期租"],"maxTags":8}'),
    ('factory_warehouse_rental', '{"tagOptions":["交通便利","带车位","货车可进","近高速","可分租","层高充足","有三相电"],"maxTags":8}'),
    ('workshop_rental', '{"tagOptions":["交通便利","带设备","货车可进","可短租","拎包开工","有三相电"],"maxTags":8}'),
    ('factory_sale', '{"tagOptions":["交通便利","带车位","货车可进","近高速","有三相电","产权清晰"],"maxTags":8}'),
    ('seek_factory_warehouse', '{"tagOptions":["交通便利","带车位","货车可进","近高速","需要三相电","急租","可长期租"],"maxTags":8}'),
    ('secondhand_sale', '{"tagOptions":["现货","成色良好","可现场看","可议价","支持自提"],"maxTags":8}'),
    ('secondhand_buy', '{"tagOptions":["急购","可接受二手","预算明确","可自提","长期求购"],"maxTags":8}'),
    ('education_training', '{"tagOptions":["小班教学","上门辅导","可试听","可预约","长期招生"],"maxTags":8}'),
    ('appliance_repair', '{"tagOptions":["上门维修","快速响应","可预约","配件齐全","可开票"],"maxTags":8}'),
    ('moving_cleaning', '{"tagOptions":["上门服务","快速响应","可预约","可开票","周末可约"],"maxTags":8}'),
    ('other_local_service', '{"tagOptions":["上门服务","快速响应","可预约","可开票","长期服务"],"maxTags":8}')
) AS cfg(type_code, tag_config)
WHERE rtc.city_station_id = (
    SELECT id FROM city_stations WHERE code = 'zhili'
  )
  AND rtc.type_code = cfg.type_code;

WITH zhili AS (
  SELECT id FROM city_stations WHERE code = 'zhili'
),
inserted_topic AS (
  INSERT INTO banner_topics (
    city_station_id,
    kind,
    title,
    subtitle,
    cover_url,
    type_scope,
    jump_type,
    jump_target,
    tags,
    sort_order,
    status
  )
  SELECT
    zhili.id,
    'topic',
    '织里童装供需精选',
    '快速发现童装批发、加工生产和本地服务',
    '',
    '["stock_clearance"]'::jsonb,
    'internal',
    '/pages/search/index',
    '["童装","供需"]'::jsonb,
    90,
    'active'
  FROM zhili
  WHERE NOT EXISTS (
    SELECT 1
    FROM banner_topics bt
    WHERE bt.city_station_id = zhili.id
      AND bt.kind = 'topic'
      AND bt.title = '织里童装供需精选'
  )
  RETURNING id, city_station_id
),
topic AS (
  SELECT id, city_station_id FROM inserted_topic
  UNION ALL
  SELECT bt.id, bt.city_station_id
  FROM banner_topics bt
  JOIN zhili ON zhili.id = bt.city_station_id
  WHERE bt.kind = 'topic'
    AND bt.title = '织里童装供需精选'
  LIMIT 1
)
INSERT INTO banner_topics (
  city_station_id,
  kind,
  title,
  subtitle,
  cover_url,
  type_scope,
  jump_type,
  jump_target,
  tags,
  sort_order,
  status
)
SELECT
  topic.city_station_id,
  'banner',
  '织里童装现货对接',
  '库存、货源、工厂资源一站式服务',
  '',
  '["factory_direct","stock_clearance","processing_accept"]'::jsonb,
  'topic',
  topic.id::text,
  '["首页推荐"]'::jsonb,
  100,
  'active'
FROM topic
WHERE NOT EXISTS (
  SELECT 1
  FROM banner_topics bt
  WHERE bt.city_station_id = topic.city_station_id
    AND bt.kind = 'banner'
    AND bt.title = '织里童装现货对接'
);
