export const resourceTypeText = {
  factory_direct: '工厂直批',
  spot_wholesale: '尾货批发',
  stock_clearance: '库存出售',
  buy_kids_goods: '求购尾货',
  fabric_supply: '最新面料',
  accessory_supply: '辅料配饰',
  processing_accept: '承接加工',
  find_factory: '招加工厂',
  production_support: '生产配套',
  job_hiring: '招聘员工',
  job_seeking: '我要求职',
  sample_rental: '挂样出租',
  shop_office_rental: '商铺/办公出租',
  shop_sale: '商铺出售',
  seek_shop_office: '我要求租',
  apartment_rental: '套房/公寓出租',
  housing_sale: '住宅出售',
  seek_housing: '求租求购',
  factory_warehouse_rental: '厂房/仓库出租',
  workshop_rental: '加工间出租',
  factory_sale: '厂房出售',
  seek_factory_warehouse: '我要求租',
  secondhand_sale: '二手转让',
  secondhand_buy: '二手求购',
  education_training: '教育辅导',
  appliance_repair: '家电维修',
  moving_cleaning: '搬家保洁',
  other_local_service: '其他服务',
}

export const resourceStatusText = {
  draft: '草稿',
  pending: '自动检测中',
  manual_review: '异常处理中',
  audit_retry: '自动检测重试中',
  published: '已发布',
  rejected: '已驳回',
  taken_down: '已下架',
  expired: '已过期',
  dealt: '已成交',
}

export const merchantTypeText = {
  individual: '个人',
  rental_provider: '场地/设备方',
  factory: '源头工厂',
  stall: '现货档口',
  stockist: '库存货源',
  service_provider: '配套服务',
  buyer: '采购',
}
