import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import test from 'node:test'

const root = path.resolve(new URL('../..', import.meta.url).pathname)

test('vip page is registered and shows vip benefits with add-on quota tab', () => {
  const pagesConfig = JSON.parse(fs.readFileSync(path.join(root, 'pages.json'), 'utf8'))
  const pagePaths = pagesConfig.pages.map((item) => item.path)
  const source = fs.readFileSync(path.join(root, 'pages/vip/index.vue'), 'utf8')
  const apiSource = fs.readFileSync(path.join(root, 'api/vip.js'), 'utf8')

  assert.ok(pagePaths.includes('pages/vip/index'))
  assert.match(apiSource, /listVIPPlans/)
  assert.match(apiSource, /\/api\/v1\/vip\/plans/)
  assert.match(apiSource, /listQuotaPacks/)
  assert.match(apiSource, /\/api\/v1\/vip\/quota-packs/)
  assert.match(apiSource, /getMerchantVIP/)
  assert.match(apiSource, /createVIPOrder/)
  assert.match(apiSource, /createQuotaPackOrder/)
  assert.match(apiSource, /createVIPPayment/)
  assert.match(source, /VIP权益包/)
  assert.match(source, /购买次数/)
  assert.doesNotMatch(source, /VIP 仅包含发布、刷新、置顶等经营权益，不代表平台认证/)
  assert.match(source, /publishQuota \|\| 80/)
  assert.match(source, /refreshQuota \|\| 30/)
  assert.match(source, /durationMonths \|\| 1/)
  assert.match(source, /每 30 天到账/)
  assert.match(source, /开通后到账/)
  assert.doesNotMatch(source, /每张置顶券可让 1 条已发布资源置顶 24 小时/)
  assert.match(source, /VIP 赠送的发布额度和刷新次数均在发放后 30 天内有效/)
  assert.doesNotMatch(source, /均当月有效/)
  assert.match(source, /单独购买的次数包有效期 180 天/)
  assert.match(source, /立即开通 VIP/)
  assert.match(source, /发布次数包/)
  assert.match(source, /刷新次数包/)
  assert.doesNotMatch(source, /置顶券包/)
  assert.match(source, /loadQuotaPacks/)
  assert.match(source, /openQuotaPack/)
  assert.match(source, /createQuotaPackOrder/)
  assert.match(source, /¥25 购买/)
  assert.match(source, /¥19 购买/)
  assert.doesNotMatch(source, /¥29 购买/)
  assert.match(source, /filterAvailableQuotaPacks/)
  assert.match(source, /function isTopVoucherPack\(item\)/)
  assert.doesNotMatch(source, /open-type="contact"/)
  assert.doesNotMatch(source, /联系平台购买/)
  assert.doesNotMatch(source, /class="status-band"/)
  assert.doesNotMatch(source, /class="status-title"/)
  assert.doesNotMatch(source, /class="status-subtitle"/)
  assert.doesNotMatch(source, /class="status-pill"/)
  assert.doesNotMatch(source, /class="benefit-strip"/)
  assert.doesNotMatch(source, /class="launch-offer"/)
  assert.doesNotMatch(source, /限时特价：年卡 ¥299/)
  assert.doesNotMatch(source, /每月 80 条发布额度 · 30 次刷新 · 3 张置顶券/)
  assert.doesNotMatch(source, /冷启动/)
  assert.doesNotMatch(source, /getMerchantVIP/)
  assert.doesNotMatch(source, /loadVIPStatus/)
  assert.doesNotMatch(source, /vipStatus/)
  assert.match(source, /await requestWechatPayment\(payment\)/)
  assert.match(source, /resp\.status === 'paid'/)
})
