// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5

package handler

import (
	"net/http"

	adminauth "wplink/backend/app/internal/handler/adminauth"
	adminbannertopic "wplink/backend/app/internal/handler/adminbannertopic"
	adminconfig "wplink/backend/app/internal/handler/adminconfig"
	admindashboard "wplink/backend/app/internal/handler/admindashboard"
	adminentitlement "wplink/backend/app/internal/handler/adminentitlement"
	adminhotsearchkeyword "wplink/backend/app/internal/handler/adminhotsearchkeyword"
	adminlog "wplink/backend/app/internal/handler/adminlog"
	adminmerchant "wplink/backend/app/internal/handler/adminmerchant"
	adminpermission "wplink/backend/app/internal/handler/adminpermission"
	adminresource "wplink/backend/app/internal/handler/adminresource"
	adminvipconfig "wplink/backend/app/internal/handler/adminvipconfig"
	auth "wplink/backend/app/internal/handler/auth"
	callback "wplink/backend/app/internal/handler/callback"
	city "wplink/backend/app/internal/handler/city"
	discovery "wplink/backend/app/internal/handler/discovery"
	entitlement "wplink/backend/app/internal/handler/entitlement"
	favorite "wplink/backend/app/internal/handler/favorite"
	location "wplink/backend/app/internal/handler/location"
	maphandler "wplink/backend/app/internal/handler/map"
	merchant "wplink/backend/app/internal/handler/merchant"
	message "wplink/backend/app/internal/handler/message"
	metrics "wplink/backend/app/internal/handler/metrics"
	resource "wplink/backend/app/internal/handler/resource"
	upload "wplink/backend/app/internal/handler/upload"
	vip "wplink/backend/app/internal/handler/vip"
	"wplink/backend/app/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/auth/login",
				Handler: adminauth.AdminLoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/admin"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/banner-topics",
				Handler: adminbannertopic.AdminListBannerTopicsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/banner-topics",
				Handler: adminbannertopic.AdminCreateBannerTopicHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/banner-topics/:configId",
				Handler: adminbannertopic.AdminUpdateBannerTopicHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/admin"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/resource-type-configs",
				Handler: adminconfig.AdminListResourceTypeConfigsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/resource-type-configs",
				Handler: adminconfig.AdminCreateResourceTypeConfigHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/resource-type-configs/:configId",
				Handler: adminconfig.AdminUpdateResourceTypeConfigHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/admin"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/dashboard/overview",
				Handler: admindashboard.AdminDashboardOverviewHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/admin"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/merchants/:merchantId/entitlements",
				Handler: adminentitlement.AdminGrantMerchantEntitlementHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/admin"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/hot-search-keywords",
				Handler: adminhotsearchkeyword.AdminListHotSearchKeywordsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/hot-search-keywords",
				Handler: adminhotsearchkeyword.AdminCreateHotSearchKeywordHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/hot-search-keywords/:configId",
				Handler: adminhotsearchkeyword.AdminUpdateHotSearchKeywordHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/admin"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/operation-logs",
				Handler: adminlog.AdminListOperationLogsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/search-logs",
				Handler: adminlog.AdminListSearchLogsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/tasks/resource-lifecycle/run",
				Handler: adminlog.AdminRunResourceLifecycleHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/admin"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/merchants",
				Handler: adminmerchant.AdminListMerchantsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/admin"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/module-permissions",
				Handler: adminpermission.AdminListModulePermissionsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/module-permissions/:roleCode",
				Handler: adminpermission.AdminUpdateRoleModulePermissionsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/operators",
				Handler: adminpermission.AdminListOperatorsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/operators",
				Handler: adminpermission.AdminCreateOperatorHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/operators/:operatorId",
				Handler: adminpermission.AdminUpdateOperatorHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/operators/:operatorId/status",
				Handler: adminpermission.AdminUpdateOperatorStatusHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/admin"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/resource-reports",
				Handler: adminresource.AdminListResourceReportsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/resource-reports/:reportId/review",
				Handler: adminresource.AdminReviewResourceReportHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/resources/:resourceId/review",
				Handler: adminresource.AdminReviewResourceHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/resources/pending",
				Handler: adminresource.AdminListPendingResourcesHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/admin"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/vip/plans",
				Handler: adminvipconfig.AdminListVIPPlansHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/vip/plans",
				Handler: adminvipconfig.AdminCreateVIPPlanHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/vip/plans/:planCode",
				Handler: adminvipconfig.AdminUpdateVIPPlanHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/vip/promotions",
				Handler: adminvipconfig.AdminListVIPPromotionsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/vip/promotions",
				Handler: adminvipconfig.AdminCreateVIPPromotionHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/vip/promotions/:promotionCode",
				Handler: adminvipconfig.AdminUpdateVIPPromotionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/vip/quota-packs",
				Handler: adminvipconfig.AdminListQuotaPacksHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/vip/quota-packs",
				Handler: adminvipconfig.AdminCreateQuotaPackHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/vip/quota-packs/:packCode",
				Handler: adminvipconfig.AdminUpdateQuotaPackHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/admin"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/auth/sms-code",
				Handler: auth.SendSMSCodeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/auth/wechat-login",
				Handler: auth.WechatLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/me",
				Handler: auth.GetMeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/me/account-deletion",
				Handler: auth.DeleteAccountHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/me/phone",
				Handler: auth.BindPhoneHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/me/wechat-phone",
				Handler: auth.BindWechatPhoneHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/wechat-pay/notify",
				Handler: callback.WechatPayNotifyHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/wechat/content-audit/media-callback",
				Handler: callback.VerifyContentAuditCallbackHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/wechat/content-audit/media-callback",
				Handler: callback.HandleContentAuditCallbackHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/city-stations",
				Handler: city.ListCityStationsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/city-stations/:cityCode/resource-types",
				Handler: city.ListCityResourceTypesHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/home/operation-config",
				Handler: discovery.GetHomeOperationConfigHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/home/recent-merchants",
				Handler: discovery.ListHomeRecentMerchantsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/home/resources",
				Handler: discovery.ListHomeResourcesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/search/hot-keywords",
				Handler: discovery.ListHotSearchKeywordsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/topics/:topicId/resources",
				Handler: discovery.GetTopicResourcesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/webview/validate",
				Handler: discovery.ValidateWebviewHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/merchants/:merchantId/entitlements",
				Handler: entitlement.ListMerchantEntitlementsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/merchants/:merchantId/entitlements/:entitlementId/usage-records",
				Handler: entitlement.ListEntitlementUsageRecordsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/merchants/:merchantId/top-vouchers",
				Handler: entitlement.ListTopVouchersHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/top-vouchers/:voucherId/redeem",
				Handler: entitlement.RedeemTopVoucherHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/me/favorite-resources",
				Handler: favorite.ListFavoriteResourcesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/me/favorite-resources/:resourceId",
				Handler: favorite.GetResourceFavoriteStateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/me/favorite-resources/:resourceId",
				Handler: favorite.SetResourceFavoriteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/me/followed-merchants",
				Handler: favorite.ListFollowedMerchantsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/me/followed-merchants/:merchantId",
				Handler: favorite.GetMerchantFollowStateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/me/followed-merchants/:merchantId",
				Handler: favorite.SetMerchantFollowHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/me/saved-searches",
				Handler: favorite.ListSavedSearchesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/me/saved-searches",
				Handler: favorite.CreateSavedSearchHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/me/saved-searches/:savedSearchId",
				Handler: favorite.DeleteSavedSearchHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/locations/reverse-geocode",
				Handler: location.ReverseGeocodeHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/map/bind-candidates",
				Handler: maphandler.ListMapBindCandidatesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/map/categories",
				Handler: maphandler.ListMapCategoriesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/map/merchant-places",
				Handler: maphandler.ListMerchantPlacesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/map/merchants/:merchantId/location-context",
				Handler: maphandler.GetMerchantLocationContextHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/map/objects/:objectId",
				Handler: maphandler.GetMapObjectHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/map/objects/:objectId/location-corrections",
				Handler: maphandler.SubmitMapLocationCorrectionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/map/objects/:objectId/nearby-pois",
				Handler: maphandler.ListNearbyPoisHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/map/objects/:objectId/risk-reports",
				Handler: maphandler.SubmitMapRiskReportHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/map/objects/search",
				Handler: maphandler.SearchMapObjectsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/map/scenes",
				Handler: maphandler.ListMapScenesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/map/scenes/:sceneCode",
				Handler: maphandler.GetMapSceneHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/map/scenes/:sceneCode/objects",
				Handler: maphandler.ListMapObjectsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/merchants/:merchantId/map-binding",
				Handler: maphandler.GetMerchantMapBindingHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/merchants/:merchantId/map-binding-requests",
				Handler: maphandler.SubmitMapBindRequestHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/map/bind-requests",
				Handler: maphandler.AdminListMapBindRequestsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/map/bind-requests/:requestId/review",
				Handler: maphandler.AdminReviewMapBindRequestHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/map/categories",
				Handler: maphandler.AdminListMapCategoriesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/map/categories",
				Handler: maphandler.AdminSaveMapCategoryHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/map/objects/:objectId",
				Handler: maphandler.AdminUpdateMapObjectHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/map/objects/:objectId/status",
				Handler: maphandler.AdminUpdateMapObjectStatusHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/map/scenes",
				Handler: maphandler.AdminListMapScenesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/map/scenes",
				Handler: maphandler.AdminSaveMapSceneHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/map/scenes/:sceneCode",
				Handler: maphandler.AdminGetMapSceneHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/map/scenes/:sceneCode",
				Handler: maphandler.AdminUpdateMapSceneHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/map/scenes/:sceneCode/objects",
				Handler: maphandler.AdminListMapObjectsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/map/scenes/:sceneCode/objects",
				Handler: maphandler.AdminSaveMapObjectHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/map/scenes/:sceneCode/objects/batch-generate",
				Handler: maphandler.AdminBatchGenerateMapObjectsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/map/scenes/:sceneCode/publish",
				Handler: maphandler.AdminPublishMapSceneHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/admin"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/merchants/:merchantId",
				Handler: merchant.GetMerchantHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/merchants/:merchantId",
				Handler: merchant.UpdateMerchantHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/messages",
				Handler: message.ListMessagesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/messages/:messageId/read",
				Handler: message.ReadMessageHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/merchants/:merchantId/metrics/summary",
				Handler: metrics.GetMerchantMetricsSummaryHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/metrics/exposures/batch",
				Handler: metrics.RecordResourceExposuresHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/metrics/merchant-map-events",
				Handler: metrics.RecordMerchantMapEventHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/resources/:resourceId/metrics",
				Handler: metrics.GetResourceMetricsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/me/resources",
				Handler: resource.ListMyResourcesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/me/resources/:resourceId/detail",
				Handler: resource.GetOwnResourceHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/me/resources/:resourceId/edit",
				Handler: resource.GetEditableResourceHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/resource-search",
				Handler: resource.SearchResourcesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/resources",
				Handler: resource.CreateResourceHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/resources",
				Handler: resource.ListResourcesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/resources/:resourceId",
				Handler: resource.GetResourceHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/resources/:resourceId",
				Handler: resource.DeleteTakenDownResourceHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/resources/:resourceId/contact-events",
				Handler: resource.CreateResourceContactEventHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/resources/:resourceId/contact-unlock-orders",
				Handler: resource.CreateContactUnlockOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/resources/:resourceId/contact-unlock-orders/:orderId/payment",
				Handler: resource.CreateContactUnlockPaymentHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/resources/:resourceId/deal-feedback",
				Handler: resource.MarkResourceDealHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/resources/:resourceId/detail-view",
				Handler: resource.RecordResourceDetailViewHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/resources/:resourceId/draft",
				Handler: resource.UpdateResourceDraftHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/resources/:resourceId/refresh",
				Handler: resource.RefreshResourceHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/resources/:resourceId/related",
				Handler: resource.ListRelatedResourcesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/resources/:resourceId/reports",
				Handler: resource.ReportResourceHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/resources/:resourceId/repost-similar",
				Handler: resource.RepostSimilarResourceHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/resources/:resourceId/submit",
				Handler: resource.SubmitResourceHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/resources/:resourceId/take-down",
				Handler: resource.TakeDownOwnResourceHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/resources/drafts",
				Handler: resource.CreateResourceDraftHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/uploads/token",
				Handler: upload.CreateUploadTokenHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/merchants/:merchantId/vip",
				Handler: vip.GetMerchantVIPHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/merchants/:merchantId/vip/orders",
				Handler: vip.CreateVIPOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/merchants/:merchantId/vip/orders/:orderId/payment",
				Handler: vip.CreateVIPPaymentHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/vip/plans",
				Handler: vip.ListVIPPlansHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/vip/quota-packs",
				Handler: vip.ListQuotaPacksHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
