// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5

package types

type AdminAddMatchParticipantsReq struct {
	ParticipantMerchantIds []string `json:"participantMerchantIds"`
}

type AdminAddMatchResourcesReq struct {
	ResourceIds []string `json:"resourceIds"`
}

type AdminBannerTopicItem struct {
	Id         string   `json:"id"`
	CityCode   string   `json:"cityCode,optional"`
	Kind       string   `json:"kind"`
	Title      string   `json:"title"`
	Subtitle   string   `json:"subtitle,optional"`
	CoverUrl   string   `json:"coverUrl,optional"`
	TypeScope  []string `json:"typeScope"`
	JumpType   string   `json:"jumpType"`
	JumpTarget string   `json:"jumpTarget"`
	Tags       []string `json:"tags"`
	StartAt    string   `json:"startAt,optional"`
	EndAt      string   `json:"endAt,optional"`
	SortOrder  int64    `json:"sortOrder"`
	Status     string   `json:"status"`
	UpdatedAt  string   `json:"updatedAt"`
}

type AdminBatchGenerateMapObjectsReq struct {
	StartCode     string   `json:"startCode"`
	Count         int64    `json:"count"`
	Direction     string   `json:"direction"`
	StartX        string   `json:"startX"`
	StartY        string   `json:"startY"`
	Width         string   `json:"width"`
	Height        string   `json:"height"`
	Gap           string   `json:"gap"`
	Type          string   `json:"type"`
	Layer         string   `json:"layer"`
	CategoryCodes []string `json:"categoryCodes,optional"`
	ServiceTags   []string `json:"serviceTags,optional"`
}

type AdminBatchGenerateMapObjectsResp struct {
	Items []MapObjectItem `json:"items"`
}

type AdminCreateMatchCaseReq struct {
	PurchaseDemandId       string   `json:"purchaseDemandId"`
	ResourceIds            []string `json:"resourceIds,optional"`
	ParticipantMerchantIds []string `json:"participantMerchantIds,optional"`
	ResultNote             string   `json:"resultNote,optional"`
}

type AdminCreateMatchCaseResp struct {
	Id      string `json:"id"`
	Status  string `json:"status"`
	Message string `json:"message"`
}

type AdminDashboardMetrics struct {
	PendingResourceCount     int64 `json:"pendingResourceCount"`
	PendingVerificationCount int64 `json:"pendingVerificationCount"`
	PendingDemandCount       int64 `json:"pendingDemandCount"`
	TodayContactCount        int64 `json:"todayContactCount"`
}

type AdminDashboardOverviewReq struct {
	CityCode string `form:"cityCode,optional"`
}

type AdminDashboardOverviewResp struct {
	Metrics AdminDashboardMetrics `json:"metrics"`
	Tasks   []AdminDashboardTask  `json:"tasks"`
}

type AdminDashboardTask struct {
	Type      string `json:"type"`
	Title     string `json:"title"`
	CityName  string `json:"cityName"`
	CreatedAt string `json:"createdAt"`
}

type AdminDemandContact struct {
	Name   string `json:"name"`
	Phone  string `json:"phone"`
	Wechat string `json:"wechat,optional"`
}

type AdminDemandDetailResp struct {
	Id                  string                 `json:"id"`
	Title               string                 `json:"title"`
	DemandType          string                 `json:"demandType"`
	Category            string                 `json:"category"`
	PriceRange          map[string]interface{} `json:"priceRange"`
	QuantityRequirement map[string]interface{} `json:"quantityRequirement"`
	Attributes          map[string]interface{} `json:"attributes"`
	Contact             AdminDemandContact     `json:"contact"`
	Status              string                 `json:"status"`
	CreatedAt           string                 `json:"createdAt"`
}

type AdminDemandListItem struct {
	Id          string `json:"id"`
	Title       string `json:"title"`
	DemandType  string `json:"demandType"`
	Category    string `json:"category"`
	ContactName string `json:"contactName"`
	Status      string `json:"status"`
	CreatedAt   string `json:"createdAt"`
}

type AdminGrantEntitlementReq struct {
	EntitlementType string `json:"entitlementType"`
	SourceType      string `json:"sourceType"`
	TotalAmount     int64  `json:"totalAmount"`
	ExpiresAt       string `json:"expiresAt,optional"`
	Reason          string `json:"reason"`
}

type AdminGrantEntitlementResp struct {
	Id      string `json:"id"`
	Message string `json:"message"`
}

type AdminHotSearchKeywordItem struct {
	Id        string `json:"id"`
	CityCode  string `json:"cityCode,optional"`
	Keyword   string `json:"keyword"`
	SortOrder int64  `json:"sortOrder"`
	Status    string `json:"status"`
	StartAt   string `json:"startAt,optional"`
	EndAt     string `json:"endAt,optional"`
	UpdatedAt string `json:"updatedAt"`
}

type AdminListBannerTopicsReq struct {
	CityCode string `form:"cityCode,optional"`
	Kind     string `form:"kind,optional"`
	Status   string `form:"status,optional"`
}

type AdminListBannerTopicsResp struct {
	Items []AdminBannerTopicItem `json:"items"`
}

type AdminListDemandsReq struct {
	CityCode   string `form:"cityCode,optional"`
	DemandType string `form:"demandType,optional"`
	Status     string `form:"status,optional"`
	Page       int64  `form:"page,optional"`
	PageSize   int64  `form:"pageSize,optional"`
}

type AdminListDemandsResp struct {
	Items    []AdminDemandListItem `json:"items"`
	Page     int64                 `json:"page"`
	PageSize int64                 `json:"pageSize"`
	Total    int64                 `json:"total"`
}

type AdminListHotSearchKeywordsReq struct {
	CityCode string `form:"cityCode,optional"`
	Status   string `form:"status,optional"`
}

type AdminListHotSearchKeywordsResp struct {
	Items []AdminHotSearchKeywordItem `json:"items"`
}

type AdminListMapCategoriesReq struct {
	Type   string `form:"type,optional"`
	Status string `form:"status,optional"`
}

type AdminListMapCategoriesResp struct {
	Items []MapCategoryItem `json:"items"`
}

type AdminListMapObjectsReq struct {
	Types   string `form:"types,optional"`
	Status  string `form:"status,optional"`
	Keyword string `form:"keyword,optional"`
	MinX    string `form:"minX,optional"`
	MinY    string `form:"minY,optional"`
	MaxX    string `form:"maxX,optional"`
	MaxY    string `form:"maxY,optional"`
	Zoom    int64  `form:"zoom,optional"`
}

type AdminListMapScenesReq struct {
	CityCode string `form:"cityCode,optional"`
	Status   string `form:"status,optional"`
	Type     string `form:"type,optional"`
}

type AdminListMatchCasesReq struct {
	Status   string `form:"status,optional"`
	Page     int64  `form:"page,optional"`
	PageSize int64  `form:"pageSize,optional"`
}

type AdminListMatchCasesResp struct {
	Items    []AdminMatchCaseItem `json:"items"`
	Page     int64                `json:"page"`
	PageSize int64                `json:"pageSize"`
	Total    int64                `json:"total"`
}

type AdminListMerchantsReq struct {
	CityCode     string `form:"cityCode,optional"`
	MerchantType string `form:"merchantType,optional"`
	Status       string `form:"status,optional"`
	Keyword      string `form:"keyword,optional"`
	Page         int64  `form:"page,optional"`
	PageSize     int64  `form:"pageSize,optional"`
}

type AdminListMerchantsResp struct {
	Items    []AdminMerchantListItem `json:"items"`
	Page     int64                   `json:"page"`
	PageSize int64                   `json:"pageSize"`
	Total    int64                   `json:"total"`
}

type AdminListResourceTypeConfigsReq struct {
	CityCode string `form:"cityCode,optional"`
	Status   string `form:"status,optional"`
}

type AdminListResourceTypeConfigsResp struct {
	Items []AdminResourceTypeConfigItem `json:"items"`
}

type AdminLoginReq struct {
	LoginName string `json:"loginName"`
	Password  string `json:"password"`
}

type AdminLoginResp struct {
	Token  string   `json:"token"`
	UserId string   `json:"userId"`
	Roles  []string `json:"roles"`
}

type AdminMatchCaseActionResp struct {
	Id      string `json:"id"`
	Status  string `json:"status,optional"`
	Message string `json:"message"`
}

type AdminMatchCaseItem struct {
	Id               string `json:"id"`
	PurchaseDemandId string `json:"purchaseDemandId"`
	DemandTitle      string `json:"demandTitle"`
	Status           string `json:"status"`
	Source           string `json:"source"`
	ResultNote       string `json:"resultNote,optional"`
	ResourceCount    int64  `json:"resourceCount"`
	ParticipantCount int64  `json:"participantCount"`
	CreatedAt        string `json:"createdAt"`
}

type AdminMerchantListItem struct {
	Id                 string `json:"id"`
	Name               string `json:"name"`
	MerchantType       string `json:"merchantType"`
	VerificationStatus string `json:"verificationStatus"`
	Status             string `json:"status"`
	LastActiveAt       string `json:"lastActiveAt,optional"`
}

type AdminOperationLogItem struct {
	Id           string `json:"id"`
	OperatorId   string `json:"operatorId"`
	OperatorRole string `json:"operatorRole"`
	ObjectType   string `json:"objectType"`
	ObjectId     string `json:"objectId,optional"`
	Action       string `json:"action"`
	Reason       string `json:"reason,optional"`
	CreatedAt    string `json:"createdAt"`
}

type AdminOperationLogsReq struct {
	ObjectType string `form:"objectType,optional"`
	ObjectId   string `form:"objectId,optional"`
	OperatorId string `form:"operatorId,optional"`
	Page       int64  `form:"page,optional"`
	PageSize   int64  `form:"pageSize,optional"`
}

type AdminOperationLogsResp struct {
	Items    []AdminOperationLogItem `json:"items"`
	Page     int64                   `json:"page"`
	PageSize int64                   `json:"pageSize"`
	Total    int64                   `json:"total"`
}

type AdminPendingResourceItem struct {
	Id           string `json:"id"`
	Title        string `json:"title"`
	TypeCode     string `json:"typeCode"`
	MerchantName string `json:"merchantName"`
	CreatedAt    string `json:"createdAt"`
}

type AdminPendingResourcesReq struct {
	CityCode string `form:"cityCode,optional"`
	TypeCode string `form:"typeCode,optional"`
	Page     int64  `form:"page,optional"`
	PageSize int64  `form:"pageSize,optional"`
}

type AdminPendingResourcesResp struct {
	Items    []AdminPendingResourceItem `json:"items"`
	Page     int64                      `json:"page"`
	PageSize int64                      `json:"pageSize"`
	Total    int64                      `json:"total"`
}

type AdminPendingVerificationItem struct {
	Id               string                 `json:"id"`
	MerchantId       string                 `json:"merchantId"`
	MerchantName     string                 `json:"merchantName"`
	VerificationType string                 `json:"verificationType"`
	Status           string                 `json:"status"`
	SubmittedAt      string                 `json:"submittedAt"`
	BusinessName     string                 `json:"businessName"`
	LicenseUrl       string                 `json:"licenseUrl"`
	StorefrontUrl    string                 `json:"storefrontUrl"`
	Materials        map[string]interface{} `json:"materials"`
}

type AdminPendingVerificationsReq struct {
	Page     int64 `form:"page,optional"`
	PageSize int64 `form:"pageSize,optional"`
}

type AdminPendingVerificationsResp struct {
	Items    []AdminPendingVerificationItem `json:"items"`
	Page     int64                          `json:"page"`
	PageSize int64                          `json:"pageSize"`
	Total    int64                          `json:"total"`
}

type AdminPublishMapSceneResp struct {
	Item    MapSceneItem `json:"item"`
	Message string       `json:"message"`
}

type AdminResourceTypeConfigItem struct {
	Id               string                 `json:"id"`
	CityCode         string                 `json:"cityCode,optional"`
	TypeCode         string                 `json:"typeCode"`
	TypeName         string                 `json:"typeName"`
	FieldSchema      map[string]interface{} `json:"fieldSchema"`
	RequiredFields   []string               `json:"requiredFields"`
	FilterFields     []string               `json:"filterFields"`
	DisplayTemplate  map[string]interface{} `json:"displayTemplate"`
	ReviewRules      map[string]interface{} `json:"reviewRules"`
	SortWeights      map[string]interface{} `json:"sortWeights"`
	MessageRules     map[string]interface{} `json:"messageRules"`
	DefaultValidDays int64                  `json:"defaultValidDays"`
	Status           string                 `json:"status"`
}

type AdminReviewResourceReq struct {
	Action string `json:"action"`
	Reason string `json:"reason,optional"`
}

type AdminReviewResourceResp struct {
	Id      string `json:"id"`
	Status  string `json:"status"`
	Message string `json:"message"`
}

type AdminReviewVerificationReq struct {
	Action     string `json:"action"`
	ReviewNote string `json:"reviewNote,optional"`
}

type AdminReviewVerificationResp struct {
	Id      string `json:"id"`
	Status  string `json:"status"`
	Message string `json:"message"`
}

type AdminRunResourceLifecycleResp struct {
	ExpiredCount          int64 `json:"expiredCount"`
	ExpiringReminderCount int64 `json:"expiringReminderCount"`
}

type AdminSaveBannerTopicReq struct {
	CityCode   string   `json:"cityCode,optional"`
	Kind       string   `json:"kind"`
	Title      string   `json:"title"`
	Subtitle   string   `json:"subtitle,optional"`
	CoverUrl   string   `json:"coverUrl,optional"`
	TypeScope  []string `json:"typeScope,optional"`
	JumpType   string   `json:"jumpType"`
	JumpTarget string   `json:"jumpTarget"`
	Tags       []string `json:"tags,optional"`
	StartAt    string   `json:"startAt,optional"`
	EndAt      string   `json:"endAt,optional"`
	SortOrder  int64    `json:"sortOrder,optional"`
	Status     string   `json:"status,optional"`
}

type AdminSaveBannerTopicResp struct {
	Id        string `json:"id"`
	UpdatedAt string `json:"updatedAt"`
}

type AdminSaveHotSearchKeywordReq struct {
	CityCode  string `json:"cityCode,optional"`
	Keyword   string `json:"keyword"`
	SortOrder int64  `json:"sortOrder,optional"`
	Status    string `json:"status,optional"`
	StartAt   string `json:"startAt,optional"`
	EndAt     string `json:"endAt,optional"`
}

type AdminSaveHotSearchKeywordResp struct {
	Id        string `json:"id"`
	UpdatedAt string `json:"updatedAt"`
}

type AdminSaveMapCategoryReq struct {
	Code      string `json:"code"`
	Name      string `json:"name"`
	Type      string `json:"type"`
	IconUrl   string `json:"iconUrl,optional"`
	Sort      int64  `json:"sort,optional"`
	IsVisible bool   `json:"isVisible,optional"`
	Status    string `json:"status,optional"`
}

type AdminSaveMapCategoryResp struct {
	Item MapCategoryItem `json:"item"`
}

type AdminSaveMapObjectReq struct {
	Id             string                 `json:"id,optional"`
	MerchantId     string                 `json:"merchantId,optional"`
	Code           string                 `json:"code"`
	Name           string                 `json:"name"`
	Type           string                 `json:"type"`
	Layer          string                 `json:"layer"`
	GeometryType   string                 `json:"geometryType"`
	Geometry       map[string]interface{} `json:"geometry"`
	MinZoom        int64                  `json:"minZoom,optional"`
	MaxZoom        int64                  `json:"maxZoom,optional"`
	CategoryCodes  []string               `json:"categoryCodes,optional"`
	ServiceTags    []string               `json:"serviceTags,optional"`
	PlatformTags   []string               `json:"platformTags,optional"`
	PoiServiceTags []string               `json:"poiServiceTags,optional"`
	Address        string                 `json:"address,optional"`
	Phone          string                 `json:"phone,optional"`
	Wechat         string                 `json:"wechat,optional"`
	Lat            string                 `json:"lat,optional"`
	Lng            string                 `json:"lng,optional"`
	Extra          map[string]interface{} `json:"extra,optional"`
	Sort           int64                  `json:"sort,optional"`
	Status         string                 `json:"status,optional"`
}

type AdminSaveMapObjectResp struct {
	Item MapObjectItem `json:"item"`
}

type AdminSaveMapSceneReq struct {
	CityCode       string `json:"cityCode,optional"`
	Code           string `json:"code"`
	Name           string `json:"name"`
	Type           string `json:"type"`
	ParentCode     string `json:"parentCode,optional"`
	BackgroundUrl  string `json:"backgroundUrl"`
	Width          int64  `json:"width"`
	Height         int64  `json:"height"`
	MinScale       string `json:"minScale,optional"`
	MaxScale       string `json:"maxScale,optional"`
	DefaultScale   string `json:"defaultScale,optional"`
	DefaultCenterX string `json:"defaultCenterX,optional"`
	DefaultCenterY string `json:"defaultCenterY,optional"`
	FloorNo        string `json:"floorNo,optional"`
	Sort           int64  `json:"sort,optional"`
	Status         string `json:"status,optional"`
}

type AdminSaveMapSceneResp struct {
	Item MapSceneItem `json:"item"`
}

type AdminSearchLogItem struct {
	Id          string                 `json:"id"`
	UserId      string                 `json:"userId,optional"`
	CityCode    string                 `json:"cityCode,optional"`
	CityName    string                 `json:"cityName,optional"`
	Keyword     string                 `json:"keyword"`
	Filters     map[string]interface{} `json:"filters"`
	ResultCount int64                  `json:"resultCount"`
	CreatedAt   string                 `json:"createdAt"`
}

type AdminSearchLogsReq struct {
	CityCode string `form:"cityCode,optional"`
	Keyword  string `form:"keyword,optional"`
	Page     int64  `form:"page,optional"`
	PageSize int64  `form:"pageSize,optional"`
}

type AdminSearchLogsResp struct {
	Items    []AdminSearchLogItem `json:"items"`
	Page     int64                `json:"page"`
	PageSize int64                `json:"pageSize"`
	Total    int64                `json:"total"`
}

type AdminUpdateDemandStatusReq struct {
	Status string `json:"status"`
}

type AdminUpdateDemandStatusResp struct {
	Id     string `json:"id"`
	Status string `json:"status"`
}

type AdminUpdateMapObjectStatusReq struct {
	Status string `json:"status"`
}

type AdminUpdateMapObjectStatusResp struct {
	Item MapObjectItem `json:"item"`
}

type AdminUpdateMatchCaseStatusReq struct {
	Status     string `json:"status"`
	ResultNote string `json:"resultNote,optional"`
}

type AdminUpdateResourceTypeConfigReq struct {
	FieldSchema      map[string]interface{} `json:"fieldSchema,optional"`
	RequiredFields   []string               `json:"requiredFields,optional"`
	FilterFields     []string               `json:"filterFields,optional"`
	DisplayTemplate  map[string]interface{} `json:"displayTemplate,optional"`
	ReviewRules      map[string]interface{} `json:"reviewRules,optional"`
	SortWeights      map[string]interface{} `json:"sortWeights,optional"`
	MessageRules     map[string]interface{} `json:"messageRules,optional"`
	DefaultValidDays int64                  `json:"defaultValidDays,optional"`
	Status           string                 `json:"status,optional"`
}

type AdminUpdateResourceTypeConfigResp struct {
	Id        string `json:"id"`
	UpdatedAt string `json:"updatedAt"`
}

type AdminVerificationBillingConfigReq struct {
	CityCode      string `json:"cityCode,optional"`
	ChargeEnabled bool   `json:"chargeEnabled"`
	FeeAmount     int64  `json:"feeAmount"`
	Currency      string `json:"currency,optional"`
	FreeEnabled   bool   `json:"freeEnabled,optional"`
	FreeStartAt   string `json:"freeStartAt,optional"`
	FreeEndAt     string `json:"freeEndAt,optional"`
	Notice        string `json:"notice,optional"`
}

type AdminVerificationBillingConfigResp struct {
	CityCode      string `json:"cityCode"`
	ChargeEnabled bool   `json:"chargeEnabled"`
	FeeAmount     int64  `json:"feeAmount"`
	Currency      string `json:"currency"`
	FreeEnabled   bool   `json:"freeEnabled"`
	FreeStartAt   string `json:"freeStartAt,optional"`
	FreeEndAt     string `json:"freeEndAt,optional"`
	Notice        string `json:"notice,optional"`
	UpdatedAt     string `json:"updatedAt,optional"`
}

type AuthUserInfo struct {
	Id              string   `json:"id"`
	Nickname        string   `json:"nickname,optional"`
	AvatarUrl       string   `json:"avatarUrl,optional"`
	DefaultCityCode string   `json:"defaultCityCode,optional"`
	Roles           []string `json:"roles"`
}

type BindPhoneReq struct {
	Phone   string `json:"phone"`
	SmsCode string `json:"smsCode"`
}

type BindPhoneResp struct {
	Id    string `json:"id"`
	Phone string `json:"phone"`
}

type CityStationInfo struct {
	Id              string `json:"id"`
	Code            string `json:"code"`
	Name            string `json:"name"`
	PrimaryCategory string `json:"primaryCategory,optional"`
	Status          string `json:"status"`
}

type ContactEventReq struct {
	Action string `json:"action"`
}

type ContactEventResp struct {
	Message string `json:"message"`
	Action  string `json:"action,optional"`
	Phone   string `json:"phone,optional"`
	Wechat  string `json:"wechat,optional"`
}

type CreateMerchantReq struct {
	CityCode       string   `json:"cityCode"`
	Name           string   `json:"name"`
	MerchantType   string   `json:"merchantType"`
	MainCategories []string `json:"mainCategories"`
	ContactName    string   `json:"contactName,optional"`
	ContactPhone   string   `json:"contactPhone,optional"`
	ContactWechat  string   `json:"contactWechat,optional"`
	AddressText    string   `json:"addressText,optional"`
	Description    string   `json:"description,optional"`
}

type CreateMerchantResp struct {
	Id                 string `json:"id"`
	Name               string `json:"name"`
	VerificationStatus string `json:"verificationStatus"`
	Status             string `json:"status"`
}

type CreatePurchaseDemandReq struct {
	CityCode            string                 `json:"cityCode,optional"`
	DemandType          string                 `json:"demandType"`
	Title               string                 `json:"title"`
	Category            string                 `json:"category"`
	PriceRange          PriceRangeReq          `json:"priceRange,optional"`
	QuantityRequirement QuantityRequirementReq `json:"quantityRequirement,optional"`
	Attributes          map[string]interface{} `json:"attributes,optional"`
	Contact             DemandContactReq       `json:"contact"`
}

type CreatePurchaseDemandResp struct {
	Id      string `json:"id"`
	Status  string `json:"status"`
	Message string `json:"message"`
}

type CreateResourceReq struct {
	MerchantId   string                 `json:"merchantId"`
	CityCode     string                 `json:"cityCode"`
	TypeCode     string                 `json:"typeCode"`
	Title        string                 `json:"title"`
	Category     string                 `json:"category"`
	District     string                 `json:"district,optional"`
	PriceText    string                 `json:"priceText,optional"`
	QuantityText string                 `json:"quantityText,optional"`
	Description  string                 `json:"description"`
	Attributes   map[string]interface{} `json:"attributes,optional"`
	Tags         []string               `json:"tags,optional"`
	Images       []string               `json:"images,optional"`
	Contact      ResourceContactReq     `json:"contact"`
}

type CreateResourceResp struct {
	Id      string `json:"id"`
	Status  string `json:"status"`
	Message string `json:"message"`
}

type CreateSavedSearchReq struct {
	Name         string `json:"name,optional"`
	CityCode     string `json:"cityCode,optional"`
	TypeCode     string `json:"typeCode,optional"`
	Keyword      string `json:"keyword,optional"`
	Category     string `json:"category,optional"`
	VerifiedOnly bool   `json:"verifiedOnly,optional"`
}

type CreateUploadTokenReq struct {
	Purpose     string `json:"purpose"`
	FileName    string `json:"fileName"`
	ContentType string `json:"contentType"`
	FileSize    int64  `json:"fileSize"`
}

type CreateUploadTokenResp struct {
	UploadToken   string `json:"uploadToken"`
	UploadUrl     string `json:"uploadUrl"`
	PublicBaseUrl string `json:"publicBaseUrl"`
	ObjectKey     string `json:"objectKey"`
	ExpiresAt     string `json:"expiresAt"`
}

type CreateVerificationPaymentReq struct {
	UserId string `json:"userId,optional"`
}

type CreateVerificationPaymentResp struct {
	OrderId string          `json:"orderId"`
	Status  string          `json:"status"`
	Payment WechatPayParams `json:"payment"`
}

type CreditTagInfo struct {
	Code  string `json:"code"`
	Label string `json:"label"`
}

type DealFeedbackReq struct {
	IsDealt                 bool   `json:"isDealt"`
	IsReal                  bool   `json:"isReal,optional"`
	ResponseTimely          bool   `json:"responseTimely,optional"`
	WillingToCooperateAgain bool   `json:"willingToCooperateAgain,optional"`
	Note                    string `json:"note,optional"`
}

type DealFeedbackResp struct {
	Id      string `json:"id"`
	Status  string `json:"status"`
	Message string `json:"message"`
}

type DeleteSavedSearchResp struct {
	Message string `json:"message"`
}

type DeleteTakenDownResourceReq struct {
	MerchantId string `json:"merchantId,optional"`
}

type DeleteTakenDownResourceResp struct {
	Id      string `json:"id"`
	Status  string `json:"status"`
	Message string `json:"message"`
}

type DemandContactReq struct {
	Name   string `json:"name"`
	Phone  string `json:"phone"`
	Wechat string `json:"wechat,optional"`
}

type DetailViewResp struct {
	Message string `json:"message"`
}

type EditableResourceContact struct {
	Name   string `json:"name"`
	Phone  string `json:"phone"`
	Wechat string `json:"wechat,optional"`
}

type EditableResourceResp struct {
	Id           string                  `json:"id"`
	MerchantId   string                  `json:"merchantId"`
	CityCode     string                  `json:"cityCode"`
	TypeCode     string                  `json:"typeCode"`
	Status       string                  `json:"status"`
	Title        string                  `json:"title"`
	Category     string                  `json:"category"`
	District     string                  `json:"district,optional"`
	PriceText    string                  `json:"priceText,optional"`
	QuantityText string                  `json:"quantityText,optional"`
	Description  string                  `json:"description"`
	Attributes   map[string]interface{}  `json:"attributes"`
	Tags         []string                `json:"tags"`
	Images       []string                `json:"images"`
	Contact      EditableResourceContact `json:"contact"`
	RejectReason string                  `json:"rejectReason,optional"`
}

type FollowedMerchantItem struct {
	Id                 string   `json:"id"`
	Name               string   `json:"name"`
	MerchantType       string   `json:"merchantType"`
	VerificationStatus string   `json:"verificationStatus"`
	MainCategories     []string `json:"mainCategories"`
	LogoUrl            string   `json:"logoUrl,optional"`
	FollowedAt         string   `json:"followedAt"`
}

type HomeBannerItem struct {
	Id         string   `json:"id"`
	Title      string   `json:"title"`
	Subtitle   string   `json:"subtitle,optional"`
	CoverUrl   string   `json:"coverUrl,optional"`
	JumpType   string   `json:"jumpType"`
	JumpTarget string   `json:"jumpTarget"`
	Tags       []string `json:"tags"`
}

type HomeBannersReq struct {
	CityCode string `form:"cityCode,optional"`
}

type HomeBannersResp struct {
	Items []HomeBannerItem `json:"items"`
}

type HomeRecommendCardItem struct {
	Id         string `json:"id"`
	Tag        string `json:"tag,optional"`
	Title      string `json:"title"`
	Subtitle   string `json:"subtitle,optional"`
	JumpType   string `json:"jumpType"`
	JumpTarget string `json:"jumpTarget"`
}

type HomeRecommendCardsReq struct {
	CityCode string `form:"cityCode,optional"`
}

type HomeRecommendCardsResp struct {
	Items []HomeRecommendCardItem `json:"items"`
}

type HotSearchKeywordItem struct {
	Keyword string `json:"keyword"`
}

type HotSearchKeywordsReq struct {
	CityCode string `form:"cityCode,optional"`
}

type HotSearchKeywordsResp struct {
	Items []HotSearchKeywordItem `json:"items"`
}

type LatestVerificationResp struct {
	Id               string                 `json:"id"`
	VerificationType string                 `json:"verificationType"`
	Status           string                 `json:"status"`
	ReviewedAt       string                 `json:"reviewedAt,optional"`
	ExpiresAt        string                 `json:"expiresAt,optional"`
	ReviewNote       string                 `json:"reviewNote,optional"`
	BusinessName     string                 `json:"businessName,optional"`
	LicenseUrl       string                 `json:"licenseUrl,optional"`
	StorefrontUrl    string                 `json:"storefrontUrl,optional"`
	Materials        map[string]interface{} `json:"materials,optional"`
}

type ListCityStationsResp struct {
	Items []CityStationInfo `json:"items"`
}

type ListFollowedMerchantsResp struct {
	Items    []FollowedMerchantItem `json:"items"`
	Page     int64                  `json:"page"`
	PageSize int64                  `json:"pageSize"`
	Total    int64                  `json:"total"`
}

type ListInteractionReq struct {
	Page     int64 `form:"page,optional"`
	PageSize int64 `form:"pageSize,optional"`
}

type ListMapCategoriesReq struct {
	Type string `form:"type,optional"`
}

type ListMapCategoriesResp struct {
	Items []MapCategoryItem `json:"items"`
}

type ListMapObjectsReq struct {
	Types          string `form:"types,optional"`
	Categories     string `form:"categories,optional"`
	ServiceTags    string `form:"serviceTags,optional"`
	PoiServiceTags string `form:"poiServiceTags,optional"`
	Keyword        string `form:"keyword,optional"`
	MinX           string `form:"minX,optional"`
	MinY           string `form:"minY,optional"`
	MaxX           string `form:"maxX,optional"`
	MaxY           string `form:"maxY,optional"`
	Zoom           int64  `form:"zoom,optional"`
}

type ListMapObjectsResp struct {
	SceneCode string          `json:"sceneCode"`
	Items     []MapObjectItem `json:"items"`
	Total     int64           `json:"total"`
}

type ListMapScenesReq struct {
	CityCode   string `form:"cityCode,optional"`
	ParentCode string `form:"parentCode,optional"`
	Type       string `form:"type,optional"`
}

type ListMapScenesResp struct {
	Items []MapSceneItem `json:"items"`
}

type ListMerchantEntitlementsResp struct {
	Items []MerchantEntitlementInfo `json:"items"`
}

type ListMessagesReq struct {
	UserId   string `form:"userId,optional"`
	RoleCode string `form:"roleCode,optional"`
	Type     string `form:"type,optional"`
	Status   string `form:"status,optional"`
	Page     int64  `form:"page,optional"`
	PageSize int64  `form:"pageSize,optional"`
}

type ListMessagesResp struct {
	Items    []MessageListItem `json:"items"`
	Page     int64             `json:"page"`
	PageSize int64             `json:"pageSize"`
	Total    int64             `json:"total"`
}

type ListMyPurchaseDemandsReq struct {
	Status   string `form:"status,optional"`
	Page     int64  `form:"page,optional"`
	PageSize int64  `form:"pageSize,optional"`
}

type ListMyPurchaseDemandsResp struct {
	Items    []PurchaseDemandListItem `json:"items"`
	Page     int64                    `json:"page"`
	PageSize int64                    `json:"pageSize"`
	Total    int64                    `json:"total"`
}

type ListMyResourcesReq struct {
	MerchantId string `form:"merchantId"`
	Status     string `form:"status,optional"`
	Page       int64  `form:"page,optional"`
	PageSize   int64  `form:"pageSize,optional"`
}

type ListMyResourcesResp struct {
	Items    []MyResourceItem `json:"items"`
	Page     int64            `json:"page"`
	PageSize int64            `json:"pageSize"`
	Total    int64            `json:"total"`
}

type ListNearbyPoisReq struct {
	Types string `form:"types,optional"`
	Limit int64  `form:"limit,optional"`
}

type ListNearbyPoisResp struct {
	Items []NearbyPoiItem `json:"items"`
}

type ListResourceTypesResp struct {
	Items []ResourceTypeConfigInfo `json:"items"`
}

type ListResourcesReq struct {
	CityCode     string `form:"cityCode,optional"`
	MerchantId   string `form:"merchantId,optional"`
	TypeCode     string `form:"typeCode,optional"`
	Keyword      string `form:"keyword,optional"`
	Category     string `form:"category,optional"`
	VerifiedOnly bool   `form:"verifiedOnly,optional"`
	Page         int64  `form:"page,optional"`
	PageSize     int64  `form:"pageSize,optional"`
}

type ListResourcesResp struct {
	Items    []ResourceListItem `json:"items"`
	Page     int64              `json:"page"`
	PageSize int64              `json:"pageSize"`
	Total    int64              `json:"total"`
}

type ListSavedSearchesResp struct {
	Items    []SavedSearchItem `json:"items"`
	Page     int64             `json:"page"`
	PageSize int64             `json:"pageSize"`
	Total    int64             `json:"total"`
}

type ListTopVouchersResp struct {
	Items []TopVoucherInfo `json:"items"`
}

type ManagedMerchantInfo struct {
	Id   string `json:"id"`
	Name string `json:"name"`
	Role string `json:"role"`
}

type MapCategoryItem struct {
	Code      string `json:"code"`
	Name      string `json:"name"`
	Type      string `json:"type"`
	IconUrl   string `json:"iconUrl,optional"`
	Sort      int64  `json:"sort"`
	IsVisible bool   `json:"isVisible"`
	Status    string `json:"status"`
}

type MapGeometry struct {
	Type string                 `json:"type"`
	Data map[string]interface{} `json:"data"`
}

type MapObjectDetailResp struct {
	Item MapObjectItem `json:"item"`
}

type MapObjectItem struct {
	Id                 string                 `json:"id"`
	SceneCode          string                 `json:"sceneCode"`
	MerchantId         string                 `json:"merchantId,optional"`
	Code               string                 `json:"code"`
	Name               string                 `json:"name"`
	Type               string                 `json:"type"`
	Layer              string                 `json:"layer"`
	DisplaySource      string                 `json:"displaySource"`
	DisplayLevel       string                 `json:"displayLevel"`
	IsVerifiedMerchant bool                   `json:"isVerifiedMerchant"`
	Merchant           *MapObjectMerchantItem `json:"merchant,optional"`
	GeometryType       string                 `json:"geometryType"`
	Geometry           map[string]interface{} `json:"geometry"`
	CenterX            string                 `json:"centerX,optional"`
	CenterY            string                 `json:"centerY,optional"`
	MinZoom            int64                  `json:"minZoom,optional"`
	MaxZoom            int64                  `json:"maxZoom,optional"`
	CategoryCodes      []string               `json:"categoryCodes"`
	ServiceTags        []string               `json:"serviceTags"`
	PlatformTags       []string               `json:"platformTags"`
	PoiServiceTags     []string               `json:"poiServiceTags"`
	Address            string                 `json:"address,optional"`
	Phone              string                 `json:"phone,optional"`
	Wechat             string                 `json:"wechat,optional"`
	Lat                string                 `json:"lat,optional"`
	Lng                string                 `json:"lng,optional"`
	Extra              map[string]interface{} `json:"extra"`
	Status             string                 `json:"status"`
}

type MapObjectMerchantItem struct {
	Id                 string   `json:"id"`
	Name               string   `json:"name"`
	MerchantType       string   `json:"merchantType"`
	VerificationStatus string   `json:"verificationStatus"`
	LogoUrl            string   `json:"logoUrl,optional"`
	MainCategories     []string `json:"mainCategories"`
}

type MapSceneItem struct {
	Code           string `json:"code"`
	Name           string `json:"name"`
	Type           string `json:"type"`
	ParentCode     string `json:"parentCode,optional"`
	BackgroundUrl  string `json:"backgroundUrl,optional"`
	Width          int64  `json:"width,optional"`
	Height         int64  `json:"height,optional"`
	DefaultScale   string `json:"defaultScale,optional"`
	DefaultCenterX string `json:"defaultCenterX,optional"`
	DefaultCenterY string `json:"defaultCenterY,optional"`
	FloorNo        string `json:"floorNo,optional"`
	Sort           int64  `json:"sort"`
	Status         string `json:"status"`
}

type MapSceneResp struct {
	Item MapSceneItem `json:"item"`
}

type MeResp struct {
	Id               string                `json:"id"`
	Phone            string                `json:"phone,optional"`
	Nickname         string                `json:"nickname,optional"`
	DefaultCityCode  string                `json:"defaultCityCode,optional"`
	Roles            []string              `json:"roles"`
	ManagedMerchants []ManagedMerchantInfo `json:"managedMerchants"`
}

type MerchantContactInfo struct {
	Name         string `json:"name"`
	PhoneMasked  string `json:"phoneMasked"`
	WechatMasked string `json:"wechatMasked,optional"`
}

type MerchantDetailResp struct {
	Id                 string                   `json:"id"`
	Name               string                   `json:"name"`
	MerchantType       string                   `json:"merchantType"`
	CityCode           string                   `json:"cityCode"`
	MainCategories     []string                 `json:"mainCategories"`
	VerificationStatus string                   `json:"verificationStatus"`
	VerificationInfo   MerchantVerificationInfo `json:"verificationInfo,optional"`
	CreditTags         []CreditTagInfo          `json:"creditTags"`
	Contact            MerchantContactInfo      `json:"contact"`
	ResourcesSummary   MerchantResourcesSummary `json:"resourcesSummary"`
	HeatScore          int64                    `json:"heatScore"`
	AddressText        string                   `json:"addressText,optional"`
	Location           map[string]interface{}   `json:"location,optional"`
	Description        string                   `json:"description,optional"`
	LogoUrl            string                   `json:"logoUrl,optional"`
	Images             []string                 `json:"images,optional"`
	LastActiveAt       string                   `json:"lastActiveAt,optional"`
}

type MerchantEntitlementInfo struct {
	Type            string `json:"type"`
	SourceType      string `json:"sourceType"`
	TotalAmount     int64  `json:"totalAmount"`
	UsedAmount      int64  `json:"usedAmount"`
	RemainingAmount int64  `json:"remainingAmount"`
	ExpiresAt       string `json:"expiresAt,optional"`
}

type MerchantFollowStateResp struct {
	MerchantId string `json:"merchantId"`
	Followed   bool   `json:"followed"`
}

type MerchantLast7DaysMetrics struct {
	ExposureCount     int64 `json:"exposureCount"`
	DetailViewCount   int64 `json:"detailViewCount"`
	ContactClickCount int64 `json:"contactClickCount"`
}

type MerchantMetricsSummaryResp struct {
	MerchantId             string                   `json:"merchantId"`
	PublishedResourceCount int64                    `json:"publishedResourceCount"`
	ExpiringResourceCount  int64                    `json:"expiringResourceCount"`
	DealtResourceCount     int64                    `json:"dealtResourceCount"`
	Last7Days              MerchantLast7DaysMetrics `json:"last7Days"`
}

type MerchantResourcesSummary struct {
	PublishedCount int64 `json:"publishedCount"`
	DealtCount     int64 `json:"dealtCount"`
}

type MerchantVerificationInfo struct {
	Status       string   `json:"status"`
	Type         string   `json:"type"`
	ReviewedAt   string   `json:"reviewedAt,optional"`
	ExpiresAt    string   `json:"expiresAt,optional"`
	CheckedItems []string `json:"checkedItems"`
}

type MessageListItem struct {
	Id          string `json:"id"`
	MessageType string `json:"messageType"`
	TriggerId   string `json:"triggerId,optional"`
	Title       string `json:"title"`
	Content     string `json:"content"`
	TargetUrl   string `json:"targetUrl,optional"`
	Status      string `json:"status"`
	CreatedAt   string `json:"createdAt"`
}

type MyResourceItem struct {
	Id           string            `json:"id"`
	TypeCode     string            `json:"typeCode"`
	Title        string            `json:"title"`
	Category     string            `json:"category"`
	CoverUrl     string            `json:"coverUrl,optional"`
	Status       string            `json:"status"`
	RejectReason string            `json:"rejectReason,optional"`
	PublishedAt  string            `json:"publishedAt,optional"`
	ExpiresAt    string            `json:"expiresAt,optional"`
	DealtAt      string            `json:"dealtAt,optional"`
	Metrics      MyResourceMetrics `json:"metrics"`
}

type MyResourceMetrics struct {
	ExposureCount   int64 `json:"exposureCount"`
	DetailViewCount int64 `json:"detailViewCount"`
	PhoneClickCount int64 `json:"phoneClickCount"`
	WechatCopyCount int64 `json:"wechatCopyCount"`
}

type NearbyPoiItem struct {
	Id           string `json:"id"`
	Name         string `json:"name"`
	Type         string `json:"type"`
	DistanceText string `json:"distanceText"`
	CenterX      string `json:"centerX,optional"`
	CenterY      string `json:"centerY,optional"`
}

type PriceRangeReq struct {
	Min float64 `json:"min,optional"`
	Max float64 `json:"max,optional"`
}

type PurchaseDemandListItem struct {
	Id          string `json:"id"`
	Title       string `json:"title"`
	DemandType  string `json:"demandType"`
	Category    string `json:"category"`
	ContactName string `json:"contactName"`
	Status      string `json:"status"`
	CreatedAt   string `json:"createdAt"`
}

type QuantityRequirementReq struct {
	Quantity int64  `json:"quantity,optional"`
	Unit     string `json:"unit,optional"`
}

type ReadMessageReq struct {
	UserId   string `json:"userId,optional"`
	RoleCode string `json:"roleCode,optional"`
}

type ReadMessageResp struct {
	Id     string `json:"id"`
	Status string `json:"status"`
}

type RedeemTopVoucherReq struct {
	MerchantId string `json:"merchantId,optional"`
	ResourceId string `json:"resourceId"`
}

type RedeemTopVoucherResp struct {
	VoucherId  string `json:"voucherId"`
	ResourceId string `json:"resourceId"`
	Status     string `json:"status"`
	Message    string `json:"message"`
}

type RefreshResourceResp struct {
	Id                    string `json:"id"`
	RefreshedAt           string `json:"refreshedAt"`
	RemainingRefreshQuota int64  `json:"remainingRefreshQuota"`
}

type RepostSimilarResp struct {
	Id      string `json:"id"`
	Status  string `json:"status"`
	Message string `json:"message"`
}

type ResourceContactMasked struct {
	Name         string `json:"name"`
	PhoneMasked  string `json:"phoneMasked"`
	WechatMasked string `json:"wechatMasked,optional"`
}

type ResourceContactReq struct {
	Name   string `json:"name"`
	Phone  string `json:"phone"`
	Wechat string `json:"wechat,optional"`
}

type ResourceDetailResp struct {
	Id           string                 `json:"id"`
	Status       string                 `json:"status"`
	TypeCode     string                 `json:"typeCode"`
	Title        string                 `json:"title"`
	Category     string                 `json:"category"`
	Description  string                 `json:"description"`
	PriceText    string                 `json:"priceText,optional"`
	QuantityText string                 `json:"quantityText,optional"`
	Attributes   map[string]interface{} `json:"attributes"`
	Tags         []string               `json:"tags"`
	Images       []string               `json:"images"`
	Merchant     ResourceMerchantBrief  `json:"merchant"`
	Contact      ResourceContactMasked  `json:"contact"`
	PublishedAt  string                 `json:"publishedAt,optional"`
	ExpiresAt    string                 `json:"expiresAt,optional"`
}

type ResourceFavoriteStateResp struct {
	ResourceId string `json:"resourceId"`
	Favorited  bool   `json:"favorited"`
}

type ResourceListItem struct {
	Id           string                `json:"id"`
	TypeCode     string                `json:"typeCode"`
	Title        string                `json:"title"`
	Category     string                `json:"category"`
	District     string                `json:"district,optional"`
	PriceText    string                `json:"priceText,optional"`
	QuantityText string                `json:"quantityText,optional"`
	Merchant     ResourceMerchantBrief `json:"merchant"`
	CreditTags   []string              `json:"creditTags"`
	RefreshedAt  string                `json:"refreshedAt,optional"`
}

type ResourceMerchantBrief struct {
	Id                 string `json:"id"`
	Name               string `json:"name"`
	VerificationStatus string `json:"verificationStatus"`
}

type ResourceMetricsDailyItem struct {
	Date            string `json:"date"`
	ExposureCount   int64  `json:"exposureCount"`
	DetailViewCount int64  `json:"detailViewCount"`
	PhoneClickCount int64  `json:"phoneClickCount"`
	WechatCopyCount int64  `json:"wechatCopyCount"`
}

type ResourceMetricsReq struct {
	From string `form:"from,optional"`
	To   string `form:"to,optional"`
}

type ResourceMetricsResp struct {
	ResourceId string                     `json:"resourceId"`
	Summary    ResourceMetricsSummary     `json:"summary"`
	Daily      []ResourceMetricsDailyItem `json:"daily"`
}

type ResourceMetricsSummary struct {
	ExposureCount     int64 `json:"exposureCount"`
	DetailViewCount   int64 `json:"detailViewCount"`
	PhoneClickCount   int64 `json:"phoneClickCount"`
	WechatCopyCount   int64 `json:"wechatCopyCount"`
	DealFeedbackCount int64 `json:"dealFeedbackCount"`
}

type ResourceTypeConfigInfo struct {
	Id               string                 `json:"id"`
	TypeCode         string                 `json:"typeCode"`
	TypeName         string                 `json:"typeName"`
	DefaultValidDays int64                  `json:"defaultValidDays"`
	RequiredFields   []string               `json:"requiredFields"`
	FilterFields     []string               `json:"filterFields"`
	DisplayTemplate  map[string]interface{} `json:"displayTemplate"`
}

type SavedSearchItem struct {
	Id           string `json:"id"`
	Name         string `json:"name"`
	CityCode     string `json:"cityCode"`
	TypeCode     string `json:"typeCode"`
	Keyword      string `json:"keyword"`
	Category     string `json:"category"`
	VerifiedOnly bool   `json:"verifiedOnly"`
	CreatedAt    string `json:"createdAt"`
}

type SavedSearchResp struct {
	Id string `json:"id"`
}

type SearchMapObjectsReq struct {
	SceneCode      string `form:"sceneCode,optional"`
	Keyword        string `form:"keyword,optional"`
	Types          string `form:"types,optional"`
	Categories     string `form:"categories,optional"`
	ServiceTags    string `form:"serviceTags,optional"`
	PoiServiceTags string `form:"poiServiceTags,optional"`
	MinX           string `form:"minX,optional"`
	MinY           string `form:"minY,optional"`
	MaxX           string `form:"maxX,optional"`
	MaxY           string `form:"maxY,optional"`
	Zoom           int64  `form:"zoom,optional"`
	Limit          int64  `form:"limit,optional"`
}

type SearchMapObjectsResp struct {
	Items []MapObjectItem `json:"items"`
	Total int64           `json:"total"`
}

type SearchResourcesReq struct {
	CityCode     string `form:"cityCode,optional"`
	TypeCode     string `form:"typeCode,optional"`
	Keyword      string `form:"keyword,optional"`
	Category     string `form:"category,optional"`
	VerifiedOnly bool   `form:"verifiedOnly,optional"`
	Page         int64  `form:"page,optional"`
	PageSize     int64  `form:"pageSize,optional"`
}

type SendSMSCodeReq struct {
	Phone string `json:"phone"`
}

type SendSMSCodeResp struct {
	Message string `json:"message"`
}

type SetMerchantFollowReq struct {
	Followed bool `json:"followed"`
}

type SetResourceFavoriteReq struct {
	Favorited bool `json:"favorited"`
}

type SubmitResourceReq struct {
	MerchantId string `json:"merchantId,optional"`
}

type SubmitResourceResp struct {
	Id      string `json:"id"`
	Status  string `json:"status"`
	Message string `json:"message"`
}

type SubmitVerificationReq struct {
	VerificationType string                 `json:"verificationType"`
	BusinessName     string                 `json:"businessName,optional"`
	LicenseUrl       string                 `json:"licenseUrl,optional"`
	StorefrontUrl    string                 `json:"storefrontUrl,optional"`
	Materials        map[string]interface{} `json:"materials,optional"`
}

type SubmitVerificationResp struct {
	Id      string `json:"id"`
	Status  string `json:"status"`
	Message string `json:"message"`
}

type TakeDownOwnResourceReq struct {
	Reason string `json:"reason"`
}

type TakeDownOwnResourceResp struct {
	Id      string `json:"id"`
	Status  string `json:"status"`
	Message string `json:"message"`
}

type TopVoucherInfo struct {
	Id               string   `json:"id"`
	Status           string   `json:"status"`
	TopDurationHours int64    `json:"topDurationHours"`
	AllowedTypeCodes []string `json:"allowedTypeCodes"`
	ExpiresAt        string   `json:"expiresAt,optional"`
}

type TopicDemandEntry struct {
	Title      string `json:"title"`
	ButtonText string `json:"buttonText"`
}

type TopicInfoResp struct {
	Id       string   `json:"id"`
	Title    string   `json:"title"`
	Subtitle string   `json:"subtitle,optional"`
	CoverUrl string   `json:"coverUrl,optional"`
	Tags     []string `json:"tags"`
}

type TopicResourceItem struct {
	Id           string `json:"id"`
	TypeCode     string `json:"typeCode"`
	Title        string `json:"title"`
	Category     string `json:"category"`
	District     string `json:"district,optional"`
	PriceText    string `json:"priceText,optional"`
	QuantityText string `json:"quantityText,optional"`
	MerchantName string `json:"merchantName"`
}

type TopicResourcesReq struct {
	CityCode string `form:"cityCode,optional"`
	Page     int64  `form:"page,optional"`
	PageSize int64  `form:"pageSize,optional"`
}

type TopicResourcesResp struct {
	Topic       TopicInfoResp       `json:"topic"`
	Items       []TopicResourceItem `json:"items"`
	Page        int64               `json:"page"`
	PageSize    int64               `json:"pageSize"`
	Total       int64               `json:"total"`
	DemandEntry TopicDemandEntry    `json:"demandEntry,optional"`
}

type UpdateMerchantReq struct {
	MainCategories []string               `json:"mainCategories,optional"`
	MerchantType   string                 `json:"merchantType,optional"`
	Description    string                 `json:"description,optional"`
	LogoUrl        string                 `json:"logoUrl,optional"`
	Images         []string               `json:"images,optional"`
	ContactName    string                 `json:"contactName,optional"`
	ContactPhone   string                 `json:"contactPhone,optional"`
	ContactWechat  string                 `json:"contactWechat,optional"`
	AddressText    string                 `json:"addressText,optional"`
	Location       map[string]interface{} `json:"location,optional"`
	SmsCode        string                 `json:"smsCode,optional"`
}

type UpdateMerchantResp struct {
	Id        string `json:"id"`
	UpdatedAt string `json:"updatedAt"`
}

type ValidateWebviewReq struct {
	Url string `json:"url"`
}

type ValidateWebviewResp struct {
	Allowed bool   `json:"allowed"`
	Url     string `json:"url"`
}

type VerificationBillingConfigResp struct {
	CityCode      string `json:"cityCode"`
	ChargeEnabled bool   `json:"chargeEnabled"`
	FeeAmount     int64  `json:"feeAmount"`
	Currency      string `json:"currency"`
	FreeEnabled   bool   `json:"freeEnabled"`
	FreeStartAt   string `json:"freeStartAt,optional"`
	FreeEndAt     string `json:"freeEndAt,optional"`
	Notice        string `json:"notice,optional"`
	UpdatedAt     string `json:"updatedAt,optional"`
}

type WechatLoginReq struct {
	Code            string `json:"code"`
	DefaultCityCode string `json:"defaultCityCode,optional"`
}

type WechatLoginResp struct {
	Token            string                `json:"token"`
	User             AuthUserInfo          `json:"user"`
	ManagedMerchants []ManagedMerchantInfo `json:"managedMerchants"`
}

type WechatPayParams struct {
	TimeStamp string `json:"timeStamp"`
	NonceStr  string `json:"nonceStr"`
	Package   string `json:"package"`
	SignType  string `json:"signType"`
	PaySign   string `json:"paySign"`
}
