// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5

package types

type AdminAddMatchParticipantsReq struct {
	ParticipantMerchantIds []string `json:"participantMerchantIds"`
}

type AdminAddMatchResourcesReq struct {
	ResourceIds []string `json:"resourceIds"`
}

type AdminBannerTopicItem struct {
	Id         string   `json:"id"`
	CityCode   string   `json:"cityCode,optional"`
	Kind       string   `json:"kind"`
	Title      string   `json:"title"`
	Subtitle   string   `json:"subtitle,optional"`
	CoverUrl   string   `json:"coverUrl,optional"`
	TypeScope  []string `json:"typeScope"`
	JumpType   string   `json:"jumpType"`
	JumpTarget string   `json:"jumpTarget"`
	Tags       []string `json:"tags"`
	StartAt    string   `json:"startAt,optional"`
	EndAt      string   `json:"endAt,optional"`
	SortOrder  int64    `json:"sortOrder"`
	Status     string   `json:"status"`
	UpdatedAt  string   `json:"updatedAt"`
}

type AdminCreateMatchCaseReq struct {
	PurchaseDemandId       string   `json:"purchaseDemandId"`
	ResourceIds            []string `json:"resourceIds,optional"`
	ParticipantMerchantIds []string `json:"participantMerchantIds,optional"`
	ResultNote             string   `json:"resultNote,optional"`
}

type AdminCreateMatchCaseResp struct {
	Id      string `json:"id"`
	Status  string `json:"status"`
	Message string `json:"message"`
}

type AdminDashboardMetrics struct {
	PendingResourceCount     int64 `json:"pendingResourceCount"`
	PendingVerificationCount int64 `json:"pendingVerificationCount"`
	PendingDemandCount       int64 `json:"pendingDemandCount"`
	TodayContactCount        int64 `json:"todayContactCount"`
}

type AdminDashboardOverviewReq struct {
	CityCode string `form:"cityCode,optional"`
}

type AdminDashboardOverviewResp struct {
	Metrics AdminDashboardMetrics `json:"metrics"`
	Tasks   []AdminDashboardTask  `json:"tasks"`
}

type AdminDashboardTask struct {
	Type      string `json:"type"`
	Title     string `json:"title"`
	CityName  string `json:"cityName"`
	CreatedAt string `json:"createdAt"`
}

type AdminDemandContact struct {
	Name   string `json:"name"`
	Phone  string `json:"phone"`
	Wechat string `json:"wechat,optional"`
}

type AdminDemandDetailResp struct {
	Id                  string                 `json:"id"`
	Title               string                 `json:"title"`
	DemandType          string                 `json:"demandType"`
	Category            string                 `json:"category"`
	PriceRange          map[string]interface{} `json:"priceRange"`
	QuantityRequirement map[string]interface{} `json:"quantityRequirement"`
	Attributes          map[string]interface{} `json:"attributes"`
	Contact             AdminDemandContact     `json:"contact"`
	Status              string                 `json:"status"`
	CreatedAt           string                 `json:"createdAt"`
}

type AdminDemandListItem struct {
	Id          string `json:"id"`
	Title       string `json:"title"`
	DemandType  string `json:"demandType"`
	Category    string `json:"category"`
	ContactName string `json:"contactName"`
	Status      string `json:"status"`
	CreatedAt   string `json:"createdAt"`
}

type AdminGrantEntitlementReq struct {
	EntitlementType string `json:"entitlementType"`
	SourceType      string `json:"sourceType"`
	TotalAmount     int64  `json:"totalAmount"`
	ExpiresAt       string `json:"expiresAt,optional"`
	Reason          string `json:"reason"`
}

type AdminGrantEntitlementResp struct {
	Id      string `json:"id"`
	Message string `json:"message"`
}

type AdminListBannerTopicsReq struct {
	CityCode string `form:"cityCode,optional"`
	Kind     string `form:"kind,optional"`
	Status   string `form:"status,optional"`
}

type AdminListBannerTopicsResp struct {
	Items []AdminBannerTopicItem `json:"items"`
}

type AdminListDemandsReq struct {
	CityCode   string `form:"cityCode,optional"`
	DemandType string `form:"demandType,optional"`
	Status     string `form:"status,optional"`
	Page       int64  `form:"page,optional"`
	PageSize   int64  `form:"pageSize,optional"`
}

type AdminListDemandsResp struct {
	Items    []AdminDemandListItem `json:"items"`
	Page     int64                 `json:"page"`
	PageSize int64                 `json:"pageSize"`
	Total    int64                 `json:"total"`
}

type AdminListMatchCasesReq struct {
	Status   string `form:"status,optional"`
	Page     int64  `form:"page,optional"`
	PageSize int64  `form:"pageSize,optional"`
}

type AdminListMatchCasesResp struct {
	Items    []AdminMatchCaseItem `json:"items"`
	Page     int64                `json:"page"`
	PageSize int64                `json:"pageSize"`
	Total    int64                `json:"total"`
}

type AdminListMerchantsReq struct {
	CityCode     string `form:"cityCode,optional"`
	MerchantType string `form:"merchantType,optional"`
	Status       string `form:"status,optional"`
	Page         int64  `form:"page,optional"`
	PageSize     int64  `form:"pageSize,optional"`
}

type AdminListMerchantsResp struct {
	Items    []AdminMerchantListItem `json:"items"`
	Page     int64                   `json:"page"`
	PageSize int64                   `json:"pageSize"`
	Total    int64                   `json:"total"`
}

type AdminListResourceTypeConfigsReq struct {
	CityCode string `form:"cityCode,optional"`
	Status   string `form:"status,optional"`
}

type AdminListResourceTypeConfigsResp struct {
	Items []AdminResourceTypeConfigItem `json:"items"`
}

type AdminLoginReq struct {
	LoginName string `json:"loginName"`
	Password  string `json:"password"`
}

type AdminLoginResp struct {
	Token  string   `json:"token"`
	UserId string   `json:"userId"`
	Roles  []string `json:"roles"`
}

type AdminMatchCaseActionResp struct {
	Id      string `json:"id"`
	Status  string `json:"status,optional"`
	Message string `json:"message"`
}

type AdminMatchCaseItem struct {
	Id               string `json:"id"`
	PurchaseDemandId string `json:"purchaseDemandId"`
	DemandTitle      string `json:"demandTitle"`
	Status           string `json:"status"`
	Source           string `json:"source"`
	ResultNote       string `json:"resultNote,optional"`
	ResourceCount    int64  `json:"resourceCount"`
	ParticipantCount int64  `json:"participantCount"`
	CreatedAt        string `json:"createdAt"`
}

type AdminMerchantListItem struct {
	Id                 string `json:"id"`
	Name               string `json:"name"`
	MerchantType       string `json:"merchantType"`
	VerificationStatus string `json:"verificationStatus"`
	Status             string `json:"status"`
	LastActiveAt       string `json:"lastActiveAt,optional"`
}

type AdminOperationLogItem struct {
	Id           string `json:"id"`
	OperatorId   string `json:"operatorId"`
	OperatorRole string `json:"operatorRole"`
	ObjectType   string `json:"objectType"`
	ObjectId     string `json:"objectId,optional"`
	Action       string `json:"action"`
	Reason       string `json:"reason,optional"`
	CreatedAt    string `json:"createdAt"`
}

type AdminOperationLogsReq struct {
	ObjectType string `form:"objectType,optional"`
	ObjectId   string `form:"objectId,optional"`
	OperatorId string `form:"operatorId,optional"`
	Page       int64  `form:"page,optional"`
	PageSize   int64  `form:"pageSize,optional"`
}

type AdminOperationLogsResp struct {
	Items    []AdminOperationLogItem `json:"items"`
	Page     int64                   `json:"page"`
	PageSize int64                   `json:"pageSize"`
	Total    int64                   `json:"total"`
}

type AdminPendingResourceItem struct {
	Id           string `json:"id"`
	Title        string `json:"title"`
	TypeCode     string `json:"typeCode"`
	MerchantName string `json:"merchantName"`
	CreatedAt    string `json:"createdAt"`
}

type AdminPendingResourcesReq struct {
	CityCode string `form:"cityCode,optional"`
	TypeCode string `form:"typeCode,optional"`
	Page     int64  `form:"page,optional"`
	PageSize int64  `form:"pageSize,optional"`
}

type AdminPendingResourcesResp struct {
	Items    []AdminPendingResourceItem `json:"items"`
	Page     int64                      `json:"page"`
	PageSize int64                      `json:"pageSize"`
	Total    int64                      `json:"total"`
}

type AdminPendingVerificationItem struct {
	Id               string `json:"id"`
	MerchantId       string `json:"merchantId"`
	MerchantName     string `json:"merchantName"`
	VerificationType string `json:"verificationType"`
	Status           string `json:"status"`
	SubmittedAt      string `json:"submittedAt"`
}

type AdminPendingVerificationsReq struct {
	Page     int64 `form:"page,optional"`
	PageSize int64 `form:"pageSize,optional"`
}

type AdminPendingVerificationsResp struct {
	Items    []AdminPendingVerificationItem `json:"items"`
	Page     int64                          `json:"page"`
	PageSize int64                          `json:"pageSize"`
	Total    int64                          `json:"total"`
}

type AdminResourceTypeConfigItem struct {
	Id               string                 `json:"id"`
	CityCode         string                 `json:"cityCode,optional"`
	TypeCode         string                 `json:"typeCode"`
	TypeName         string                 `json:"typeName"`
	FieldSchema      map[string]interface{} `json:"fieldSchema"`
	RequiredFields   []string               `json:"requiredFields"`
	FilterFields     []string               `json:"filterFields"`
	DisplayTemplate  map[string]interface{} `json:"displayTemplate"`
	ReviewRules      map[string]interface{} `json:"reviewRules"`
	SortWeights      map[string]interface{} `json:"sortWeights"`
	MessageRules     map[string]interface{} `json:"messageRules"`
	DefaultValidDays int64                  `json:"defaultValidDays"`
	Status           string                 `json:"status"`
}

type AdminReviewResourceReq struct {
	Action string `json:"action"`
	Reason string `json:"reason,optional"`
}

type AdminReviewResourceResp struct {
	Id      string `json:"id"`
	Status  string `json:"status"`
	Message string `json:"message"`
}

type AdminReviewVerificationReq struct {
	Action     string `json:"action"`
	ReviewNote string `json:"reviewNote,optional"`
}

type AdminReviewVerificationResp struct {
	Id      string `json:"id"`
	Status  string `json:"status"`
	Message string `json:"message"`
}

type AdminSaveBannerTopicReq struct {
	CityCode   string   `json:"cityCode,optional"`
	Kind       string   `json:"kind"`
	Title      string   `json:"title"`
	Subtitle   string   `json:"subtitle,optional"`
	CoverUrl   string   `json:"coverUrl,optional"`
	TypeScope  []string `json:"typeScope,optional"`
	JumpType   string   `json:"jumpType"`
	JumpTarget string   `json:"jumpTarget"`
	Tags       []string `json:"tags,optional"`
	StartAt    string   `json:"startAt,optional"`
	EndAt      string   `json:"endAt,optional"`
	SortOrder  int64    `json:"sortOrder,optional"`
	Status     string   `json:"status,optional"`
}

type AdminSaveBannerTopicResp struct {
	Id        string `json:"id"`
	UpdatedAt string `json:"updatedAt"`
}

type AdminUpdateDemandStatusReq struct {
	Status string `json:"status"`
}

type AdminUpdateDemandStatusResp struct {
	Id     string `json:"id"`
	Status string `json:"status"`
}

type AdminUpdateMatchCaseStatusReq struct {
	Status     string `json:"status"`
	ResultNote string `json:"resultNote,optional"`
}

type AdminUpdateResourceTypeConfigReq struct {
	FieldSchema      map[string]interface{} `json:"fieldSchema,optional"`
	RequiredFields   []string               `json:"requiredFields,optional"`
	FilterFields     []string               `json:"filterFields,optional"`
	DisplayTemplate  map[string]interface{} `json:"displayTemplate,optional"`
	ReviewRules      map[string]interface{} `json:"reviewRules,optional"`
	SortWeights      map[string]interface{} `json:"sortWeights,optional"`
	MessageRules     map[string]interface{} `json:"messageRules,optional"`
	DefaultValidDays int64                  `json:"defaultValidDays,optional"`
	Status           string                 `json:"status,optional"`
}

type AdminUpdateResourceTypeConfigResp struct {
	Id        string `json:"id"`
	UpdatedAt string `json:"updatedAt"`
}

type AuthUserInfo struct {
	Id              string   `json:"id"`
	Nickname        string   `json:"nickname,optional"`
	AvatarUrl       string   `json:"avatarUrl,optional"`
	DefaultCityCode string   `json:"defaultCityCode,optional"`
	Roles           []string `json:"roles"`
}

type BindPhoneReq struct {
	Phone   string `json:"phone"`
	SmsCode string `json:"smsCode"`
}

type BindPhoneResp struct {
	Id    string `json:"id"`
	Phone string `json:"phone"`
}

type CityStationInfo struct {
	Id              string `json:"id"`
	Code            string `json:"code"`
	Name            string `json:"name"`
	PrimaryCategory string `json:"primaryCategory,optional"`
	Status          string `json:"status"`
}

type ContactEventReq struct {
	Action string `json:"action"`
}

type ContactEventResp struct {
	Message string `json:"message"`
}

type CreateMerchantReq struct {
	CityCode       string   `json:"cityCode"`
	Name           string   `json:"name"`
	MerchantType   string   `json:"merchantType"`
	MainCategories []string `json:"mainCategories"`
	ContactName    string   `json:"contactName"`
	ContactPhone   string   `json:"contactPhone"`
	ContactWechat  string   `json:"contactWechat,optional"`
	AddressText    string   `json:"addressText,optional"`
	Description    string   `json:"description,optional"`
}

type CreateMerchantResp struct {
	Id                 string `json:"id"`
	Name               string `json:"name"`
	VerificationStatus string `json:"verificationStatus"`
	Status             string `json:"status"`
}

type CreatePurchaseDemandReq struct {
	CityCode            string                 `json:"cityCode,optional"`
	DemandType          string                 `json:"demandType"`
	Title               string                 `json:"title"`
	Category            string                 `json:"category"`
	PriceRange          PriceRangeReq          `json:"priceRange,optional"`
	QuantityRequirement QuantityRequirementReq `json:"quantityRequirement,optional"`
	Attributes          map[string]interface{} `json:"attributes,optional"`
	Contact             DemandContactReq       `json:"contact"`
}

type CreatePurchaseDemandResp struct {
	Id      string `json:"id"`
	Status  string `json:"status"`
	Message string `json:"message"`
}

type CreateResourceReq struct {
	MerchantId   string                 `json:"merchantId"`
	CityCode     string                 `json:"cityCode"`
	TypeCode     string                 `json:"typeCode"`
	Title        string                 `json:"title"`
	Category     string                 `json:"category"`
	District     string                 `json:"district,optional"`
	PriceText    string                 `json:"priceText,optional"`
	QuantityText string                 `json:"quantityText,optional"`
	Description  string                 `json:"description"`
	Attributes   map[string]interface{} `json:"attributes,optional"`
	Tags         []string               `json:"tags,optional"`
	Images       []string               `json:"images,optional"`
	Contact      ResourceContactReq     `json:"contact"`
}

type CreateResourceResp struct {
	Id      string `json:"id"`
	Status  string `json:"status"`
	Message string `json:"message"`
}

type CreditTagInfo struct {
	Code  string `json:"code"`
	Label string `json:"label"`
}

type DealFeedbackReq struct {
	IsDealt                 bool   `json:"isDealt"`
	IsReal                  bool   `json:"isReal,optional"`
	ResponseTimely          bool   `json:"responseTimely,optional"`
	WillingToCooperateAgain bool   `json:"willingToCooperateAgain,optional"`
	Note                    string `json:"note,optional"`
}

type DealFeedbackResp struct {
	Id      string `json:"id"`
	Status  string `json:"status"`
	Message string `json:"message"`
}

type DemandContactReq struct {
	Name   string `json:"name"`
	Phone  string `json:"phone"`
	Wechat string `json:"wechat,optional"`
}

type DetailViewResp struct {
	Message string `json:"message"`
}

type HomeBannerItem struct {
	Id         string   `json:"id"`
	Title      string   `json:"title"`
	Subtitle   string   `json:"subtitle,optional"`
	CoverUrl   string   `json:"coverUrl,optional"`
	JumpType   string   `json:"jumpType"`
	JumpTarget string   `json:"jumpTarget"`
	Tags       []string `json:"tags"`
}

type HomeBannersReq struct {
	CityCode string `form:"cityCode,optional"`
}

type HomeBannersResp struct {
	Items []HomeBannerItem `json:"items"`
}

type LatestVerificationResp struct {
	Id               string `json:"id"`
	VerificationType string `json:"verificationType"`
	Status           string `json:"status"`
	ReviewedAt       string `json:"reviewedAt,optional"`
}

type ListCityStationsResp struct {
	Items []CityStationInfo `json:"items"`
}

type ListMerchantEntitlementsResp struct {
	Items []MerchantEntitlementInfo `json:"items"`
}

type ListMessagesReq struct {
	UserId   string `form:"userId,optional"`
	RoleCode string `form:"roleCode,optional"`
	Type     string `form:"type,optional"`
	Status   string `form:"status,optional"`
	Page     int64  `form:"page,optional"`
	PageSize int64  `form:"pageSize,optional"`
}

type ListMessagesResp struct {
	Items    []MessageListItem `json:"items"`
	Page     int64             `json:"page"`
	PageSize int64             `json:"pageSize"`
	Total    int64             `json:"total"`
}

type ListMyPurchaseDemandsReq struct {
	Page     int64 `form:"page,optional"`
	PageSize int64 `form:"pageSize,optional"`
}

type ListMyPurchaseDemandsResp struct {
	Items    []PurchaseDemandListItem `json:"items"`
	Page     int64                    `json:"page"`
	PageSize int64                    `json:"pageSize"`
	Total    int64                    `json:"total"`
}

type ListMyResourcesReq struct {
	MerchantId string `form:"merchantId"`
	Status     string `form:"status,optional"`
	Page       int64  `form:"page,optional"`
	PageSize   int64  `form:"pageSize,optional"`
}

type ListMyResourcesResp struct {
	Items    []MyResourceItem `json:"items"`
	Page     int64            `json:"page"`
	PageSize int64            `json:"pageSize"`
	Total    int64            `json:"total"`
}

type ListResourceTypesResp struct {
	Items []ResourceTypeConfigInfo `json:"items"`
}

type ListResourcesReq struct {
	CityCode     string `form:"cityCode,optional"`
	TypeCode     string `form:"typeCode,optional"`
	Keyword      string `form:"keyword,optional"`
	Category     string `form:"category,optional"`
	VerifiedOnly bool   `form:"verifiedOnly,optional"`
	Page         int64  `form:"page,optional"`
	PageSize     int64  `form:"pageSize,optional"`
}

type ListResourcesResp struct {
	Items    []ResourceListItem `json:"items"`
	Page     int64              `json:"page"`
	PageSize int64              `json:"pageSize"`
	Total    int64              `json:"total"`
}

type ListTopVouchersResp struct {
	Items []TopVoucherInfo `json:"items"`
}

type ManagedMerchantInfo struct {
	Id   string `json:"id"`
	Name string `json:"name"`
	Role string `json:"role"`
}

type MeResp struct {
	Id               string                `json:"id"`
	Phone            string                `json:"phone,optional"`
	Nickname         string                `json:"nickname,optional"`
	DefaultCityCode  string                `json:"defaultCityCode,optional"`
	Roles            []string              `json:"roles"`
	ManagedMerchants []ManagedMerchantInfo `json:"managedMerchants"`
}

type MerchantContactInfo struct {
	Name         string `json:"name"`
	PhoneMasked  string `json:"phoneMasked"`
	WechatMasked string `json:"wechatMasked,optional"`
}

type MerchantDetailResp struct {
	Id                 string                   `json:"id"`
	Name               string                   `json:"name"`
	MerchantType       string                   `json:"merchantType"`
	CityCode           string                   `json:"cityCode"`
	MainCategories     []string                 `json:"mainCategories"`
	VerificationStatus string                   `json:"verificationStatus"`
	CreditTags         []CreditTagInfo          `json:"creditTags"`
	Contact            MerchantContactInfo      `json:"contact"`
	ResourcesSummary   MerchantResourcesSummary `json:"resourcesSummary"`
	Description        string                   `json:"description,optional"`
	Images             []string                 `json:"images,optional"`
	LastActiveAt       string                   `json:"lastActiveAt,optional"`
}

type MerchantEntitlementInfo struct {
	Type            string `json:"type"`
	SourceType      string `json:"sourceType"`
	TotalAmount     int64  `json:"totalAmount"`
	UsedAmount      int64  `json:"usedAmount"`
	RemainingAmount int64  `json:"remainingAmount"`
	ExpiresAt       string `json:"expiresAt,optional"`
}

type MerchantLast7DaysMetrics struct {
	ExposureCount     int64 `json:"exposureCount"`
	DetailViewCount   int64 `json:"detailViewCount"`
	ContactClickCount int64 `json:"contactClickCount"`
}

type MerchantMetricsSummaryResp struct {
	MerchantId             string                   `json:"merchantId"`
	PublishedResourceCount int64                    `json:"publishedResourceCount"`
	ExpiringResourceCount  int64                    `json:"expiringResourceCount"`
	DealtResourceCount     int64                    `json:"dealtResourceCount"`
	Last7Days              MerchantLast7DaysMetrics `json:"last7Days"`
}

type MerchantResourcesSummary struct {
	PublishedCount int64 `json:"publishedCount"`
	DealtCount     int64 `json:"dealtCount"`
}

type MessageListItem struct {
	Id          string `json:"id"`
	MessageType string `json:"messageType"`
	Title       string `json:"title"`
	Content     string `json:"content"`
	TargetUrl   string `json:"targetUrl,optional"`
	Status      string `json:"status"`
	CreatedAt   string `json:"createdAt"`
}

type MyResourceItem struct {
	Id          string            `json:"id"`
	TypeCode    string            `json:"typeCode"`
	Title       string            `json:"title"`
	Category    string            `json:"category"`
	Status      string            `json:"status"`
	PublishedAt string            `json:"publishedAt,optional"`
	ExpiresAt   string            `json:"expiresAt,optional"`
	DealtAt     string            `json:"dealtAt,optional"`
	Metrics     MyResourceMetrics `json:"metrics"`
}

type MyResourceMetrics struct {
	ExposureCount   int64 `json:"exposureCount"`
	DetailViewCount int64 `json:"detailViewCount"`
	PhoneClickCount int64 `json:"phoneClickCount"`
	WechatCopyCount int64 `json:"wechatCopyCount"`
}

type PriceRangeReq struct {
	Min float64 `json:"min,optional"`
	Max float64 `json:"max,optional"`
}

type PurchaseDemandListItem struct {
	Id        string `json:"id"`
	Title     string `json:"title"`
	Status    string `json:"status"`
	CreatedAt string `json:"createdAt"`
}

type QuantityRequirementReq struct {
	Quantity int64  `json:"quantity,optional"`
	Unit     string `json:"unit,optional"`
}

type ReadMessageResp struct {
	Id     string `json:"id"`
	Status string `json:"status"`
}

type RedeemTopVoucherReq struct {
	ResourceId string `json:"resourceId"`
}

type RedeemTopVoucherResp struct {
	VoucherId  string `json:"voucherId"`
	ResourceId string `json:"resourceId"`
	Status     string `json:"status"`
	Message    string `json:"message"`
}

type RefreshResourceResp struct {
	Id                    string `json:"id"`
	RefreshedAt           string `json:"refreshedAt"`
	RemainingRefreshQuota int64  `json:"remainingRefreshQuota"`
}

type RepostSimilarResp struct {
	Id      string `json:"id"`
	Status  string `json:"status"`
	Message string `json:"message"`
}

type ResourceContactMasked struct {
	Name         string `json:"name"`
	PhoneMasked  string `json:"phoneMasked"`
	WechatMasked string `json:"wechatMasked,optional"`
}

type ResourceContactReq struct {
	Name   string `json:"name"`
	Phone  string `json:"phone"`
	Wechat string `json:"wechat,optional"`
}

type ResourceDetailResp struct {
	Id           string                 `json:"id"`
	Status       string                 `json:"status"`
	TypeCode     string                 `json:"typeCode"`
	Title        string                 `json:"title"`
	Category     string                 `json:"category"`
	Description  string                 `json:"description"`
	PriceText    string                 `json:"priceText,optional"`
	QuantityText string                 `json:"quantityText,optional"`
	Attributes   map[string]interface{} `json:"attributes"`
	Merchant     ResourceMerchantBrief  `json:"merchant"`
	Contact      ResourceContactMasked  `json:"contact"`
	PublishedAt  string                 `json:"publishedAt,optional"`
	ExpiresAt    string                 `json:"expiresAt,optional"`
}

type ResourceListItem struct {
	Id           string                `json:"id"`
	TypeCode     string                `json:"typeCode"`
	Title        string                `json:"title"`
	Category     string                `json:"category"`
	District     string                `json:"district,optional"`
	PriceText    string                `json:"priceText,optional"`
	QuantityText string                `json:"quantityText,optional"`
	Merchant     ResourceMerchantBrief `json:"merchant"`
	CreditTags   []string              `json:"creditTags"`
	RefreshedAt  string                `json:"refreshedAt,optional"`
}

type ResourceMerchantBrief struct {
	Id                 string `json:"id"`
	Name               string `json:"name"`
	VerificationStatus string `json:"verificationStatus"`
}

type ResourceMetricsDailyItem struct {
	Date            string `json:"date"`
	ExposureCount   int64  `json:"exposureCount"`
	DetailViewCount int64  `json:"detailViewCount"`
	PhoneClickCount int64  `json:"phoneClickCount"`
	WechatCopyCount int64  `json:"wechatCopyCount"`
}

type ResourceMetricsReq struct {
	From string `form:"from,optional"`
	To   string `form:"to,optional"`
}

type ResourceMetricsResp struct {
	ResourceId string                     `json:"resourceId"`
	Summary    ResourceMetricsSummary     `json:"summary"`
	Daily      []ResourceMetricsDailyItem `json:"daily"`
}

type ResourceMetricsSummary struct {
	ExposureCount     int64 `json:"exposureCount"`
	DetailViewCount   int64 `json:"detailViewCount"`
	PhoneClickCount   int64 `json:"phoneClickCount"`
	WechatCopyCount   int64 `json:"wechatCopyCount"`
	DealFeedbackCount int64 `json:"dealFeedbackCount"`
}

type ResourceTypeConfigInfo struct {
	Id               string                 `json:"id"`
	TypeCode         string                 `json:"typeCode"`
	TypeName         string                 `json:"typeName"`
	DefaultValidDays int64                  `json:"defaultValidDays"`
	RequiredFields   []string               `json:"requiredFields"`
	FilterFields     []string               `json:"filterFields"`
	DisplayTemplate  map[string]interface{} `json:"displayTemplate"`
}

type SearchResourcesReq struct {
	CityCode     string `form:"cityCode,optional"`
	TypeCode     string `form:"typeCode,optional"`
	Keyword      string `form:"keyword,optional"`
	Category     string `form:"category,optional"`
	VerifiedOnly bool   `form:"verifiedOnly,optional"`
	Page         int64  `form:"page,optional"`
	PageSize     int64  `form:"pageSize,optional"`
}

type SubmitResourceResp struct {
	Id      string `json:"id"`
	Status  string `json:"status"`
	Message string `json:"message"`
}

type SubmitVerificationReq struct {
	VerificationType string                 `json:"verificationType"`
	BusinessName     string                 `json:"businessName,optional"`
	LicenseUrl       string                 `json:"licenseUrl,optional"`
	StorefrontUrl    string                 `json:"storefrontUrl,optional"`
	Materials        map[string]interface{} `json:"materials,optional"`
}

type SubmitVerificationResp struct {
	Id      string `json:"id"`
	Status  string `json:"status"`
	Message string `json:"message"`
}

type TakeDownOwnResourceReq struct {
	Reason string `json:"reason"`
}

type TakeDownOwnResourceResp struct {
	Id      string `json:"id"`
	Status  string `json:"status"`
	Message string `json:"message"`
}

type TopVoucherInfo struct {
	Id               string   `json:"id"`
	Status           string   `json:"status"`
	TopDurationHours int64    `json:"topDurationHours"`
	AllowedTypeCodes []string `json:"allowedTypeCodes"`
	ExpiresAt        string   `json:"expiresAt,optional"`
}

type TopicDemandEntry struct {
	Title      string `json:"title"`
	ButtonText string `json:"buttonText"`
}

type TopicInfoResp struct {
	Id       string   `json:"id"`
	Title    string   `json:"title"`
	Subtitle string   `json:"subtitle,optional"`
	CoverUrl string   `json:"coverUrl,optional"`
	Tags     []string `json:"tags"`
}

type TopicResourceItem struct {
	Id           string `json:"id"`
	TypeCode     string `json:"typeCode"`
	Title        string `json:"title"`
	Category     string `json:"category"`
	District     string `json:"district,optional"`
	PriceText    string `json:"priceText,optional"`
	QuantityText string `json:"quantityText,optional"`
	MerchantName string `json:"merchantName"`
}

type TopicResourcesReq struct {
	CityCode string `form:"cityCode,optional"`
	Page     int64  `form:"page,optional"`
	PageSize int64  `form:"pageSize,optional"`
}

type TopicResourcesResp struct {
	Topic       TopicInfoResp       `json:"topic"`
	Items       []TopicResourceItem `json:"items"`
	Page        int64               `json:"page"`
	PageSize    int64               `json:"pageSize"`
	Total       int64               `json:"total"`
	DemandEntry TopicDemandEntry    `json:"demandEntry,optional"`
}

type UpdateMerchantReq struct {
	MainCategories []string `json:"mainCategories,optional"`
	Description    string   `json:"description,optional"`
	Images         []string `json:"images,optional"`
}

type UpdateMerchantResp struct {
	Id        string `json:"id"`
	UpdatedAt string `json:"updatedAt"`
}

type ValidateWebviewReq struct {
	Url string `json:"url"`
}

type ValidateWebviewResp struct {
	Allowed bool   `json:"allowed"`
	Url     string `json:"url"`
}

type WechatLoginReq struct {
	Code            string `json:"code"`
	DefaultCityCode string `json:"defaultCityCode,optional"`
}

type WechatLoginResp struct {
	Token string       `json:"token"`
	User  AuthUserInfo `json:"user"`
}
