// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5

package types

type AdminBannerTopicItem struct {
	Id         string   `json:"id"`
	CityCode   string   `json:"cityCode,optional"`
	Kind       string   `json:"kind"`
	Title      string   `json:"title"`
	Subtitle   string   `json:"subtitle,optional"`
	CoverUrl   string   `json:"coverUrl,optional"`
	TypeScope  []string `json:"typeScope"`
	JumpType   string   `json:"jumpType"`
	JumpTarget string   `json:"jumpTarget"`
	Tags       []string `json:"tags"`
	StartAt    string   `json:"startAt,optional"`
	EndAt      string   `json:"endAt,optional"`
	SortOrder  int64    `json:"sortOrder"`
	Status     string   `json:"status"`
	UpdatedAt  string   `json:"updatedAt"`
}

type AdminBatchGenerateMapObjectsReq struct {
	StartCode     string   `json:"startCode"`
	Count         int64    `json:"count"`
	Direction     string   `json:"direction"`
	StartX        string   `json:"startX"`
	StartY        string   `json:"startY"`
	Width         string   `json:"width"`
	Height        string   `json:"height"`
	Gap           string   `json:"gap"`
	Type          string   `json:"type"`
	Layer         string   `json:"layer"`
	CategoryCodes []string `json:"categoryCodes,optional"`
	ServiceTags   []string `json:"serviceTags,optional"`
}

type AdminBatchGenerateMapObjectsResp struct {
	Items []MapObjectItem `json:"items"`
}

type AdminCreateResourceTypeConfigReq struct {
	CityCode         string                 `json:"cityCode"`
	TypeCode         string                 `json:"typeCode"`
	TypeName         string                 `json:"typeName"`
	Direction        string                 `json:"direction"`
	GroupCode        string                 `json:"groupCode"`
	GroupName        string                 `json:"groupName"`
	GroupSort        int64                  `json:"groupSort,optional"`
	FieldSchema      map[string]interface{} `json:"fieldSchema,optional"`
	RequiredFields   []string               `json:"requiredFields,optional"`
	FilterFields     []string               `json:"filterFields,optional"`
	DisplayTemplate  map[string]interface{} `json:"displayTemplate,optional"`
	ReviewRules      map[string]interface{} `json:"reviewRules,optional"`
	SortWeights      map[string]interface{} `json:"sortWeights,optional"`
	MessageRules     map[string]interface{} `json:"messageRules,optional"`
	CommercialRules  map[string]interface{} `json:"commercialRules,optional"`
	DefaultValidDays int64                  `json:"defaultValidDays,optional"`
	Status           string                 `json:"status,optional"`
}

type AdminCreateResourceTypeConfigResp struct {
	Id        string `json:"id"`
	UpdatedAt string `json:"updatedAt"`
}

type AdminDashboardMetrics struct {
	PendingResourceCount     int64 `json:"pendingResourceCount"`
	PendingVerificationCount int64 `json:"pendingVerificationCount"`
	TodayContactCount        int64 `json:"todayContactCount"`
}

type AdminDashboardOverviewReq struct {
	CityCode string `form:"cityCode,optional"`
}

type AdminDashboardOverviewResp struct {
	Metrics AdminDashboardMetrics `json:"metrics"`
	Tasks   []AdminDashboardTask  `json:"tasks"`
}

type AdminDashboardTask struct {
	Type      string `json:"type"`
	Title     string `json:"title"`
	CityName  string `json:"cityName"`
	CreatedAt string `json:"createdAt"`
}

type AdminGrantEntitlementReq struct {
	EntitlementType string `json:"entitlementType"`
	SourceType      string `json:"sourceType"`
	TotalAmount     int64  `json:"totalAmount"`
	ExpiresAt       string `json:"expiresAt,optional"`
	Reason          string `json:"reason"`
}

type AdminGrantEntitlementResp struct {
	Id      string `json:"id"`
	Message string `json:"message"`
}

type AdminHotSearchKeywordItem struct {
	Id        string `json:"id"`
	CityCode  string `json:"cityCode,optional"`
	Keyword   string `json:"keyword"`
	SortOrder int64  `json:"sortOrder"`
	Status    string `json:"status"`
	StartAt   string `json:"startAt,optional"`
	EndAt     string `json:"endAt,optional"`
	UpdatedAt string `json:"updatedAt"`
}

type AdminListBannerTopicsReq struct {
	CityCode string `form:"cityCode,optional"`
	Kind     string `form:"kind,optional"`
	Status   string `form:"status,optional"`
}

type AdminListBannerTopicsResp struct {
	Items []AdminBannerTopicItem `json:"items"`
}

type AdminListHotSearchKeywordsReq struct {
	CityCode string `form:"cityCode,optional"`
	Status   string `form:"status,optional"`
}

type AdminListHotSearchKeywordsResp struct {
	Items []AdminHotSearchKeywordItem `json:"items"`
}

type AdminListMapBindRequestsReq struct {
	Status   string `form:"status,optional"`
	Keyword  string `form:"keyword,optional"`
	Page     int64  `form:"page,optional"`
	PageSize int64  `form:"pageSize,optional"`
}

type AdminListMapBindRequestsResp struct {
	Items []MapBindRequestItem `json:"items"`
}

type AdminListMapCategoriesReq struct {
	Type   string `form:"type,optional"`
	Status string `form:"status,optional"`
}

type AdminListMapCategoriesResp struct {
	Items []MapCategoryItem `json:"items"`
}

type AdminListMapObjectsReq struct {
	Types   string `form:"types,optional"`
	Status  string `form:"status,optional"`
	Keyword string `form:"keyword,optional"`
	MinX    string `form:"minX,optional"`
	MinY    string `form:"minY,optional"`
	MaxX    string `form:"maxX,optional"`
	MaxY    string `form:"maxY,optional"`
	Zoom    int64  `form:"zoom,optional"`
}

type AdminListMapScenesReq struct {
	CityCode string `form:"cityCode,optional"`
	Status   string `form:"status,optional"`
	Type     string `form:"type,optional"`
}

type AdminListMerchantsReq struct {
	CityCode     string `form:"cityCode,optional"`
	MerchantType string `form:"merchantType,optional"`
	Status       string `form:"status,optional"`
	Keyword      string `form:"keyword,optional"`
	Page         int64  `form:"page,optional"`
	PageSize     int64  `form:"pageSize,optional"`
}

type AdminListMerchantsResp struct {
	Items    []AdminMerchantListItem `json:"items"`
	Page     int64                   `json:"page"`
	PageSize int64                   `json:"pageSize"`
	Total    int64                   `json:"total"`
}

type AdminListOperatorsReq struct {
	Keyword  string `form:"keyword,optional"`
	Role     string `form:"role,optional"`
	Status   string `form:"status,optional"`
	Page     int64  `form:"page,optional"`
	PageSize int64  `form:"pageSize,optional"`
}

type AdminListOperatorsResp struct {
	Items    []AdminOperatorItem `json:"items"`
	Page     int64               `json:"page"`
	PageSize int64               `json:"pageSize"`
	Total    int64               `json:"total"`
}

type AdminListQuotaPacksResp struct {
	Items []AdminQuotaPackConfigItem `json:"items"`
}

type AdminListResourceTypeConfigsReq struct {
	CityCode string `form:"cityCode,optional"`
	Status   string `form:"status,optional"`
}

type AdminListResourceTypeConfigsResp struct {
	Items []AdminResourceTypeConfigItem `json:"items"`
}

type AdminListVIPPlansResp struct {
	Items []AdminVIPPlanConfigItem `json:"items"`
}

type AdminListVIPPromotionsResp struct {
	Items []AdminVIPPromotionConfigItem `json:"items"`
}

type AdminLoginReq struct {
	LoginName string `json:"loginName"`
	Password  string `json:"password"`
}

type AdminLoginResp struct {
	Token      string   `json:"token"`
	OperatorId string   `json:"operatorId"`
	Roles      []string `json:"roles"`
	Modules    []string `json:"modules"`
}

type AdminMerchantListItem struct {
	Id                 string `json:"id"`
	Name               string `json:"name"`
	MerchantType       string `json:"merchantType"`
	VerificationStatus string `json:"verificationStatus"`
	Status             string `json:"status"`
	LastActiveAt       string `json:"lastActiveAt,optional"`
}

type AdminModuleItem struct {
	Code  string `json:"code"`
	Label string `json:"label"`
	Group string `json:"group"`
}

type AdminModulePermissionsResp struct {
	Modules []AdminModuleItem               `json:"modules"`
	Roles   []AdminRoleModulePermissionItem `json:"roles"`
}

type AdminOperationLogItem struct {
	Id           string `json:"id"`
	OperatorId   string `json:"operatorId"`
	OperatorRole string `json:"operatorRole"`
	ObjectType   string `json:"objectType"`
	ObjectId     string `json:"objectId,optional"`
	Action       string `json:"action"`
	Reason       string `json:"reason,optional"`
	CreatedAt    string `json:"createdAt"`
}

type AdminOperationLogsReq struct {
	ObjectType string `form:"objectType,optional"`
	ObjectId   string `form:"objectId,optional"`
	OperatorId string `form:"operatorId,optional"`
	Page       int64  `form:"page,optional"`
	PageSize   int64  `form:"pageSize,optional"`
}

type AdminOperationLogsResp struct {
	Items    []AdminOperationLogItem `json:"items"`
	Page     int64                   `json:"page"`
	PageSize int64                   `json:"pageSize"`
	Total    int64                   `json:"total"`
}

type AdminOperatorItem struct {
	OperatorId  string   `json:"operatorId"`
	LoginName   string   `json:"loginName"`
	RealName    string   `json:"realName"`
	Status      string   `json:"status"`
	Roles       []string `json:"roles"`
	CreatedAt   string   `json:"createdAt"`
	LastLoginAt string   `json:"lastLoginAt,optional"`
}

type AdminPendingResourceItem struct {
	Id           string `json:"id"`
	Title        string `json:"title"`
	TypeCode     string `json:"typeCode"`
	MerchantName string `json:"merchantName"`
	CreatedAt    string `json:"createdAt"`
}

type AdminPendingResourcesReq struct {
	CityCode string `form:"cityCode,optional"`
	TypeCode string `form:"typeCode,optional"`
	Page     int64  `form:"page,optional"`
	PageSize int64  `form:"pageSize,optional"`
}

type AdminPendingResourcesResp struct {
	Items    []AdminPendingResourceItem `json:"items"`
	Page     int64                      `json:"page"`
	PageSize int64                      `json:"pageSize"`
	Total    int64                      `json:"total"`
}

type AdminPendingVerificationItem struct {
	Id               string                 `json:"id"`
	MerchantId       string                 `json:"merchantId"`
	MerchantName     string                 `json:"merchantName"`
	VerificationType string                 `json:"verificationType"`
	Status           string                 `json:"status"`
	SubmittedAt      string                 `json:"submittedAt"`
	BusinessName     string                 `json:"businessName"`
	LicenseUrl       string                 `json:"licenseUrl"`
	StorefrontUrl    string                 `json:"storefrontUrl"`
	Materials        map[string]interface{} `json:"materials"`
}

type AdminPendingVerificationsReq struct {
	Page     int64 `form:"page,optional"`
	PageSize int64 `form:"pageSize,optional"`
}

type AdminPendingVerificationsResp struct {
	Items    []AdminPendingVerificationItem `json:"items"`
	Page     int64                          `json:"page"`
	PageSize int64                          `json:"pageSize"`
	Total    int64                          `json:"total"`
}

type AdminPublishMapSceneResp struct {
	Item    MapSceneItem `json:"item"`
	Message string       `json:"message"`
}

type AdminQuotaPackConfigItem struct {
	Code              string                `json:"code"`
	Name              string                `json:"name"`
	Description       string                `json:"description,optional"`
	StandardPriceCent int64                 `json:"standardPriceCent"`
	SalePriceCent     int64                 `json:"salePriceCent,optional"`
	SaleLabel         string                `json:"saleLabel,optional"`
	Status            string                `json:"status"`
	DisplayOrder      int64                 `json:"displayOrder"`
	Benefits          AdminVIPBenefitConfig `json:"benefits"`
	UpdatedAt         string                `json:"updatedAt,optional"`
}

type AdminResourceReportItem struct {
	Id               string `json:"id"`
	Status           string `json:"status"`
	ResourceId       string `json:"resourceId"`
	ResourceTitle    string `json:"resourceTitle"`
	ResourceStatus   string `json:"resourceStatus"`
	MerchantId       string `json:"merchantId"`
	MerchantName     string `json:"merchantName"`
	ReportCount      int64  `json:"reportCount"`
	ReasonCode       string `json:"reasonCode"`
	ReasonText       string `json:"reasonText,optional"`
	LatestReportedAt string `json:"latestReportedAt"`
}

type AdminResourceReportsReq struct {
	Status   string `form:"status,optional"`
	Page     int64  `form:"page,optional"`
	PageSize int64  `form:"pageSize,optional"`
}

type AdminResourceReportsResp struct {
	Items    []AdminResourceReportItem `json:"items"`
	Page     int64                     `json:"page"`
	PageSize int64                     `json:"pageSize"`
	Total    int64                     `json:"total"`
}

type AdminResourceTypeConfigItem struct {
	Id               string                 `json:"id"`
	CityCode         string                 `json:"cityCode,optional"`
	TypeCode         string                 `json:"typeCode"`
	TypeName         string                 `json:"typeName"`
	Direction        string                 `json:"direction"`
	FieldSchema      map[string]interface{} `json:"fieldSchema"`
	RequiredFields   []string               `json:"requiredFields"`
	FilterFields     []string               `json:"filterFields"`
	DisplayTemplate  map[string]interface{} `json:"displayTemplate"`
	ReviewRules      map[string]interface{} `json:"reviewRules"`
	SortWeights      map[string]interface{} `json:"sortWeights"`
	MessageRules     map[string]interface{} `json:"messageRules"`
	CommercialRules  map[string]interface{} `json:"commercialRules"`
	DefaultValidDays int64                  `json:"defaultValidDays"`
	Status           string                 `json:"status"`
}

type AdminReviewMapBindRequestReq struct {
	Action     string `json:"action"`
	ReviewNote string `json:"reviewNote,optional"`
}

type AdminReviewMapBindRequestResp struct {
	Item MapBindRequestItem `json:"item"`
}

type AdminReviewResourceReportReq struct {
	Action             string `json:"action"`
	ResourceAction     string `json:"resourceAction,optional"`
	Reason             string `json:"reason,optional"`
	RefundPublishQuota bool   `json:"refundPublishQuota,optional"`
}

type AdminReviewResourceReportResp struct {
	Id                  string `json:"id"`
	Status              string `json:"status"`
	ResourceId          string `json:"resourceId"`
	ResourceStatus      string `json:"resourceStatus"`
	ResolvedReportCount int64  `json:"resolvedReportCount"`
	RefundPublishQuota  bool   `json:"refundPublishQuota"`
	Message             string `json:"message"`
}

type AdminReviewResourceReq struct {
	Action string `json:"action"`
	Reason string `json:"reason,optional"`
}

type AdminReviewResourceResp struct {
	Id      string `json:"id"`
	Status  string `json:"status"`
	Message string `json:"message"`
}

type AdminReviewVerificationReq struct {
	Action     string `json:"action"`
	ReviewNote string `json:"reviewNote,optional"`
}

type AdminReviewVerificationResp struct {
	Id      string `json:"id"`
	Status  string `json:"status"`
	Message string `json:"message"`
}

type AdminRoleModulePermissionItem struct {
	RoleCode string   `json:"roleCode"`
	RoleName string   `json:"roleName"`
	Modules  []string `json:"modules"`
}

type AdminRunResourceLifecycleResp struct {
	ExpiredCount          int64 `json:"expiredCount"`
	ExpiringReminderCount int64 `json:"expiringReminderCount"`
}

type AdminSaveBannerTopicReq struct {
	CityCode   string   `json:"cityCode,optional"`
	Kind       string   `json:"kind"`
	Title      string   `json:"title"`
	Subtitle   string   `json:"subtitle,optional"`
	CoverUrl   string   `json:"coverUrl,optional"`
	TypeScope  []string `json:"typeScope,optional"`
	JumpType   string   `json:"jumpType"`
	JumpTarget string   `json:"jumpTarget"`
	Tags       []string `json:"tags,optional"`
	StartAt    string   `json:"startAt,optional"`
	EndAt      string   `json:"endAt,optional"`
	SortOrder  int64    `json:"sortOrder,optional"`
	Status     string   `json:"status,optional"`
}

type AdminSaveBannerTopicResp struct {
	Id        string `json:"id"`
	UpdatedAt string `json:"updatedAt"`
}

type AdminSaveHotSearchKeywordReq struct {
	CityCode  string `json:"cityCode,optional"`
	Keyword   string `json:"keyword"`
	SortOrder int64  `json:"sortOrder,optional"`
	Status    string `json:"status,optional"`
	StartAt   string `json:"startAt,optional"`
	EndAt     string `json:"endAt,optional"`
}

type AdminSaveHotSearchKeywordResp struct {
	Id        string `json:"id"`
	UpdatedAt string `json:"updatedAt"`
}

type AdminSaveMapCategoryReq struct {
	Code      string `json:"code"`
	Name      string `json:"name"`
	Type      string `json:"type"`
	IconUrl   string `json:"iconUrl,optional"`
	Sort      int64  `json:"sort,optional"`
	IsVisible bool   `json:"isVisible,optional"`
	Status    string `json:"status,optional"`
}

type AdminSaveMapCategoryResp struct {
	Item MapCategoryItem `json:"item"`
}

type AdminSaveMapObjectReq struct {
	Id             string                 `json:"id,optional"`
	MerchantId     string                 `json:"merchantId,optional"`
	Code           string                 `json:"code"`
	Name           string                 `json:"name"`
	Type           string                 `json:"type"`
	Layer          string                 `json:"layer"`
	GeometryType   string                 `json:"geometryType"`
	Geometry       map[string]interface{} `json:"geometry"`
	MinZoom        int64                  `json:"minZoom,optional"`
	MaxZoom        int64                  `json:"maxZoom,optional"`
	CategoryCodes  []string               `json:"categoryCodes,optional"`
	ServiceTags    []string               `json:"serviceTags,optional"`
	PlatformTags   []string               `json:"platformTags,optional"`
	PoiServiceTags []string               `json:"poiServiceTags,optional"`
	Address        string                 `json:"address,optional"`
	Phone          string                 `json:"phone,optional"`
	Wechat         string                 `json:"wechat,optional"`
	Lat            string                 `json:"lat,optional"`
	Lng            string                 `json:"lng,optional"`
	Extra          map[string]interface{} `json:"extra,optional"`
	Sort           int64                  `json:"sort,optional"`
	Status         string                 `json:"status,optional"`
}

type AdminSaveMapObjectResp struct {
	Item MapObjectItem `json:"item"`
}

type AdminSaveMapSceneReq struct {
	CityCode       string `json:"cityCode,optional"`
	Code           string `json:"code"`
	Name           string `json:"name"`
	Type           string `json:"type"`
	ParentCode     string `json:"parentCode,optional"`
	BackgroundUrl  string `json:"backgroundUrl"`
	Width          int64  `json:"width"`
	Height         int64  `json:"height"`
	MinScale       string `json:"minScale,optional"`
	MaxScale       string `json:"maxScale,optional"`
	DefaultScale   string `json:"defaultScale,optional"`
	DefaultCenterX string `json:"defaultCenterX,optional"`
	DefaultCenterY string `json:"defaultCenterY,optional"`
	FloorNo        string `json:"floorNo,optional"`
	Sort           int64  `json:"sort,optional"`
	Status         string `json:"status,optional"`
}

type AdminSaveMapSceneResp struct {
	Item MapSceneItem `json:"item"`
}

type AdminSaveOperatorReq struct {
	LoginName string   `json:"loginName"`
	RealName  string   `json:"realName"`
	Password  string   `json:"password,optional"`
	Roles     []string `json:"roles"`
	Status    string   `json:"status,optional"`
}

type AdminSaveOperatorResp struct {
	OperatorId string `json:"operatorId"`
	Message    string `json:"message"`
}

type AdminSaveQuotaPackConfigReq struct {
	Code              string                `json:"code,optional"`
	Name              string                `json:"name"`
	Description       string                `json:"description,optional"`
	StandardPriceCent int64                 `json:"standardPriceCent"`
	SalePriceCent     int64                 `json:"salePriceCent,optional"`
	SaleLabel         string                `json:"saleLabel,optional"`
	Status            string                `json:"status,optional"`
	DisplayOrder      int64                 `json:"displayOrder,optional"`
	Benefits          AdminVIPBenefitConfig `json:"benefits"`
}

type AdminSaveVIPConfigResp struct {
	Code      string `json:"code"`
	UpdatedAt string `json:"updatedAt"`
}

type AdminSaveVIPPlanConfigReq struct {
	Code              string                `json:"code,optional"`
	Name              string                `json:"name"`
	DurationMonths    int64                 `json:"durationMonths"`
	StandardPriceCent int64                 `json:"standardPriceCent"`
	Status            string                `json:"status,optional"`
	DisplayOrder      int64                 `json:"displayOrder,optional"`
	Benefits          AdminVIPBenefitConfig `json:"benefits"`
}

type AdminSaveVIPPromotionConfigReq struct {
	Code          string `json:"code,optional"`
	PlanCode      string `json:"planCode"`
	PromotionType string `json:"promotionType"`
	SalePriceCent int64  `json:"salePriceCent"`
	StartsAt      string `json:"startsAt,optional"`
	EndsAt        string `json:"endsAt,optional"`
	QuotaLimit    int64  `json:"quotaLimit,optional"`
	Status        string `json:"status,optional"`
}

type AdminSearchLogItem struct {
	Id          string                 `json:"id"`
	UserId      string                 `json:"userId,optional"`
	CityCode    string                 `json:"cityCode,optional"`
	CityName    string                 `json:"cityName,optional"`
	Keyword     string                 `json:"keyword"`
	Filters     map[string]interface{} `json:"filters"`
	ResultCount int64                  `json:"resultCount"`
	CreatedAt   string                 `json:"createdAt"`
}

type AdminSearchLogsReq struct {
	CityCode string `form:"cityCode,optional"`
	Keyword  string `form:"keyword,optional"`
	Page     int64  `form:"page,optional"`
	PageSize int64  `form:"pageSize,optional"`
}

type AdminSearchLogsResp struct {
	Items    []AdminSearchLogItem `json:"items"`
	Page     int64                `json:"page"`
	PageSize int64                `json:"pageSize"`
	Total    int64                `json:"total"`
}

type AdminUpdateMapObjectStatusReq struct {
	Status string `json:"status"`
}

type AdminUpdateMapObjectStatusResp struct {
	Item MapObjectItem `json:"item"`
}

type AdminUpdateOperatorStatusReq struct {
	Status string `json:"status"`
}

type AdminUpdateResourceTypeConfigReq struct {
	FieldSchema      map[string]interface{} `json:"fieldSchema,optional"`
	RequiredFields   []string               `json:"requiredFields,optional"`
	FilterFields     []string               `json:"filterFields,optional"`
	DisplayTemplate  map[string]interface{} `json:"displayTemplate,optional"`
	ReviewRules      map[string]interface{} `json:"reviewRules,optional"`
	SortWeights      map[string]interface{} `json:"sortWeights,optional"`
	MessageRules     map[string]interface{} `json:"messageRules,optional"`
	CommercialRules  map[string]interface{} `json:"commercialRules,optional"`
	DefaultValidDays int64                  `json:"defaultValidDays,optional"`
	Status           string                 `json:"status,optional"`
}

type AdminUpdateResourceTypeConfigResp struct {
	Id        string `json:"id"`
	UpdatedAt string `json:"updatedAt"`
}

type AdminUpdateRoleModulePermissionsReq struct {
	Modules []string `json:"modules"`
}

type AdminUpdateRoleModulePermissionsResp struct {
	RoleCode string   `json:"roleCode"`
	Modules  []string `json:"modules"`
	Message  string   `json:"message"`
}

type AdminVIPBenefitConfig struct {
	PublishPolicy      string `json:"publishPolicy,optional"`
	PublishQuota       int64  `json:"publishQuota"`
	RefreshQuota       int64  `json:"refreshQuota"`
	TopVoucherCount    int64  `json:"topVoucherCount"`
	TopDurationHours   int64  `json:"topDurationHours"`
	HomepageImageLimit int64  `json:"homepageImageLimit,optional"`
}

type AdminVIPPlanConfigItem struct {
	Code              string                `json:"code"`
	Name              string                `json:"name"`
	DurationMonths    int64                 `json:"durationMonths"`
	StandardPriceCent int64                 `json:"standardPriceCent"`
	Status            string                `json:"status"`
	DisplayOrder      int64                 `json:"displayOrder"`
	Benefits          AdminVIPBenefitConfig `json:"benefits"`
	UpdatedAt         string                `json:"updatedAt,optional"`
}

type AdminVIPPromotionConfigItem struct {
	Code          string `json:"code"`
	PlanCode      string `json:"planCode"`
	PlanName      string `json:"planName,optional"`
	PromotionType string `json:"promotionType"`
	SalePriceCent int64  `json:"salePriceCent"`
	StartsAt      string `json:"startsAt"`
	EndsAt        string `json:"endsAt,optional"`
	QuotaLimit    int64  `json:"quotaLimit,optional"`
	UsedCount     int64  `json:"usedCount"`
	Status        string `json:"status"`
	UpdatedAt     string `json:"updatedAt,optional"`
}

type AdminVerificationBillingConfigReq struct {
	CityCode      string `json:"cityCode,optional"`
	ChargeEnabled bool   `json:"chargeEnabled"`
	FeeAmount     int64  `json:"feeAmount"`
	Currency      string `json:"currency,optional"`
	FreeEnabled   bool   `json:"freeEnabled,optional"`
	FreeStartAt   string `json:"freeStartAt,optional"`
	FreeEndAt     string `json:"freeEndAt,optional"`
	Notice        string `json:"notice,optional"`
}

type AdminVerificationBillingConfigResp struct {
	CityCode      string `json:"cityCode"`
	ChargeEnabled bool   `json:"chargeEnabled"`
	FeeAmount     int64  `json:"feeAmount"`
	Currency      string `json:"currency"`
	FreeEnabled   bool   `json:"freeEnabled"`
	FreeStartAt   string `json:"freeStartAt,optional"`
	FreeEndAt     string `json:"freeEndAt,optional"`
	Notice        string `json:"notice,optional"`
	UpdatedAt     string `json:"updatedAt,optional"`
}

type AuthUserInfo struct {
	Id              string   `json:"id"`
	Nickname        string   `json:"nickname,optional"`
	AvatarUrl       string   `json:"avatarUrl,optional"`
	DefaultCityCode string   `json:"defaultCityCode,optional"`
	Roles           []string `json:"roles"`
}

type BindPhoneReq struct {
	Phone   string `json:"phone"`
	SmsCode string `json:"smsCode"`
}

type BindPhoneResp struct {
	Id    string `json:"id"`
	Phone string `json:"phone"`
}

type BindWechatPhoneReq struct {
	Code string `json:"code"`
}

type CityStationInfo struct {
	Id              string `json:"id"`
	Code            string `json:"code"`
	Name            string `json:"name"`
	PrimaryCategory string `json:"primaryCategory,optional"`
	Status          string `json:"status"`
}

type ContactEventReq struct {
	Action string `json:"action"`
}

type ContactEventResp struct {
	Message string `json:"message"`
	Action  string `json:"action,optional"`
	Phone   string `json:"phone,optional"`
	Wechat  string `json:"wechat,optional"`
}

type CreateContactUnlockOrderReq struct {
	Action           string `json:"action,optional"`
	ViewerMerchantId string `json:"viewerMerchantId,optional"`
}

type CreateContactUnlockOrderResp struct {
	OrderId         string `json:"orderId,optional"`
	Status          string `json:"status"`
	AlreadyUnlocked bool   `json:"alreadyUnlocked"`
	PriceCent       int64  `json:"priceCent"`
	Currency        string `json:"currency"`
	Message         string `json:"message"`
}

type CreateContactUnlockPaymentReq struct {
	UserId string `json:"userId,optional"`
}

type CreateContactUnlockPaymentResp struct {
	OrderId string          `json:"orderId"`
	Status  string          `json:"status"`
	Payment WechatPayParams `json:"payment"`
}

type CreateMerchantReq struct {
	CityCode       string   `json:"cityCode"`
	Name           string   `json:"name"`
	MerchantType   string   `json:"merchantType"`
	MainCategories []string `json:"mainCategories"`
	ContactName    string   `json:"contactName,optional"`
	ContactPhone   string   `json:"contactPhone,optional"`
	ContactWechat  string   `json:"contactWechat,optional"`
	AddressText    string   `json:"addressText,optional"`
	Description    string   `json:"description,optional"`
}

type CreateMerchantResp struct {
	Id                 string `json:"id"`
	MerchantNo         string `json:"merchantNo,optional"`
	Name               string `json:"name"`
	VerificationStatus string `json:"verificationStatus"`
	Status             string `json:"status"`
}

type CreateResourceReq struct {
	MerchantId   string                 `json:"merchantId"`
	CityCode     string                 `json:"cityCode"`
	TypeCode     string                 `json:"typeCode"`
	Direction    string                 `json:"direction,optional"`
	Title        string                 `json:"title"`
	Category     string                 `json:"category"`
	District     string                 `json:"district,optional"`
	PriceText    string                 `json:"priceText,optional"`
	QuantityText string                 `json:"quantityText,optional"`
	Description  string                 `json:"description"`
	Attributes   map[string]interface{} `json:"attributes,optional"`
	Tags         []string               `json:"tags,optional"`
	Images       []string               `json:"images,optional"`
	Contact      ResourceContactReq     `json:"contact"`
}

type CreateResourceResp struct {
	Id      string `json:"id"`
	Status  string `json:"status"`
	Message string `json:"message"`
}

type CreateSavedSearchReq struct {
	Name         string `json:"name,optional"`
	CityCode     string `json:"cityCode,optional"`
	TypeCode     string `json:"typeCode,optional"`
	Keyword      string `json:"keyword,optional"`
	Category     string `json:"category,optional"`
	VerifiedOnly bool   `json:"verifiedOnly,optional"`
}

type CreateUploadTokenReq struct {
	Purpose     string `json:"purpose"`
	FileName    string `json:"fileName"`
	ContentType string `json:"contentType"`
	FileSize    int64  `json:"fileSize"`
}

type CreateUploadTokenResp struct {
	UploadToken   string `json:"uploadToken"`
	UploadUrl     string `json:"uploadUrl"`
	PublicBaseUrl string `json:"publicBaseUrl"`
	ObjectKey     string `json:"objectKey"`
	ExpiresAt     string `json:"expiresAt"`
}

type CreateVIPOrderReq struct {
	ProductType string `json:"productType,optional"`
	ProductCode string `json:"productCode,optional"`
	PlanCode    string `json:"planCode,optional"`
	ResourceId  string `json:"resourceId,optional"`
}

type CreateVIPOrderResp struct {
	OrderId           string         `json:"orderId"`
	Status            string         `json:"status"`
	ProductType       string         `json:"productType,optional"`
	ProductCode       string         `json:"productCode,optional"`
	ProductName       string         `json:"productName,optional"`
	PlanCode          string         `json:"planCode,optional"`
	PlanName          string         `json:"planName,optional"`
	StandardPriceCent int64          `json:"standardPriceCent"`
	ActualPriceCent   int64          `json:"actualPriceCent"`
	PromotionCode     string         `json:"promotionCode,optional"`
	Benefits          VIPBenefitInfo `json:"benefits"`
}

type CreateVIPPaymentReq struct {
}

type CreateVIPPaymentResp struct {
	OrderId string          `json:"orderId"`
	Status  string          `json:"status"`
	Payment WechatPayParams `json:"payment"`
}

type CreateVerificationPaymentReq struct {
}

type CreateVerificationPaymentResp struct {
	OrderId string          `json:"orderId"`
	Status  string          `json:"status"`
	Payment WechatPayParams `json:"payment"`
}

type CreditTagInfo struct {
	Code  string `json:"code"`
	Label string `json:"label"`
}

type DealFeedbackReq struct {
	IsDealt                 bool   `json:"isDealt"`
	IsReal                  bool   `json:"isReal,optional"`
	ResponseTimely          bool   `json:"responseTimely,optional"`
	WillingToCooperateAgain bool   `json:"willingToCooperateAgain,optional"`
	Note                    string `json:"note,optional"`
}

type DealFeedbackResp struct {
	Id      string `json:"id"`
	Status  string `json:"status"`
	Message string `json:"message"`
}

type DeleteSavedSearchResp struct {
	Message string `json:"message"`
}

type DeleteTakenDownResourceReq struct {
	MerchantId string `json:"merchantId,optional"`
}

type DeleteTakenDownResourceResp struct {
	Id      string `json:"id"`
	Status  string `json:"status"`
	Message string `json:"message"`
}

type DetailViewResp struct {
	Message string `json:"message"`
}

type EditableResourceContact struct {
	Name   string `json:"name"`
	Phone  string `json:"phone"`
	Wechat string `json:"wechat,optional"`
}

type EditableResourceResp struct {
	Id           string                  `json:"id"`
	MerchantId   string                  `json:"merchantId"`
	CityCode     string                  `json:"cityCode"`
	TypeCode     string                  `json:"typeCode"`
	Direction    string                  `json:"direction"`
	Status       string                  `json:"status"`
	Title        string                  `json:"title"`
	Category     string                  `json:"category"`
	District     string                  `json:"district,optional"`
	PriceText    string                  `json:"priceText,optional"`
	QuantityText string                  `json:"quantityText,optional"`
	Description  string                  `json:"description"`
	Attributes   map[string]interface{}  `json:"attributes"`
	Tags         []string                `json:"tags"`
	Images       []string                `json:"images"`
	Contact      EditableResourceContact `json:"contact"`
	RejectReason string                  `json:"rejectReason,optional"`
}

type EntitlementUsageRecordInfo struct {
	Id                    string `json:"id"`
	EntitlementId         string `json:"entitlementId"`
	EntitlementType       string `json:"entitlementType"`
	ActionType            string `json:"actionType"`
	Amount                int64  `json:"amount"`
	ResourceId            string `json:"resourceId,optional"`
	BeforeRemainingAmount int64  `json:"beforeRemainingAmount"`
	AfterRemainingAmount  int64  `json:"afterRemainingAmount"`
	UsedAt                string `json:"usedAt"`
}

type FollowedMerchantItem struct {
	Id                 string   `json:"id"`
	Name               string   `json:"name"`
	MerchantType       string   `json:"merchantType"`
	VerificationStatus string   `json:"verificationStatus"`
	MainCategories     []string `json:"mainCategories"`
	LogoUrl            string   `json:"logoUrl,optional"`
	FollowedAt         string   `json:"followedAt"`
}

type HomeBannerItem struct {
	Id         string   `json:"id"`
	Title      string   `json:"title"`
	Subtitle   string   `json:"subtitle,optional"`
	CoverUrl   string   `json:"coverUrl,optional"`
	JumpType   string   `json:"jumpType"`
	JumpTarget string   `json:"jumpTarget"`
	Tags       []string `json:"tags"`
}

type HomeOperationConfigReq struct {
	CityCode string `form:"cityCode,optional"`
}

type HomeOperationConfigResp struct {
	Banners        []HomeBannerItem        `json:"banners"`
	RecommendCards []HomeRecommendCardItem `json:"recommendCards"`
}

type HomeRecommendCardItem struct {
	Id         string `json:"id"`
	Tag        string `json:"tag,optional"`
	Title      string `json:"title"`
	Subtitle   string `json:"subtitle,optional"`
	JumpType   string `json:"jumpType"`
	JumpTarget string `json:"jumpTarget"`
}

type HomeResourceItem struct {
	Id           string                    `json:"id"`
	Direction    string                    `json:"direction"`
	TypeCode     string                    `json:"typeCode"`
	TypeName     string                    `json:"typeName,optional"`
	Title        string                    `json:"title"`
	Category     string                    `json:"category"`
	District     string                    `json:"district,optional"`
	PriceText    string                    `json:"priceText,optional"`
	QuantityText string                    `json:"quantityText,optional"`
	Merchant     HomeResourceMerchantBrief `json:"merchant"`
	CreditTags   []string                  `json:"creditTags"`
	RefreshedAt  string                    `json:"refreshedAt,optional"`
}

type HomeResourceMerchantBrief struct {
	Id                 string `json:"id"`
	Name               string `json:"name"`
	VerificationStatus string `json:"verificationStatus"`
	VipStatus          string `json:"vipStatus"`
}

type HomeResourcesReq struct {
	CityCode string `form:"cityCode,optional"`
}

type HomeResourcesResp struct {
	Items    []HomeResourceItem `json:"items"`
	Page     int64              `json:"page"`
	PageSize int64              `json:"pageSize"`
	Total    int64              `json:"total"`
}

type HotSearchKeywordItem struct {
	Keyword string `json:"keyword"`
}

type HotSearchKeywordsReq struct {
	CityCode string `form:"cityCode,optional"`
}

type HotSearchKeywordsResp struct {
	Items []HotSearchKeywordItem `json:"items"`
}

type LatestVerificationResp struct {
	Id               string                 `json:"id"`
	VerificationType string                 `json:"verificationType"`
	Status           string                 `json:"status"`
	ReviewedAt       string                 `json:"reviewedAt,optional"`
	ExpiresAt        string                 `json:"expiresAt,optional"`
	ReviewNote       string                 `json:"reviewNote,optional"`
	BusinessName     string                 `json:"businessName,optional"`
	LicenseUrl       string                 `json:"licenseUrl,optional"`
	StorefrontUrl    string                 `json:"storefrontUrl,optional"`
	Materials        map[string]interface{} `json:"materials,optional"`
}

type ListCityStationsResp struct {
	Items []CityStationInfo `json:"items"`
}

type ListEntitlementUsageRecordsResp struct {
	Items []EntitlementUsageRecordInfo `json:"items"`
}

type ListFollowedMerchantsResp struct {
	Items    []FollowedMerchantItem `json:"items"`
	Page     int64                  `json:"page"`
	PageSize int64                  `json:"pageSize"`
	Total    int64                  `json:"total"`
}

type ListInteractionReq struct {
	Page     int64 `form:"page,optional"`
	PageSize int64 `form:"pageSize,optional"`
}

type ListMapBindCandidatesReq struct {
	MerchantId string `form:"merchantId"`
	SceneCode  string `form:"sceneCode,optional"`
	Keyword    string `form:"keyword,optional"`
	Limit      int64  `form:"limit,optional"`
}

type ListMapBindCandidatesResp struct {
	Items []MapBindCandidateItem `json:"items"`
}

type ListMapCategoriesReq struct {
	Type string `form:"type,optional"`
}

type ListMapCategoriesResp struct {
	Items []MapCategoryItem `json:"items"`
}

type ListMapObjectsReq struct {
	Types          string `form:"types,optional"`
	Categories     string `form:"categories,optional"`
	ServiceTags    string `form:"serviceTags,optional"`
	PoiServiceTags string `form:"poiServiceTags,optional"`
	Keyword        string `form:"keyword,optional"`
	MinX           string `form:"minX,optional"`
	MinY           string `form:"minY,optional"`
	MaxX           string `form:"maxX,optional"`
	MaxY           string `form:"maxY,optional"`
	Zoom           int64  `form:"zoom,optional"`
}

type ListMapObjectsResp struct {
	SceneCode string          `json:"sceneCode"`
	Items     []MapObjectItem `json:"items"`
	Total     int64           `json:"total"`
}

type ListMapScenesReq struct {
	CityCode   string `form:"cityCode,optional"`
	ParentCode string `form:"parentCode,optional"`
	Type       string `form:"type,optional"`
}

type ListMapScenesResp struct {
	Items []MapSceneItem `json:"items"`
}

type ListMerchantEntitlementsResp struct {
	Items []MerchantEntitlementInfo `json:"items"`
}

type ListMessagesReq struct {
	Type     string `form:"type,optional"`
	Status   string `form:"status,optional"`
	Page     int64  `form:"page,optional"`
	PageSize int64  `form:"pageSize,optional"`
}

type ListMessagesResp struct {
	Items    []MessageListItem `json:"items"`
	Page     int64             `json:"page"`
	PageSize int64             `json:"pageSize"`
	Total    int64             `json:"total"`
}

type ListMyResourcesReq struct {
	MerchantId string `form:"merchantId"`
	Status     string `form:"status,optional"`
	Direction  string `form:"direction,optional"`
	Page       int64  `form:"page,optional"`
	PageSize   int64  `form:"pageSize,optional"`
}

type ListMyResourcesResp struct {
	Items    []MyResourceItem `json:"items"`
	Page     int64            `json:"page"`
	PageSize int64            `json:"pageSize"`
	Total    int64            `json:"total"`
}

type ListNearbyPoisReq struct {
	Types string `form:"types,optional"`
	Limit int64  `form:"limit,optional"`
}

type ListNearbyPoisResp struct {
	Items []NearbyPoiItem `json:"items"`
}

type ListQuotaPacksResp struct {
	Items []QuotaPackInfo `json:"items"`
}

type ListResourceTypesReq struct {
	Direction string `form:"direction,optional"`
}

type ListResourceTypesResp struct {
	Items []ResourceTypeConfigInfo `json:"items"`
}

type ListResourcesReq struct {
	CityCode     string `form:"cityCode,optional"`
	MerchantId   string `form:"merchantId,optional"`
	GroupCode    string `form:"groupCode,optional"`
	TypeCode     string `form:"typeCode,optional"`
	Direction    string `form:"direction,optional"`
	Keyword      string `form:"keyword,optional"`
	Category     string `form:"category,optional"`
	Tags         string `form:"tags,optional"`
	VerifiedOnly bool   `form:"verifiedOnly,optional"`
	Page         int64  `form:"page,optional"`
	PageSize     int64  `form:"pageSize,optional"`
}

type ListResourcesResp struct {
	Items    []ResourceListItem `json:"items"`
	Page     int64              `json:"page"`
	PageSize int64              `json:"pageSize"`
	Total    int64              `json:"total"`
}

type ListSavedSearchesResp struct {
	Items    []SavedSearchItem `json:"items"`
	Page     int64             `json:"page"`
	PageSize int64             `json:"pageSize"`
	Total    int64             `json:"total"`
}

type ListTopVouchersResp struct {
	Items []TopVoucherInfo `json:"items"`
}

type ListVIPPlansResp struct {
	Items []VIPPlanInfo `json:"items"`
}

type ManagedMerchantInfo struct {
	Id            string `json:"id"`
	Name          string `json:"name"`
	Role          string `json:"role"`
	ProfileStatus string `json:"profileStatus"`
}

type MapBindCandidateItem struct {
	ObjectId     string `json:"objectId"`
	SceneCode    string `json:"sceneCode"`
	SceneName    string `json:"sceneName"`
	Code         string `json:"code"`
	Name         string `json:"name"`
	Address      string `json:"address,optional"`
	MerchantId   string `json:"merchantId,optional"`
	MerchantName string `json:"merchantName,optional"`
	IsBound      bool   `json:"isBound"`
}

type MapBindRequestItem struct {
	Id              string   `json:"id"`
	MerchantId      string   `json:"merchantId"`
	MerchantName    string   `json:"merchantName,optional"`
	ObjectId        string   `json:"objectId"`
	SceneCode       string   `json:"sceneCode"`
	SceneName       string   `json:"sceneName,optional"`
	ObjectCode      string   `json:"objectCode,optional"`
	ObjectName      string   `json:"objectName,optional"`
	ApplicantUserId string   `json:"applicantUserId,optional"`
	EvidenceImages  []string `json:"evidenceImages"`
	Note            string   `json:"note,optional"`
	Status          string   `json:"status"`
	ReviewNote      string   `json:"reviewNote,optional"`
	ReviewedBy      string   `json:"reviewedBy,optional"`
	ReviewedAt      string   `json:"reviewedAt,optional"`
	CreatedAt       string   `json:"createdAt"`
}

type MapBindingStatusResp struct {
	BoundObject   *MapBindCandidateItem `json:"boundObject,optional"`
	LatestRequest *MapBindRequestItem   `json:"latestRequest,optional"`
}

type MapCategoryItem struct {
	Code      string `json:"code"`
	Name      string `json:"name"`
	Type      string `json:"type"`
	IconUrl   string `json:"iconUrl,optional"`
	Sort      int64  `json:"sort"`
	IsVisible bool   `json:"isVisible"`
	Status    string `json:"status"`
}

type MapGeometry struct {
	Type string                 `json:"type"`
	Data map[string]interface{} `json:"data"`
}

type MapObjectDetailResp struct {
	Item MapObjectItem `json:"item"`
}

type MapObjectItem struct {
	Id                 string                 `json:"id"`
	SceneCode          string                 `json:"sceneCode"`
	MerchantId         string                 `json:"merchantId,optional"`
	Code               string                 `json:"code"`
	Name               string                 `json:"name"`
	Type               string                 `json:"type"`
	Layer              string                 `json:"layer"`
	DisplaySource      string                 `json:"displaySource"`
	DisplayLevel       string                 `json:"displayLevel"`
	IsVerifiedMerchant bool                   `json:"isVerifiedMerchant"`
	Merchant           *MapObjectMerchantItem `json:"merchant,optional"`
	GeometryType       string                 `json:"geometryType"`
	Geometry           map[string]interface{} `json:"geometry"`
	CenterX            string                 `json:"centerX,optional"`
	CenterY            string                 `json:"centerY,optional"`
	MinZoom            int64                  `json:"minZoom,optional"`
	MaxZoom            int64                  `json:"maxZoom,optional"`
	CategoryCodes      []string               `json:"categoryCodes"`
	ServiceTags        []string               `json:"serviceTags"`
	PlatformTags       []string               `json:"platformTags"`
	PoiServiceTags     []string               `json:"poiServiceTags"`
	Address            string                 `json:"address,optional"`
	Phone              string                 `json:"phone,optional"`
	Wechat             string                 `json:"wechat,optional"`
	Lat                string                 `json:"lat,optional"`
	Lng                string                 `json:"lng,optional"`
	Extra              map[string]interface{} `json:"extra"`
	Status             string                 `json:"status"`
}

type MapObjectMerchantItem struct {
	Id                 string   `json:"id"`
	Name               string   `json:"name"`
	MerchantType       string   `json:"merchantType"`
	VerificationStatus string   `json:"verificationStatus"`
	LogoUrl            string   `json:"logoUrl,optional"`
	MainCategories     []string `json:"mainCategories"`
}

type MapSceneItem struct {
	Code           string `json:"code"`
	Name           string `json:"name"`
	Type           string `json:"type"`
	ParentCode     string `json:"parentCode,optional"`
	BackgroundUrl  string `json:"backgroundUrl,optional"`
	Width          int64  `json:"width,optional"`
	Height         int64  `json:"height,optional"`
	DefaultScale   string `json:"defaultScale,optional"`
	DefaultCenterX string `json:"defaultCenterX,optional"`
	DefaultCenterY string `json:"defaultCenterY,optional"`
	FloorNo        string `json:"floorNo,optional"`
	Sort           int64  `json:"sort"`
	Status         string `json:"status"`
}

type MapSceneResp struct {
	Item MapSceneItem `json:"item"`
}

type MeResp struct {
	Id               string                `json:"id"`
	Phone            string                `json:"phone,optional"`
	Nickname         string                `json:"nickname,optional"`
	DefaultCityCode  string                `json:"defaultCityCode,optional"`
	Roles            []string              `json:"roles"`
	ManagedMerchants []ManagedMerchantInfo `json:"managedMerchants"`
}

type MerchantContactInfo struct {
	Name         string `json:"name"`
	Phone        string `json:"phone,optional"`
	Wechat       string `json:"wechat,optional"`
	PhoneMasked  string `json:"phoneMasked"`
	WechatMasked string `json:"wechatMasked,optional"`
}

type MerchantDetailResp struct {
	Id                 string                   `json:"id"`
	MerchantNo         string                   `json:"merchantNo"`
	Name               string                   `json:"name"`
	MerchantType       string                   `json:"merchantType"`
	CityCode           string                   `json:"cityCode"`
	MainCategories     []string                 `json:"mainCategories"`
	ProfileStatus      string                   `json:"profileStatus"`
	VerificationStatus string                   `json:"verificationStatus"`
	VipStatus          string                   `json:"vipStatus"`
	VerificationInfo   MerchantVerificationInfo `json:"verificationInfo,optional"`
	CreditTags         []CreditTagInfo          `json:"creditTags"`
	Contact            MerchantContactInfo      `json:"contact"`
	ResourcesSummary   MerchantResourcesSummary `json:"resourcesSummary"`
	HeatScore          int64                    `json:"heatScore"`
	AddressText        string                   `json:"addressText,optional"`
	Location           map[string]interface{}   `json:"location,optional"`
	Description        string                   `json:"description,optional"`
	LogoUrl            string                   `json:"logoUrl,optional"`
	Images             []string                 `json:"images,optional"`
	LastActiveAt       string                   `json:"lastActiveAt,optional"`
}

type MerchantEntitlementInfo struct {
	Id               string   `json:"id"`
	Type             string   `json:"type"`
	SourceType       string   `json:"sourceType"`
	Status           string   `json:"status"`
	TotalAmount      int64    `json:"totalAmount"`
	UsedAmount       int64    `json:"usedAmount"`
	RemainingAmount  int64    `json:"remainingAmount"`
	TopDurationHours int64    `json:"topDurationHours,optional"`
	AllowedTypeCodes []string `json:"allowedTypeCodes,optional"`
	ExpiresAt        string   `json:"expiresAt,optional"`
}

type MerchantFollowStateResp struct {
	MerchantId string `json:"merchantId"`
	Followed   bool   `json:"followed"`
}

type MerchantLast7DaysMetrics struct {
	ExposureCount     int64 `json:"exposureCount"`
	DetailViewCount   int64 `json:"detailViewCount"`
	ContactClickCount int64 `json:"contactClickCount"`
}

type MerchantMetricsSummaryResp struct {
	MerchantId             string                   `json:"merchantId"`
	PublishedResourceCount int64                    `json:"publishedResourceCount"`
	ExpiringResourceCount  int64                    `json:"expiringResourceCount"`
	DealtResourceCount     int64                    `json:"dealtResourceCount"`
	Last7Days              MerchantLast7DaysMetrics `json:"last7Days"`
}

type MerchantResourcesSummary struct {
	PublishedCount int64 `json:"publishedCount"`
	DealtCount     int64 `json:"dealtCount"`
}

type MerchantVIPResp struct {
	MerchantId            string `json:"merchantId"`
	Status                string `json:"status"`
	PlanCode              string `json:"planCode,optional"`
	PlanName              string `json:"planName,optional"`
	StartsAt              string `json:"startsAt,optional"`
	ExpiresAt             string `json:"expiresAt,optional"`
	PublishQuotaRemaining int64  `json:"publishQuotaRemaining"`
	RefreshQuotaRemaining int64  `json:"refreshQuotaRemaining"`
	TopVoucherCount       int64  `json:"topVoucherCount"`
}

type MerchantVerificationInfo struct {
	Status       string   `json:"status"`
	Type         string   `json:"type"`
	ReviewedAt   string   `json:"reviewedAt,optional"`
	ExpiresAt    string   `json:"expiresAt,optional"`
	CheckedItems []string `json:"checkedItems"`
}

type MessageListItem struct {
	Id          string `json:"id"`
	MessageType string `json:"messageType"`
	TriggerId   string `json:"triggerId,optional"`
	Title       string `json:"title"`
	Content     string `json:"content"`
	TargetUrl   string `json:"targetUrl,optional"`
	Status      string `json:"status"`
	CreatedAt   string `json:"createdAt"`
}

type MyResourceItem struct {
	Id           string            `json:"id"`
	Direction    string            `json:"direction"`
	TypeCode     string            `json:"typeCode"`
	TypeName     string            `json:"typeName,optional"`
	Title        string            `json:"title"`
	Category     string            `json:"category"`
	CoverUrl     string            `json:"coverUrl,optional"`
	Status       string            `json:"status"`
	RejectReason string            `json:"rejectReason,optional"`
	PublishedAt  string            `json:"publishedAt,optional"`
	ExpiresAt    string            `json:"expiresAt,optional"`
	DealtAt      string            `json:"dealtAt,optional"`
	Metrics      MyResourceMetrics `json:"metrics"`
}

type MyResourceMetrics struct {
	ExposureCount   int64 `json:"exposureCount"`
	DetailViewCount int64 `json:"detailViewCount"`
	PhoneClickCount int64 `json:"phoneClickCount"`
	WechatCopyCount int64 `json:"wechatCopyCount"`
}

type NearbyPoiItem struct {
	Id           string `json:"id"`
	Name         string `json:"name"`
	Type         string `json:"type"`
	DistanceText string `json:"distanceText"`
	CenterX      string `json:"centerX,optional"`
	CenterY      string `json:"centerY,optional"`
}

type QuotaPackInfo struct {
	Code              string         `json:"code"`
	Name              string         `json:"name"`
	Description       string         `json:"description"`
	StandardPriceCent int64          `json:"standardPriceCent"`
	SalePriceCent     int64          `json:"salePriceCent,optional"`
	SaleLabel         string         `json:"saleLabel,optional"`
	Benefits          VIPBenefitInfo `json:"benefits"`
}

type ReadMessageReq struct {
}

type ReadMessageResp struct {
	Id     string `json:"id"`
	Status string `json:"status"`
}

type RedeemTopVoucherReq struct {
	MerchantId string `json:"merchantId,optional"`
	ResourceId string `json:"resourceId"`
}

type RedeemTopVoucherResp struct {
	VoucherId    string `json:"voucherId"`
	ResourceId   string `json:"resourceId"`
	Status       string `json:"status"`
	TopExpiresAt string `json:"topExpiresAt,optional"`
	Message      string `json:"message"`
}

type RefreshResourceResp struct {
	Id                    string `json:"id"`
	RefreshedAt           string `json:"refreshedAt"`
	RemainingRefreshQuota int64  `json:"remainingRefreshQuota"`
}

type ReportResourceReq struct {
	ReasonCode string                 `json:"reasonCode"`
	ReasonText string                 `json:"reasonText,optional"`
	Evidence   map[string]interface{} `json:"evidence,optional"`
}

type ReportResourceResp struct {
	Id      string `json:"id"`
	Status  string `json:"status"`
	Message string `json:"message"`
}

type RepostSimilarResp struct {
	Id      string `json:"id"`
	Status  string `json:"status"`
	Message string `json:"message"`
}

type ResourceAttributeItem struct {
	Key   string `json:"key"`
	Label string `json:"label"`
	Value string `json:"value"`
}

type ResourceContactAccess struct {
	Mode             string `json:"mode"`
	PriceCent        int64  `json:"priceCent"`
	Currency         string `json:"currency"`
	VipFree          bool   `json:"vipFree"`
	RepeatUnlockDays int64  `json:"repeatUnlockDays"`
	Unlocked         bool   `json:"unlocked"`
	ActionText       string `json:"actionText"`
}

type ResourceContactMasked struct {
	Name         string `json:"name"`
	PhoneMasked  string `json:"phoneMasked"`
	WechatMasked string `json:"wechatMasked,optional"`
}

type ResourceContactReq struct {
	Name   string `json:"name"`
	Phone  string `json:"phone"`
	Wechat string `json:"wechat,optional"`
}

type ResourceDetailResp struct {
	Id             string                  `json:"id"`
	Status         string                  `json:"status"`
	TypeCode       string                  `json:"typeCode"`
	Direction      string                  `json:"direction"`
	TypeName       string                  `json:"typeName,optional"`
	Title          string                  `json:"title"`
	Category       string                  `json:"category"`
	Description    string                  `json:"description"`
	PriceText      string                  `json:"priceText,optional"`
	QuantityText   string                  `json:"quantityText,optional"`
	Attributes     map[string]interface{}  `json:"attributes"`
	AttributeItems []ResourceAttributeItem `json:"attributeItems"`
	Tags           []string                `json:"tags"`
	Images         []string                `json:"images"`
	Merchant       ResourceMerchantBrief   `json:"merchant"`
	Contact        ResourceContactMasked   `json:"contact"`
	ContactAccess  ResourceContactAccess   `json:"contactAccess"`
	PublishedAt    string                  `json:"publishedAt,optional"`
	ExpiresAt      string                  `json:"expiresAt,optional"`
}

type ResourceFavoriteStateResp struct {
	ResourceId string `json:"resourceId"`
	Favorited  bool   `json:"favorited"`
}

type ResourceListItem struct {
	Id           string                `json:"id"`
	Direction    string                `json:"direction"`
	TypeCode     string                `json:"typeCode"`
	TypeName     string                `json:"typeName,optional"`
	Title        string                `json:"title"`
	Category     string                `json:"category"`
	District     string                `json:"district,optional"`
	PriceText    string                `json:"priceText,optional"`
	QuantityText string                `json:"quantityText,optional"`
	Tags         []string              `json:"tags"`
	Merchant     ResourceMerchantBrief `json:"merchant"`
	CreditTags   []string              `json:"creditTags"`
	RefreshedAt  string                `json:"refreshedAt,optional"`
}

type ResourceMerchantBrief struct {
	Id                 string `json:"id"`
	Name               string `json:"name"`
	VerificationStatus string `json:"verificationStatus"`
	VipStatus          string `json:"vipStatus"`
}

type ResourceMetricsDailyItem struct {
	Date            string `json:"date"`
	ExposureCount   int64  `json:"exposureCount"`
	DetailViewCount int64  `json:"detailViewCount"`
	PhoneClickCount int64  `json:"phoneClickCount"`
	WechatCopyCount int64  `json:"wechatCopyCount"`
}

type ResourceMetricsReq struct {
	From string `form:"from,optional"`
	To   string `form:"to,optional"`
}

type ResourceMetricsResp struct {
	ResourceId string                     `json:"resourceId"`
	Summary    ResourceMetricsSummary     `json:"summary"`
	Daily      []ResourceMetricsDailyItem `json:"daily"`
}

type ResourceMetricsSummary struct {
	ExposureCount     int64 `json:"exposureCount"`
	DetailViewCount   int64 `json:"detailViewCount"`
	PhoneClickCount   int64 `json:"phoneClickCount"`
	WechatCopyCount   int64 `json:"wechatCopyCount"`
	DealFeedbackCount int64 `json:"dealFeedbackCount"`
}

type ResourceTypeConfigInfo struct {
	Id               string                 `json:"id"`
	TypeCode         string                 `json:"typeCode"`
	TypeName         string                 `json:"typeName"`
	Direction        string                 `json:"direction"`
	DefaultValidDays int64                  `json:"defaultValidDays"`
	FieldSchema      map[string]interface{} `json:"fieldSchema"`
	RequiredFields   []string               `json:"requiredFields"`
	FilterFields     []string               `json:"filterFields"`
	DisplayTemplate  map[string]interface{} `json:"displayTemplate"`
}

type ReverseGeocodeReq struct {
	Latitude  string `form:"latitude"`
	Longitude string `form:"longitude"`
}

type ReverseGeocodeResp struct {
	Address  string `json:"address"`
	Name     string `json:"name,optional"`
	Province string `json:"province,optional"`
}

type SavedSearchItem struct {
	Id           string `json:"id"`
	Name         string `json:"name"`
	CityCode     string `json:"cityCode"`
	TypeCode     string `json:"typeCode"`
	Keyword      string `json:"keyword"`
	Category     string `json:"category"`
	VerifiedOnly bool   `json:"verifiedOnly"`
	CreatedAt    string `json:"createdAt"`
}

type SavedSearchResp struct {
	Id string `json:"id"`
}

type SearchMapObjectsReq struct {
	SceneCode      string `form:"sceneCode,optional"`
	Keyword        string `form:"keyword,optional"`
	Types          string `form:"types,optional"`
	Categories     string `form:"categories,optional"`
	ServiceTags    string `form:"serviceTags,optional"`
	PoiServiceTags string `form:"poiServiceTags,optional"`
	MinX           string `form:"minX,optional"`
	MinY           string `form:"minY,optional"`
	MaxX           string `form:"maxX,optional"`
	MaxY           string `form:"maxY,optional"`
	Zoom           int64  `form:"zoom,optional"`
	Limit          int64  `form:"limit,optional"`
}

type SearchMapObjectsResp struct {
	Items []MapObjectItem `json:"items"`
	Total int64           `json:"total"`
}

type SearchResourcesReq struct {
	CityCode     string `form:"cityCode,optional"`
	GroupCode    string `form:"groupCode,optional"`
	TypeCode     string `form:"typeCode,optional"`
	Direction    string `form:"direction,optional"`
	Keyword      string `form:"keyword,optional"`
	Category     string `form:"category,optional"`
	Tags         string `form:"tags,optional"`
	VerifiedOnly bool   `form:"verifiedOnly,optional"`
	Page         int64  `form:"page,optional"`
	PageSize     int64  `form:"pageSize,optional"`
}

type SendSMSCodeReq struct {
	Phone string `json:"phone"`
}

type SendSMSCodeResp struct {
	Message string `json:"message"`
}

type SetMerchantFollowReq struct {
	Followed bool `json:"followed"`
}

type SetResourceFavoriteReq struct {
	Favorited bool `json:"favorited"`
}

type SubmitMapBindRequestReq struct {
	ObjectId       string   `json:"objectId"`
	Note           string   `json:"note,optional"`
	EvidenceImages []string `json:"evidenceImages,optional"`
}

type SubmitMapBindRequestResp struct {
	Item MapBindRequestItem `json:"item"`
}

type SubmitResourceReq struct {
	MerchantId string `json:"merchantId,optional"`
}

type SubmitResourceResp struct {
	Id      string `json:"id"`
	Status  string `json:"status"`
	Message string `json:"message"`
}

type SubmitVerificationReq struct {
	VerificationType string                 `json:"verificationType"`
	BusinessName     string                 `json:"businessName,optional"`
	LicenseUrl       string                 `json:"licenseUrl,optional"`
	StorefrontUrl    string                 `json:"storefrontUrl,optional"`
	Materials        map[string]interface{} `json:"materials,optional"`
}

type SubmitVerificationResp struct {
	Id      string `json:"id"`
	Status  string `json:"status"`
	Message string `json:"message"`
}

type TakeDownOwnResourceReq struct {
	Reason string `json:"reason"`
}

type TakeDownOwnResourceResp struct {
	Id      string `json:"id"`
	Status  string `json:"status"`
	Message string `json:"message"`
}

type TopVoucherInfo struct {
	Id               string   `json:"id"`
	Status           string   `json:"status"`
	RemainingAmount  int64    `json:"remainingAmount"`
	TopDurationHours int64    `json:"topDurationHours"`
	AllowedTypeCodes []string `json:"allowedTypeCodes"`
	ExpiresAt        string   `json:"expiresAt,optional"`
}

type TopicInfoResp struct {
	Id       string   `json:"id"`
	Title    string   `json:"title"`
	Subtitle string   `json:"subtitle,optional"`
	CoverUrl string   `json:"coverUrl,optional"`
	Tags     []string `json:"tags"`
}

type TopicResourceItem struct {
	Id           string `json:"id"`
	TypeCode     string `json:"typeCode"`
	Title        string `json:"title"`
	Category     string `json:"category"`
	District     string `json:"district,optional"`
	PriceText    string `json:"priceText,optional"`
	QuantityText string `json:"quantityText,optional"`
	MerchantName string `json:"merchantName"`
}

type TopicResourcesReq struct {
	CityCode string `form:"cityCode,optional"`
	Page     int64  `form:"page,optional"`
	PageSize int64  `form:"pageSize,optional"`
}

type TopicResourcesResp struct {
	Topic    TopicInfoResp       `json:"topic"`
	Items    []TopicResourceItem `json:"items"`
	Page     int64               `json:"page"`
	PageSize int64               `json:"pageSize"`
	Total    int64               `json:"total"`
}

type UpdateMerchantReq struct {
	Name           string                 `json:"name,optional"`
	MainCategories []string               `json:"mainCategories,optional"`
	MerchantType   string                 `json:"merchantType,optional"`
	Description    string                 `json:"description,optional"`
	LogoUrl        string                 `json:"logoUrl,optional"`
	Images         []string               `json:"images,optional"`
	ContactName    string                 `json:"contactName,optional"`
	ContactPhone   string                 `json:"contactPhone,optional"`
	ContactWechat  string                 `json:"contactWechat,optional"`
	AddressText    string                 `json:"addressText,optional"`
	Location       map[string]interface{} `json:"location,optional"`
	SmsCode        string                 `json:"smsCode,optional"`
}

type UpdateMerchantResp struct {
	Id        string `json:"id"`
	UpdatedAt string `json:"updatedAt"`
}

type VIPBenefitInfo struct {
	PublishPolicy      string `json:"publishPolicy"`
	PublishQuota       int64  `json:"publishQuota"`
	RefreshQuota       int64  `json:"refreshQuota"`
	TopVoucherCount    int64  `json:"topVoucherCount"`
	TopDurationHours   int64  `json:"topDurationHours"`
	HomepageImageLimit int64  `json:"homepageImageLimit,optional"`
}

type VIPPlanInfo struct {
	Code              string         `json:"code"`
	Name              string         `json:"name"`
	DurationMonths    int64          `json:"durationMonths"`
	StandardPriceCent int64          `json:"standardPriceCent"`
	SalePriceCent     int64          `json:"salePriceCent,optional"`
	SaleLabel         string         `json:"saleLabel,optional"`
	Benefits          VIPBenefitInfo `json:"benefits"`
}

type ValidateWebviewReq struct {
	Url string `json:"url"`
}

type ValidateWebviewResp struct {
	Allowed bool   `json:"allowed"`
	Url     string `json:"url"`
}

type VerificationBillingConfigResp struct {
	CityCode      string `json:"cityCode"`
	ChargeEnabled bool   `json:"chargeEnabled"`
	FeeAmount     int64  `json:"feeAmount"`
	Currency      string `json:"currency"`
	FreeEnabled   bool   `json:"freeEnabled"`
	FreeStartAt   string `json:"freeStartAt,optional"`
	FreeEndAt     string `json:"freeEndAt,optional"`
	Notice        string `json:"notice,optional"`
	UpdatedAt     string `json:"updatedAt,optional"`
}

type WechatLoginReq struct {
	Code            string `json:"code"`
	DefaultCityCode string `json:"defaultCityCode,optional"`
}

type WechatLoginResp struct {
	Token            string                `json:"token"`
	User             AuthUserInfo          `json:"user"`
	ManagedMerchants []ManagedMerchantInfo `json:"managedMerchants"`
}

type WechatPayParams struct {
	TimeStamp string `json:"timeStamp"`
	NonceStr  string `json:"nonceStr"`
	Package   string `json:"package"`
	SignType  string `json:"signType"`
	PaySign   string `json:"paySign"`
}
