import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import test from 'node:test'

const root = path.resolve(new URL('../..', import.meta.url).pathname)

test('growth entitlement detail page is registered and loads public campaign rules', () => {
  const pagesConfig = JSON.parse(fs.readFileSync(path.join(root, 'pages.json'), 'utf8'))
  const pagePaths = pagesConfig.pages.map((item) => item.path)
  const source = fs.readFileSync(path.join(root, 'pages/my/growth-entitlement.vue'), 'utf8')
  const apiSource = fs.readFileSync(path.join(root, 'api/growthCampaign.js'), 'utf8')

  assert.ok(pagePaths.includes('pages/my/growth-entitlement'))
  assert.match(apiSource, /getActiveGrowthCampaigns/)
  assert.match(apiSource, /\/api\/v1\/growth-campaigns\/active/)
  assert.match(apiSource, /getGrowthTasks/)
  assert.match(apiSource, /\/api\/v1\/merchants\/\$\{merchantId\}\/growth-tasks/)
  assert.match(source, /权益余额/)
  assert.match(source, /新手主线任务/)
  assert.match(source, /每日曝光任务/)
  assert.match(source, /规则说明/)
  assert.match(source, /主线进度/)
  assert.doesNotMatch(source, /class="section-card progress-card"/)
  assert.doesNotMatch(source, /新手成长进度/)
  assert.match(source, /规则说明：达标自动到账/)
  assert.match(source, /getMerchantEntitlements/)
  assert.match(source, /getActiveGrowthCampaigns/)
  assert.match(source, /getGrowthTasks/)
  assert.match(source, /starterTasks/)
  assert.match(source, /dailyTasks/)
  assert.match(source, /taskStatusText/)
  assert.match(source, /openTaskAction/)
  assert.match(source, /发布次数/)
  assert.match(source, /刷新次数/)
  assert.match(source, /联系/)
  assert.match(source, /tasksLoaded/)
  assert.match(source, /growthPageLoadSeq/)
  assert.match(source, /skipNextShowLoad/)
  assert.match(source, /activeCampaign\.value\.hint/)
  assert.match(source, /nearestExpiryText/)
  assert.match(source, /最近到期/)
  assert.match(source, /shouldShowTaskAction/)
  assert.match(source, /请先完善发布者资料/)
  assert.match(source, /当前暂无活动/)
  assert.match(source, /活动规则未开启/)
  assert.match(source, /flex-wrap:\s*wrap/)
  assert.doesNotMatch(source, /可继续获得/)
  assert.doesNotMatch(source, /当前暂无进行中的新手主线任务/)
  assert.doesNotMatch(source, /发布优质资源、有效分享，可获得更多发布和刷新次数/)
  assert.doesNotMatch(source, /权益达标后自动到账，不需要手动领取/)
  assert.doesNotMatch(source, /暂无可参与的新手任务/)
  assert.match(source, /达标自动到账/)
  assert.match(source, /分享需产生有效浏览或联系/)
})
