// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.5

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	adminOperatorProfilesFieldNames          = builder.RawFieldNames(&AdminOperatorProfiles{}, true)
	adminOperatorProfilesRows                = strings.Join(adminOperatorProfilesFieldNames, ",")
	adminOperatorProfilesRowsExpectAutoSet   = strings.Join(stringx.Remove(adminOperatorProfilesFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	adminOperatorProfilesRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(adminOperatorProfilesFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	adminOperatorProfilesModel interface {
		Insert(ctx context.Context, data *AdminOperatorProfiles) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*AdminOperatorProfiles, error)
		FindOneByUserId(ctx context.Context, userId string) (*AdminOperatorProfiles, error)
		Update(ctx context.Context, data *AdminOperatorProfiles) error
		Delete(ctx context.Context, id string) error
	}

	defaultAdminOperatorProfilesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AdminOperatorProfiles struct {
		Id                    string       `db:"id"`
		UserId                string       `db:"user_id"`
		RealName              string       `db:"real_name"`
		ManagedCityStationIds string       `db:"managed_city_station_ids"`
		Status                string       `db:"status"`
		LastLoginAt           sql.NullTime `db:"last_login_at"`
		CreatedAt             time.Time    `db:"created_at"`
		UpdatedAt             time.Time    `db:"updated_at"`
	}
)

func newAdminOperatorProfilesModel(conn sqlx.SqlConn) *defaultAdminOperatorProfilesModel {
	return &defaultAdminOperatorProfilesModel{
		conn:  conn,
		table: `"public"."admin_operator_profiles"`,
	}
}

func (m *defaultAdminOperatorProfilesModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAdminOperatorProfilesModel) FindOne(ctx context.Context, id string) (*AdminOperatorProfiles, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", adminOperatorProfilesRows, m.table)
	var resp AdminOperatorProfiles
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAdminOperatorProfilesModel) FindOneByUserId(ctx context.Context, userId string) (*AdminOperatorProfiles, error) {
	var resp AdminOperatorProfiles
	query := fmt.Sprintf("select %s from %s where user_id = $1 limit 1", adminOperatorProfilesRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAdminOperatorProfilesModel) Insert(ctx context.Context, data *AdminOperatorProfiles) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6)", m.table, adminOperatorProfilesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.UserId, data.RealName, data.ManagedCityStationIds, data.Status, data.LastLoginAt)
	return ret, err
}

func (m *defaultAdminOperatorProfilesModel) Update(ctx context.Context, newData *AdminOperatorProfiles) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, adminOperatorProfilesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.UserId, newData.RealName, newData.ManagedCityStationIds, newData.Status, newData.LastLoginAt)
	return err
}

func (m *defaultAdminOperatorProfilesModel) tableName() string {
	return m.table
}
