// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.5

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	adminLoginCredentialsFieldNames          = builder.RawFieldNames(&AdminLoginCredentials{}, true)
	adminLoginCredentialsRows                = postgresTextIDRows(adminLoginCredentialsFieldNames)
	adminLoginCredentialsRowsExpectAutoSet   = strings.Join(stringx.Remove(adminLoginCredentialsFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	adminLoginCredentialsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(adminLoginCredentialsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	adminLoginCredentialsModel interface {
		Insert(ctx context.Context, data *AdminLoginCredentials) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*AdminLoginCredentials, error)
		FindOneByLoginName(ctx context.Context, loginName string) (*AdminLoginCredentials, error)
		FindOneByUserId(ctx context.Context, userId string) (*AdminLoginCredentials, error)
		Update(ctx context.Context, data *AdminLoginCredentials) error
		Delete(ctx context.Context, id string) error
	}

	defaultAdminLoginCredentialsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AdminLoginCredentials struct {
		Id                string         `db:"id"`
		UserId            string         `db:"user_id"`
		LoginName         string         `db:"login_name"`
		PasswordHash      string         `db:"password_hash"`
		Status            string         `db:"status"`
		FailedAttempts    int64          `db:"failed_attempts"`
		LockedUntil       sql.NullTime   `db:"locked_until"`
		PasswordChangedAt sql.NullTime   `db:"password_changed_at"`
		LastLoginAt       sql.NullTime   `db:"last_login_at"`
		CreatedBy         sql.NullString `db:"created_by"`
		CreatedAt         time.Time      `db:"created_at"`
		UpdatedAt         time.Time      `db:"updated_at"`
	}
)

func newAdminLoginCredentialsModel(conn sqlx.SqlConn) *defaultAdminLoginCredentialsModel {
	return &defaultAdminLoginCredentialsModel{
		conn:  conn,
		table: `"public"."admin_login_credentials"`,
	}
}

func (m *defaultAdminLoginCredentialsModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAdminLoginCredentialsModel) FindOne(ctx context.Context, id string) (*AdminLoginCredentials, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", adminLoginCredentialsRows, m.table)
	var resp AdminLoginCredentials
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAdminLoginCredentialsModel) FindOneByLoginName(ctx context.Context, loginName string) (*AdminLoginCredentials, error) {
	var resp AdminLoginCredentials
	query := fmt.Sprintf("select %s from %s where login_name = $1 limit 1", adminLoginCredentialsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, loginName)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAdminLoginCredentialsModel) FindOneByUserId(ctx context.Context, userId string) (*AdminLoginCredentials, error) {
	var resp AdminLoginCredentials
	query := fmt.Sprintf("select %s from %s where user_id = $1 limit 1", adminLoginCredentialsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAdminLoginCredentialsModel) Insert(ctx context.Context, data *AdminLoginCredentials) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)", m.table, adminLoginCredentialsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.UserId, data.LoginName, data.PasswordHash, data.Status, data.FailedAttempts, data.LockedUntil, data.PasswordChangedAt, data.LastLoginAt, data.CreatedBy)
	return ret, err
}

func (m *defaultAdminLoginCredentialsModel) Update(ctx context.Context, newData *AdminLoginCredentials) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, adminLoginCredentialsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.UserId, newData.LoginName, newData.PasswordHash, newData.Status, newData.FailedAttempts, newData.LockedUntil, newData.PasswordChangedAt, newData.LastLoginAt, newData.CreatedBy)
	return err
}

func (m *defaultAdminLoginCredentialsModel) tableName() string {
	return m.table
}
