// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.5

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	bannerTopicsFieldNames          = builder.RawFieldNames(&BannerTopics{}, true)
	bannerTopicsRows                = postgresTextIDRows(bannerTopicsFieldNames)
	bannerTopicsRowsExpectAutoSet   = strings.Join(stringx.Remove(bannerTopicsFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	bannerTopicsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(bannerTopicsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	bannerTopicsModel interface {
		Insert(ctx context.Context, data *BannerTopics) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*BannerTopics, error)
		Update(ctx context.Context, data *BannerTopics) error
		Delete(ctx context.Context, id string) error
	}

	defaultBannerTopicsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	BannerTopics struct {
		Id            string         `db:"id"`
		CityStationId sql.NullString `db:"city_station_id"`
		Kind          string         `db:"kind"`
		Title         string         `db:"title"`
		Subtitle      sql.NullString `db:"subtitle"`
		CoverUrl      sql.NullString `db:"cover_url"`
		TypeScope     string         `db:"type_scope"`
		JumpType      string         `db:"jump_type"`
		JumpTarget    string         `db:"jump_target"`
		Tags          string         `db:"tags"`
		StartAt       sql.NullTime   `db:"start_at"`
		EndAt         sql.NullTime   `db:"end_at"`
		SortOrder     int64          `db:"sort_order"`
		Status        string         `db:"status"`
		CreatedAt     time.Time      `db:"created_at"`
		UpdatedAt     time.Time      `db:"updated_at"`
	}
)

func newBannerTopicsModel(conn sqlx.SqlConn) *defaultBannerTopicsModel {
	return &defaultBannerTopicsModel{
		conn:  conn,
		table: `"public"."banner_topics"`,
	}
}

func (m *defaultBannerTopicsModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultBannerTopicsModel) FindOne(ctx context.Context, id string) (*BannerTopics, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", bannerTopicsRows, m.table)
	var resp BannerTopics
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBannerTopicsModel) Insert(ctx context.Context, data *BannerTopics) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)", m.table, bannerTopicsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.CityStationId, data.Kind, data.Title, data.Subtitle, data.CoverUrl, data.TypeScope, data.JumpType, data.JumpTarget, data.Tags, data.StartAt, data.EndAt, data.SortOrder, data.Status)
	return ret, err
}

func (m *defaultBannerTopicsModel) Update(ctx context.Context, data *BannerTopics) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, bannerTopicsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.CityStationId, data.Kind, data.Title, data.Subtitle, data.CoverUrl, data.TypeScope, data.JumpType, data.JumpTarget, data.Tags, data.StartAt, data.EndAt, data.SortOrder, data.Status)
	return err
}

func (m *defaultBannerTopicsModel) tableName() string {
	return m.table
}
