// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.5

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	cityStationsFieldNames          = builder.RawFieldNames(&CityStations{}, true)
	cityStationsRows                = postgresTextIDRows(cityStationsFieldNames)
	cityStationsRowsExpectAutoSet   = strings.Join(stringx.Remove(cityStationsFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	cityStationsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(cityStationsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	cityStationsModel interface {
		Insert(ctx context.Context, data *CityStations) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*CityStations, error)
		FindOneByCode(ctx context.Context, code string) (*CityStations, error)
		Update(ctx context.Context, data *CityStations) error
		Delete(ctx context.Context, id string) error
	}

	defaultCityStationsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	CityStations struct {
		Id              string         `db:"id"`
		Code            string         `db:"code"`
		Name            string         `db:"name"`
		Province        sql.NullString `db:"province"`
		City            sql.NullString `db:"city"`
		PrimaryCategory sql.NullString `db:"primary_category"`
		Status          string         `db:"status"`
		Config          string         `db:"config"`
		CreatedAt       time.Time      `db:"created_at"`
		UpdatedAt       time.Time      `db:"updated_at"`
	}
)

func newCityStationsModel(conn sqlx.SqlConn) *defaultCityStationsModel {
	return &defaultCityStationsModel{
		conn:  conn,
		table: `"public"."city_stations"`,
	}
}

func (m *defaultCityStationsModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultCityStationsModel) FindOne(ctx context.Context, id string) (*CityStations, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", cityStationsRows, m.table)
	var resp CityStations
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCityStationsModel) FindOneByCode(ctx context.Context, code string) (*CityStations, error) {
	var resp CityStations
	query := fmt.Sprintf("select %s from %s where code = $1 limit 1", cityStationsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, code)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCityStationsModel) Insert(ctx context.Context, data *CityStations) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8)", m.table, cityStationsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.Code, data.Name, data.Province, data.City, data.PrimaryCategory, data.Status, data.Config)
	return ret, err
}

func (m *defaultCityStationsModel) Update(ctx context.Context, newData *CityStations) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, cityStationsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.Code, newData.Name, newData.Province, newData.City, newData.PrimaryCategory, newData.Status, newData.Config)
	return err
}

func (m *defaultCityStationsModel) tableName() string {
	return m.table
}
