// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.5

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	creditRecordsFieldNames          = builder.RawFieldNames(&CreditRecords{}, true)
	creditRecordsRows                = postgresTextIDRows(creditRecordsFieldNames)
	creditRecordsRowsExpectAutoSet   = strings.Join(stringx.Remove(creditRecordsFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	creditRecordsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(creditRecordsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	creditRecordsModel interface {
		Insert(ctx context.Context, data *CreditRecords) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*CreditRecords, error)
		Update(ctx context.Context, data *CreditRecords) error
		Delete(ctx context.Context, id string) error
	}

	defaultCreditRecordsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	CreditRecords struct {
		Id          string         `db:"id"`
		MerchantId  string         `db:"merchant_id"`
		ResourceId  sql.NullString `db:"resource_id"`
		SourceType  string         `db:"source_type"`
		TagCode     string         `db:"tag_code"`
		TagLabel    string         `db:"tag_label"`
		Description sql.NullString `db:"description"`
		Visibility  string         `db:"visibility"`
		CreatedBy   sql.NullString `db:"created_by"`
		CreatedAt   time.Time      `db:"created_at"`
		RevokedAt   sql.NullTime   `db:"revoked_at"`
	}
)

func newCreditRecordsModel(conn sqlx.SqlConn) *defaultCreditRecordsModel {
	return &defaultCreditRecordsModel{
		conn:  conn,
		table: `"public"."credit_records"`,
	}
}

func (m *defaultCreditRecordsModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultCreditRecordsModel) FindOne(ctx context.Context, id string) (*CreditRecords, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", creditRecordsRows, m.table)
	var resp CreditRecords
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCreditRecordsModel) Insert(ctx context.Context, data *CreditRecords) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)", m.table, creditRecordsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.MerchantId, data.ResourceId, data.SourceType, data.TagCode, data.TagLabel, data.Description, data.Visibility, data.CreatedBy, data.RevokedAt)
	return ret, err
}

func (m *defaultCreditRecordsModel) Update(ctx context.Context, data *CreditRecords) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, creditRecordsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.MerchantId, data.ResourceId, data.SourceType, data.TagCode, data.TagLabel, data.Description, data.Visibility, data.CreatedBy, data.RevokedAt)
	return err
}

func (m *defaultCreditRecordsModel) tableName() string {
	return m.table
}
