// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.5

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	matchCaseParticipantsFieldNames          = builder.RawFieldNames(&MatchCaseParticipants{}, true)
	matchCaseParticipantsRows                = postgresTextIDRows(matchCaseParticipantsFieldNames)
	matchCaseParticipantsRowsExpectAutoSet   = strings.Join(stringx.Remove(matchCaseParticipantsFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	matchCaseParticipantsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(matchCaseParticipantsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	matchCaseParticipantsModel interface {
		Insert(ctx context.Context, data *MatchCaseParticipants) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*MatchCaseParticipants, error)
		Update(ctx context.Context, data *MatchCaseParticipants) error
		Delete(ctx context.Context, id string) error
	}

	defaultMatchCaseParticipantsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	MatchCaseParticipants struct {
		Id              string         `db:"id"`
		MatchCaseId     string         `db:"match_case_id"`
		UserId          sql.NullString `db:"user_id"`
		MerchantId      sql.NullString `db:"merchant_id"`
		ParticipantRole string         `db:"participant_role"`
		ContactStatus   string         `db:"contact_status"`
		CreatedAt       time.Time      `db:"created_at"`
		UpdatedAt       time.Time      `db:"updated_at"`
	}
)

func newMatchCaseParticipantsModel(conn sqlx.SqlConn) *defaultMatchCaseParticipantsModel {
	return &defaultMatchCaseParticipantsModel{
		conn:  conn,
		table: `"public"."match_case_participants"`,
	}
}

func (m *defaultMatchCaseParticipantsModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultMatchCaseParticipantsModel) FindOne(ctx context.Context, id string) (*MatchCaseParticipants, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", matchCaseParticipantsRows, m.table)
	var resp MatchCaseParticipants
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMatchCaseParticipantsModel) Insert(ctx context.Context, data *MatchCaseParticipants) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6)", m.table, matchCaseParticipantsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.MatchCaseId, data.UserId, data.MerchantId, data.ParticipantRole, data.ContactStatus)
	return ret, err
}

func (m *defaultMatchCaseParticipantsModel) Update(ctx context.Context, data *MatchCaseParticipants) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, matchCaseParticipantsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.MatchCaseId, data.UserId, data.MerchantId, data.ParticipantRole, data.ContactStatus)
	return err
}

func (m *defaultMatchCaseParticipantsModel) tableName() string {
	return m.table
}
