// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.5

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	matchCasesFieldNames          = builder.RawFieldNames(&MatchCases{}, true)
	matchCasesRows                = strings.Join(matchCasesFieldNames, ",")
	matchCasesRowsExpectAutoSet   = strings.Join(stringx.Remove(matchCasesFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	matchCasesRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(matchCasesFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	matchCasesModel interface {
		Insert(ctx context.Context, data *MatchCases) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*MatchCases, error)
		Update(ctx context.Context, data *MatchCases) error
		Delete(ctx context.Context, id string) error
	}

	defaultMatchCasesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	MatchCases struct {
		Id               string         `db:"id"`
		PurchaseDemandId sql.NullString `db:"purchase_demand_id"`
		CityStationId    sql.NullString `db:"city_station_id"`
		Status           string         `db:"status"`
		Source           string         `db:"source"`
		OperatorId       sql.NullString `db:"operator_id"`
		ResultNote       sql.NullString `db:"result_note"`
		CreatedAt        time.Time      `db:"created_at"`
		UpdatedAt        time.Time      `db:"updated_at"`
		ClosedAt         sql.NullTime   `db:"closed_at"`
	}
)

func newMatchCasesModel(conn sqlx.SqlConn) *defaultMatchCasesModel {
	return &defaultMatchCasesModel{
		conn:  conn,
		table: `"public"."match_cases"`,
	}
}

func (m *defaultMatchCasesModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultMatchCasesModel) FindOne(ctx context.Context, id string) (*MatchCases, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", matchCasesRows, m.table)
	var resp MatchCases
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMatchCasesModel) Insert(ctx context.Context, data *MatchCases) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8)", m.table, matchCasesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.PurchaseDemandId, data.CityStationId, data.Status, data.Source, data.OperatorId, data.ResultNote, data.ClosedAt)
	return ret, err
}

func (m *defaultMatchCasesModel) Update(ctx context.Context, data *MatchCases) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, matchCasesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.PurchaseDemandId, data.CityStationId, data.Status, data.Source, data.OperatorId, data.ResultNote, data.ClosedAt)
	return err
}

func (m *defaultMatchCasesModel) tableName() string {
	return m.table
}
