// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.5

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	matchCaseResourcesFieldNames          = builder.RawFieldNames(&MatchCaseResources{}, true)
	matchCaseResourcesRows                = strings.Join(matchCaseResourcesFieldNames, ",")
	matchCaseResourcesRowsExpectAutoSet   = strings.Join(stringx.Remove(matchCaseResourcesFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	matchCaseResourcesRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(matchCaseResourcesFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	matchCaseResourcesModel interface {
		Insert(ctx context.Context, data *MatchCaseResources) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*MatchCaseResources, error)
		FindOneByMatchCaseIdResourceId(ctx context.Context, matchCaseId string, resourceId string) (*MatchCaseResources, error)
		Update(ctx context.Context, data *MatchCaseResources) error
		Delete(ctx context.Context, id string) error
	}

	defaultMatchCaseResourcesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	MatchCaseResources struct {
		Id          string    `db:"id"`
		MatchCaseId string    `db:"match_case_id"`
		ResourceId  string    `db:"resource_id"`
		Role        string    `db:"role"`
		CreatedAt   time.Time `db:"created_at"`
	}
)

func newMatchCaseResourcesModel(conn sqlx.SqlConn) *defaultMatchCaseResourcesModel {
	return &defaultMatchCaseResourcesModel{
		conn:  conn,
		table: `"public"."match_case_resources"`,
	}
}

func (m *defaultMatchCaseResourcesModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultMatchCaseResourcesModel) FindOne(ctx context.Context, id string) (*MatchCaseResources, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", matchCaseResourcesRows, m.table)
	var resp MatchCaseResources
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMatchCaseResourcesModel) FindOneByMatchCaseIdResourceId(ctx context.Context, matchCaseId string, resourceId string) (*MatchCaseResources, error) {
	var resp MatchCaseResources
	query := fmt.Sprintf("select %s from %s where match_case_id = $1 and resource_id = $2 limit 1", matchCaseResourcesRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, matchCaseId, resourceId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMatchCaseResourcesModel) Insert(ctx context.Context, data *MatchCaseResources) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4)", m.table, matchCaseResourcesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.MatchCaseId, data.ResourceId, data.Role)
	return ret, err
}

func (m *defaultMatchCaseResourcesModel) Update(ctx context.Context, newData *MatchCaseResources) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, matchCaseResourcesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.MatchCaseId, newData.ResourceId, newData.Role)
	return err
}

func (m *defaultMatchCaseResourcesModel) tableName() string {
	return m.table
}
