// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.5

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	merchantsFieldNames          = builder.RawFieldNames(&Merchants{}, true)
	merchantsRows                = postgresTextIDRows(merchantsFieldNames)
	merchantsRowsExpectAutoSet   = strings.Join(stringx.Remove(merchantsFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	merchantsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(merchantsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	merchantsModel interface {
		Insert(ctx context.Context, data *Merchants) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*Merchants, error)
		Update(ctx context.Context, data *Merchants) error
		Delete(ctx context.Context, id string) error
	}

	defaultMerchantsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Merchants struct {
		Id                 string         `db:"id"`
		CityStationId      string         `db:"city_station_id"`
		Name               string         `db:"name"`
		MerchantType       string         `db:"merchant_type"`
		MainCategories     string         `db:"main_categories"`
		Description        sql.NullString `db:"description"`
		ContactName        string         `db:"contact_name"`
		ContactPhone       string         `db:"contact_phone"`
		ContactWechat      sql.NullString `db:"contact_wechat"`
		AddressText        sql.NullString `db:"address_text"`
		Location           string         `db:"location"`
		Images             string         `db:"images"`
		VerificationStatus string         `db:"verification_status"`
		Status             string         `db:"status"`
		LastActiveAt       sql.NullTime   `db:"last_active_at"`
		CreatedAt          time.Time      `db:"created_at"`
		UpdatedAt          time.Time      `db:"updated_at"`
		DeletedAt          sql.NullTime   `db:"deleted_at"`
	}
)

func newMerchantsModel(conn sqlx.SqlConn) *defaultMerchantsModel {
	return &defaultMerchantsModel{
		conn:  conn,
		table: `"public"."merchants"`,
	}
}

func (m *defaultMerchantsModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultMerchantsModel) FindOne(ctx context.Context, id string) (*Merchants, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", merchantsRows, m.table)
	var resp Merchants
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMerchantsModel) Insert(ctx context.Context, data *Merchants) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)", m.table, merchantsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.CityStationId, data.Name, data.MerchantType, data.MainCategories, data.Description, data.ContactName, data.ContactPhone, data.ContactWechat, data.AddressText, data.Location, data.Images, data.VerificationStatus, data.Status, data.LastActiveAt, data.DeletedAt)
	return ret, err
}

func (m *defaultMerchantsModel) Update(ctx context.Context, data *Merchants) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, merchantsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.CityStationId, data.Name, data.MerchantType, data.MainCategories, data.Description, data.ContactName, data.ContactPhone, data.ContactWechat, data.AddressText, data.Location, data.Images, data.VerificationStatus, data.Status, data.LastActiveAt, data.DeletedAt)
	return err
}

func (m *defaultMerchantsModel) tableName() string {
	return m.table
}
