// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.5

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	merchantEntitlementsFieldNames          = builder.RawFieldNames(&MerchantEntitlements{}, true)
	merchantEntitlementsRows                = postgresTextIDRows(merchantEntitlementsFieldNames)
	merchantEntitlementsRowsExpectAutoSet   = strings.Join(stringx.Remove(merchantEntitlementsFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	merchantEntitlementsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(merchantEntitlementsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	merchantEntitlementsModel interface {
		Insert(ctx context.Context, data *MerchantEntitlements) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*MerchantEntitlements, error)
		Update(ctx context.Context, data *MerchantEntitlements) error
		Delete(ctx context.Context, id string) error
	}

	defaultMerchantEntitlementsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	MerchantEntitlements struct {
		Id              string       `db:"id"`
		MerchantId      string       `db:"merchant_id"`
		EntitlementType string       `db:"entitlement_type"`
		SourceType      string       `db:"source_type"`
		TotalAmount     int64        `db:"total_amount"`
		UsedAmount      int64        `db:"used_amount"`
		RemainingAmount int64        `db:"remaining_amount"`
		StartsAt        time.Time    `db:"starts_at"`
		ExpiresAt       sql.NullTime `db:"expires_at"`
		Status          string       `db:"status"`
		CreatedAt       time.Time    `db:"created_at"`
		UpdatedAt       time.Time    `db:"updated_at"`
	}
)

func newMerchantEntitlementsModel(conn sqlx.SqlConn) *defaultMerchantEntitlementsModel {
	return &defaultMerchantEntitlementsModel{
		conn:  conn,
		table: `"public"."merchant_entitlements"`,
	}
}

func (m *defaultMerchantEntitlementsModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultMerchantEntitlementsModel) FindOne(ctx context.Context, id string) (*MerchantEntitlements, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", merchantEntitlementsRows, m.table)
	var resp MerchantEntitlements
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMerchantEntitlementsModel) Insert(ctx context.Context, data *MerchantEntitlements) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)", m.table, merchantEntitlementsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.MerchantId, data.EntitlementType, data.SourceType, data.TotalAmount, data.UsedAmount, data.RemainingAmount, data.StartsAt, data.ExpiresAt, data.Status)
	return ret, err
}

func (m *defaultMerchantEntitlementsModel) Update(ctx context.Context, data *MerchantEntitlements) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, merchantEntitlementsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.MerchantId, data.EntitlementType, data.SourceType, data.TotalAmount, data.UsedAmount, data.RemainingAmount, data.StartsAt, data.ExpiresAt, data.Status)
	return err
}

func (m *defaultMerchantEntitlementsModel) tableName() string {
	return m.table
}
