// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.5

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	merchantMapEventsFieldNames          = builder.RawFieldNames(&MerchantMapEvents{}, true)
	merchantMapEventsRows                = strings.Join(merchantMapEventsFieldNames, ",")
	merchantMapEventsRowsExpectAutoSet   = strings.Join(stringx.Remove(merchantMapEventsFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	merchantMapEventsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(merchantMapEventsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	merchantMapEventsModel interface {
		Insert(ctx context.Context, data *MerchantMapEvents) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*MerchantMapEvents, error)
		Update(ctx context.Context, data *MerchantMapEvents) error
		Delete(ctx context.Context, id int64) error
	}

	defaultMerchantMapEventsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	MerchantMapEvents struct {
		Id               int64         `db:"id"`
		UserId           sql.NullInt64 `db:"user_id"`
		MerchantId       int64         `db:"merchant_id"`
		TargetMerchantId sql.NullInt64 `db:"target_merchant_id"`
		VisitorKey       string        `db:"visitor_key"`
		SessionId        string        `db:"session_id"`
		EventType        string        `db:"event_type"`
		Source           string        `db:"source"`
		CreatedAt        time.Time     `db:"created_at"`
	}
)

func newMerchantMapEventsModel(conn sqlx.SqlConn) *defaultMerchantMapEventsModel {
	return &defaultMerchantMapEventsModel{
		conn:  conn,
		table: `"public"."merchant_map_events"`,
	}
}

func (m *defaultMerchantMapEventsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultMerchantMapEventsModel) FindOne(ctx context.Context, id int64) (*MerchantMapEvents, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", merchantMapEventsRows, m.table)
	var resp MerchantMapEvents
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMerchantMapEventsModel) Insert(ctx context.Context, data *MerchantMapEvents) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8)", m.table, merchantMapEventsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.UserId, data.MerchantId, data.TargetMerchantId, data.VisitorKey, data.SessionId, data.EventType, data.Source)
	return ret, err
}

func (m *defaultMerchantMapEventsModel) Update(ctx context.Context, data *MerchantMapEvents) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, merchantMapEventsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.UserId, data.MerchantId, data.TargetMerchantId, data.VisitorKey, data.SessionId, data.EventType, data.Source)
	return err
}

func (m *defaultMerchantMapEventsModel) tableName() string {
	return m.table
}
