// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.5

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	merchantAdminBindingsFieldNames          = builder.RawFieldNames(&MerchantAdminBindings{}, true)
	merchantAdminBindingsRows                = postgresTextIDRows(merchantAdminBindingsFieldNames)
	merchantAdminBindingsRowsExpectAutoSet   = strings.Join(stringx.Remove(merchantAdminBindingsFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	merchantAdminBindingsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(merchantAdminBindingsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	merchantAdminBindingsModel interface {
		Insert(ctx context.Context, data *MerchantAdminBindings) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*MerchantAdminBindings, error)
		FindOneByMerchantIdUserId(ctx context.Context, merchantId string, userId string) (*MerchantAdminBindings, error)
		Update(ctx context.Context, data *MerchantAdminBindings) error
		Delete(ctx context.Context, id string) error
	}

	defaultMerchantAdminBindingsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	MerchantAdminBindings struct {
		Id         string         `db:"id"`
		MerchantId string         `db:"merchant_id"`
		UserId     string         `db:"user_id"`
		Role       string         `db:"role"`
		Status     string         `db:"status"`
		CreatedBy  sql.NullString `db:"created_by"`
		CreatedAt  time.Time      `db:"created_at"`
		RevokedAt  sql.NullTime   `db:"revoked_at"`
	}
)

func newMerchantAdminBindingsModel(conn sqlx.SqlConn) *defaultMerchantAdminBindingsModel {
	return &defaultMerchantAdminBindingsModel{
		conn:  conn,
		table: `"public"."merchant_admin_bindings"`,
	}
}

func (m *defaultMerchantAdminBindingsModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultMerchantAdminBindingsModel) FindOne(ctx context.Context, id string) (*MerchantAdminBindings, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", merchantAdminBindingsRows, m.table)
	var resp MerchantAdminBindings
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMerchantAdminBindingsModel) FindOneByMerchantIdUserId(ctx context.Context, merchantId string, userId string) (*MerchantAdminBindings, error) {
	var resp MerchantAdminBindings
	query := fmt.Sprintf("select %s from %s where merchant_id = $1 and user_id = $2 limit 1", merchantAdminBindingsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, merchantId, userId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMerchantAdminBindingsModel) Insert(ctx context.Context, data *MerchantAdminBindings) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7)", m.table, merchantAdminBindingsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.MerchantId, data.UserId, data.Role, data.Status, data.CreatedBy, data.RevokedAt)
	return ret, err
}

func (m *defaultMerchantAdminBindingsModel) Update(ctx context.Context, newData *MerchantAdminBindings) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, merchantAdminBindingsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.MerchantId, newData.UserId, newData.Role, newData.Status, newData.CreatedBy, newData.RevokedAt)
	return err
}

func (m *defaultMerchantAdminBindingsModel) tableName() string {
	return m.table
}
