// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.5

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	messagesFieldNames          = builder.RawFieldNames(&Messages{}, true)
	messagesRows                = postgresTextIDRows(messagesFieldNames)
	messagesRowsExpectAutoSet   = strings.Join(stringx.Remove(messagesFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	messagesRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(messagesFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	messagesModel interface {
		Insert(ctx context.Context, data *Messages) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*Messages, error)
		Update(ctx context.Context, data *Messages) error
		Delete(ctx context.Context, id string) error
	}

	defaultMessagesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Messages struct {
		Id                string         `db:"id"`
		RecipientUserId   sql.NullString `db:"recipient_user_id"`
		RecipientRoleCode sql.NullString `db:"recipient_role_code"`
		MessageType       string         `db:"message_type"`
		TriggerType       string         `db:"trigger_type"`
		TriggerId         sql.NullString `db:"trigger_id"`
		Title             string         `db:"title"`
		Content           string         `db:"content"`
		TargetUrl         sql.NullString `db:"target_url"`
		Channel           string         `db:"channel"`
		Status            string         `db:"status"`
		ReadAt            sql.NullTime   `db:"read_at"`
		CreatedAt         time.Time      `db:"created_at"`
		SentAt            sql.NullTime   `db:"sent_at"`
	}
)

func newMessagesModel(conn sqlx.SqlConn) *defaultMessagesModel {
	return &defaultMessagesModel{
		conn:  conn,
		table: `"public"."messages"`,
	}
}

func (m *defaultMessagesModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultMessagesModel) FindOne(ctx context.Context, id string) (*Messages, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", messagesRows, m.table)
	var resp Messages
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMessagesModel) Insert(ctx context.Context, data *Messages) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)", m.table, messagesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.RecipientUserId, data.RecipientRoleCode, data.MessageType, data.TriggerType, data.TriggerId, data.Title, data.Content, data.TargetUrl, data.Channel, data.Status, data.ReadAt, data.SentAt)
	return ret, err
}

func (m *defaultMessagesModel) Update(ctx context.Context, data *Messages) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, messagesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.RecipientUserId, data.RecipientRoleCode, data.MessageType, data.TriggerType, data.TriggerId, data.Title, data.Content, data.TargetUrl, data.Channel, data.Status, data.ReadAt, data.SentAt)
	return err
}

func (m *defaultMessagesModel) tableName() string {
	return m.table
}
