// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.5

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	purchaseDemandsFieldNames          = builder.RawFieldNames(&PurchaseDemands{}, true)
	purchaseDemandsRows                = postgresTextIDRows(purchaseDemandsFieldNames)
	purchaseDemandsRowsExpectAutoSet   = strings.Join(stringx.Remove(purchaseDemandsFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	purchaseDemandsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(purchaseDemandsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	purchaseDemandsModel interface {
		Insert(ctx context.Context, data *PurchaseDemands) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*PurchaseDemands, error)
		Update(ctx context.Context, data *PurchaseDemands) error
		Delete(ctx context.Context, id string) error
	}

	defaultPurchaseDemandsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	PurchaseDemands struct {
		Id                  string         `db:"id"`
		UserId              string         `db:"user_id"`
		CityStationId       sql.NullString `db:"city_station_id"`
		DemandType          string         `db:"demand_type"`
		Status              string         `db:"status"`
		Title               string         `db:"title"`
		Category            string         `db:"category"`
		PriceRange          string         `db:"price_range"`
		QuantityRequirement string         `db:"quantity_requirement"`
		Attributes          string         `db:"attributes"`
		ContactName         string         `db:"contact_name"`
		ContactPhone        string         `db:"contact_phone"`
		ContactWechat       sql.NullString `db:"contact_wechat"`
		ExpiresAt           sql.NullTime   `db:"expires_at"`
		CreatedAt           time.Time      `db:"created_at"`
		UpdatedAt           time.Time      `db:"updated_at"`
	}
)

func newPurchaseDemandsModel(conn sqlx.SqlConn) *defaultPurchaseDemandsModel {
	return &defaultPurchaseDemandsModel{
		conn:  conn,
		table: `"public"."purchase_demands"`,
	}
}

func (m *defaultPurchaseDemandsModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultPurchaseDemandsModel) FindOne(ctx context.Context, id string) (*PurchaseDemands, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", purchaseDemandsRows, m.table)
	var resp PurchaseDemands
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPurchaseDemandsModel) Insert(ctx context.Context, data *PurchaseDemands) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)", m.table, purchaseDemandsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.UserId, data.CityStationId, data.DemandType, data.Status, data.Title, data.Category, data.PriceRange, data.QuantityRequirement, data.Attributes, data.ContactName, data.ContactPhone, data.ContactWechat, data.ExpiresAt)
	return ret, err
}

func (m *defaultPurchaseDemandsModel) Update(ctx context.Context, data *PurchaseDemands) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, purchaseDemandsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.UserId, data.CityStationId, data.DemandType, data.Status, data.Title, data.Category, data.PriceRange, data.QuantityRequirement, data.Attributes, data.ContactName, data.ContactPhone, data.ContactWechat, data.ExpiresAt)
	return err
}

func (m *defaultPurchaseDemandsModel) tableName() string {
	return m.table
}
