// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.5

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	resourceReviewRecordsFieldNames          = builder.RawFieldNames(&ResourceReviewRecords{}, true)
	resourceReviewRecordsRows                = strings.Join(resourceReviewRecordsFieldNames, ",")
	resourceReviewRecordsRowsExpectAutoSet   = strings.Join(stringx.Remove(resourceReviewRecordsFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	resourceReviewRecordsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(resourceReviewRecordsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	resourceReviewRecordsModel interface {
		Insert(ctx context.Context, data *ResourceReviewRecords) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*ResourceReviewRecords, error)
		Update(ctx context.Context, data *ResourceReviewRecords) error
		Delete(ctx context.Context, id string) error
	}

	defaultResourceReviewRecordsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ResourceReviewRecords struct {
		Id         string         `db:"id"`
		ResourceId string         `db:"resource_id"`
		ReviewerId string         `db:"reviewer_id"`
		Action     string         `db:"action"`
		Reason     sql.NullString `db:"reason"`
		Snapshot   string         `db:"snapshot"`
		CreatedAt  time.Time      `db:"created_at"`
	}
)

func newResourceReviewRecordsModel(conn sqlx.SqlConn) *defaultResourceReviewRecordsModel {
	return &defaultResourceReviewRecordsModel{
		conn:  conn,
		table: `"public"."resource_review_records"`,
	}
}

func (m *defaultResourceReviewRecordsModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultResourceReviewRecordsModel) FindOne(ctx context.Context, id string) (*ResourceReviewRecords, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", resourceReviewRecordsRows, m.table)
	var resp ResourceReviewRecords
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultResourceReviewRecordsModel) Insert(ctx context.Context, data *ResourceReviewRecords) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6)", m.table, resourceReviewRecordsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.ResourceId, data.ReviewerId, data.Action, data.Reason, data.Snapshot)
	return ret, err
}

func (m *defaultResourceReviewRecordsModel) Update(ctx context.Context, data *ResourceReviewRecords) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, resourceReviewRecordsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.ResourceId, data.ReviewerId, data.Action, data.Reason, data.Snapshot)
	return err
}

func (m *defaultResourceReviewRecordsModel) tableName() string {
	return m.table
}
