// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.5

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	resourceTypeConfigsFieldNames          = builder.RawFieldNames(&ResourceTypeConfigs{}, true)
	resourceTypeConfigsRows                = strings.Join(resourceTypeConfigsFieldNames, ",")
	resourceTypeConfigsRowsExpectAutoSet   = strings.Join(stringx.Remove(resourceTypeConfigsFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	resourceTypeConfigsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(resourceTypeConfigsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	resourceTypeConfigsModel interface {
		Insert(ctx context.Context, data *ResourceTypeConfigs) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*ResourceTypeConfigs, error)
		FindOneByCityStationIdTypeCode(ctx context.Context, cityStationId sql.NullString, typeCode string) (*ResourceTypeConfigs, error)
		FindOneByTypeCode(ctx context.Context, typeCode string) (*ResourceTypeConfigs, error)
		Update(ctx context.Context, data *ResourceTypeConfigs) error
		Delete(ctx context.Context, id string) error
	}

	defaultResourceTypeConfigsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ResourceTypeConfigs struct {
		Id               string         `db:"id"`
		CityStationId    sql.NullString `db:"city_station_id"`
		TypeCode         string         `db:"type_code"`
		TypeName         string         `db:"type_name"`
		FieldSchema      string         `db:"field_schema"`
		RequiredFields   string         `db:"required_fields"`
		FilterFields     string         `db:"filter_fields"`
		DisplayTemplate  string         `db:"display_template"`
		ReviewRules      string         `db:"review_rules"`
		SortWeights      string         `db:"sort_weights"`
		MessageRules     string         `db:"message_rules"`
		DefaultValidDays int64          `db:"default_valid_days"`
		Status           string         `db:"status"`
		CreatedAt        time.Time      `db:"created_at"`
		UpdatedAt        time.Time      `db:"updated_at"`
	}
)

func newResourceTypeConfigsModel(conn sqlx.SqlConn) *defaultResourceTypeConfigsModel {
	return &defaultResourceTypeConfigsModel{
		conn:  conn,
		table: `"public"."resource_type_configs"`,
	}
}

func (m *defaultResourceTypeConfigsModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultResourceTypeConfigsModel) FindOne(ctx context.Context, id string) (*ResourceTypeConfigs, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", resourceTypeConfigsRows, m.table)
	var resp ResourceTypeConfigs
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultResourceTypeConfigsModel) FindOneByCityStationIdTypeCode(ctx context.Context, cityStationId sql.NullString, typeCode string) (*ResourceTypeConfigs, error) {
	var resp ResourceTypeConfigs
	query := fmt.Sprintf("select %s from %s where city_station_id = $1 and type_code = $2 limit 1", resourceTypeConfigsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, cityStationId, typeCode)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultResourceTypeConfigsModel) FindOneByTypeCode(ctx context.Context, typeCode string) (*ResourceTypeConfigs, error) {
	var resp ResourceTypeConfigs
	query := fmt.Sprintf("select %s from %s where type_code = $1 limit 1", resourceTypeConfigsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, typeCode)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultResourceTypeConfigsModel) Insert(ctx context.Context, data *ResourceTypeConfigs) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)", m.table, resourceTypeConfigsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.CityStationId, data.TypeCode, data.TypeName, data.FieldSchema, data.RequiredFields, data.FilterFields, data.DisplayTemplate, data.ReviewRules, data.SortWeights, data.MessageRules, data.DefaultValidDays, data.Status)
	return ret, err
}

func (m *defaultResourceTypeConfigsModel) Update(ctx context.Context, newData *ResourceTypeConfigs) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, resourceTypeConfigsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.CityStationId, newData.TypeCode, newData.TypeName, newData.FieldSchema, newData.RequiredFields, newData.FilterFields, newData.DisplayTemplate, newData.ReviewRules, newData.SortWeights, newData.MessageRules, newData.DefaultValidDays, newData.Status)
	return err
}

func (m *defaultResourceTypeConfigsModel) tableName() string {
	return m.table
}
