// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.5

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	resourceContactEventsFieldNames          = builder.RawFieldNames(&ResourceContactEvents{}, true)
	resourceContactEventsRows                = strings.Join(resourceContactEventsFieldNames, ",")
	resourceContactEventsRowsExpectAutoSet   = strings.Join(stringx.Remove(resourceContactEventsFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	resourceContactEventsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(resourceContactEventsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	resourceContactEventsModel interface {
		Insert(ctx context.Context, data *ResourceContactEvents) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*ResourceContactEvents, error)
		Update(ctx context.Context, data *ResourceContactEvents) error
		Delete(ctx context.Context, id string) error
	}

	defaultResourceContactEventsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ResourceContactEvents struct {
		Id         string         `db:"id"`
		ResourceId string         `db:"resource_id"`
		UserId     sql.NullString `db:"user_id"`
		MerchantId string         `db:"merchant_id"`
		Action     string         `db:"action"`
		CreatedAt  time.Time      `db:"created_at"`
	}
)

func newResourceContactEventsModel(conn sqlx.SqlConn) *defaultResourceContactEventsModel {
	return &defaultResourceContactEventsModel{
		conn:  conn,
		table: `"public"."resource_contact_events"`,
	}
}

func (m *defaultResourceContactEventsModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultResourceContactEventsModel) FindOne(ctx context.Context, id string) (*ResourceContactEvents, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", resourceContactEventsRows, m.table)
	var resp ResourceContactEvents
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultResourceContactEventsModel) Insert(ctx context.Context, data *ResourceContactEvents) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5)", m.table, resourceContactEventsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.ResourceId, data.UserId, data.MerchantId, data.Action)
	return ret, err
}

func (m *defaultResourceContactEventsModel) Update(ctx context.Context, data *ResourceContactEvents) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, resourceContactEventsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.ResourceId, data.UserId, data.MerchantId, data.Action)
	return err
}

func (m *defaultResourceContactEventsModel) tableName() string {
	return m.table
}
