// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.5

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	resourcesFieldNames          = builder.RawFieldNames(&Resources{}, true)
	resourcesRows                = strings.Join(resourcesFieldNames, ",")
	resourcesRowsExpectAutoSet   = strings.Join(stringx.Remove(resourcesFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	resourcesRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(resourcesFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	resourcesModel interface {
		Insert(ctx context.Context, data *Resources) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*Resources, error)
		Update(ctx context.Context, data *Resources) error
		Delete(ctx context.Context, id string) error
	}

	defaultResourcesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Resources struct {
		Id                   string         `db:"id"`
		MerchantId           string         `db:"merchant_id"`
		CityStationId        string         `db:"city_station_id"`
		ResourceTypeConfigId string         `db:"resource_type_config_id"`
		TypeCode             string         `db:"type_code"`
		Status               string         `db:"status"`
		Title                string         `db:"title"`
		Category             string         `db:"category"`
		District             sql.NullString `db:"district"`
		PriceText            sql.NullString `db:"price_text"`
		QuantityText         sql.NullString `db:"quantity_text"`
		CoverUrl             sql.NullString `db:"cover_url"`
		Description          string         `db:"description"`
		Attributes           string         `db:"attributes"`
		Tags                 string         `db:"tags"`
		Images               string         `db:"images"`
		ContactName          string         `db:"contact_name"`
		ContactPhone         string         `db:"contact_phone"`
		ContactWechat        sql.NullString `db:"contact_wechat"`
		IsVerified           bool           `db:"is_verified"`
		PublishedAt          sql.NullTime   `db:"published_at"`
		RefreshedAt          sql.NullTime   `db:"refreshed_at"`
		ExpiresAt            sql.NullTime   `db:"expires_at"`
		DealtAt              sql.NullTime   `db:"dealt_at"`
		TakenDownAt          sql.NullTime   `db:"taken_down_at"`
		ArchivedAt           sql.NullTime   `db:"archived_at"`
		RejectReason         sql.NullString `db:"reject_reason"`
		TakeDownReason       sql.NullString `db:"take_down_reason"`
		CreatedBy            sql.NullString `db:"created_by"`
		CreatedAt            time.Time      `db:"created_at"`
		UpdatedAt            time.Time      `db:"updated_at"`
		DeletedAt            sql.NullTime   `db:"deleted_at"`
	}
)

func newResourcesModel(conn sqlx.SqlConn) *defaultResourcesModel {
	return &defaultResourcesModel{
		conn:  conn,
		table: `"public"."resources"`,
	}
}

func (m *defaultResourcesModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultResourcesModel) FindOne(ctx context.Context, id string) (*Resources, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", resourcesRows, m.table)
	var resp Resources
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultResourcesModel) Insert(ctx context.Context, data *Resources) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28, $29, $30)", m.table, resourcesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.MerchantId, data.CityStationId, data.ResourceTypeConfigId, data.TypeCode, data.Status, data.Title, data.Category, data.District, data.PriceText, data.QuantityText, data.CoverUrl, data.Description, data.Attributes, data.Tags, data.Images, data.ContactName, data.ContactPhone, data.ContactWechat, data.IsVerified, data.PublishedAt, data.RefreshedAt, data.ExpiresAt, data.DealtAt, data.TakenDownAt, data.ArchivedAt, data.RejectReason, data.TakeDownReason, data.CreatedBy, data.DeletedAt)
	return ret, err
}

func (m *defaultResourcesModel) Update(ctx context.Context, data *Resources) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, resourcesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.MerchantId, data.CityStationId, data.ResourceTypeConfigId, data.TypeCode, data.Status, data.Title, data.Category, data.District, data.PriceText, data.QuantityText, data.CoverUrl, data.Description, data.Attributes, data.Tags, data.Images, data.ContactName, data.ContactPhone, data.ContactWechat, data.IsVerified, data.PublishedAt, data.RefreshedAt, data.ExpiresAt, data.DealtAt, data.TakenDownAt, data.ArchivedAt, data.RejectReason, data.TakeDownReason, data.CreatedBy, data.DeletedAt)
	return err
}

func (m *defaultResourcesModel) tableName() string {
	return m.table
}
