// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.5

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	resourceMetricsDailyFieldNames          = builder.RawFieldNames(&ResourceMetricsDaily{}, true)
	resourceMetricsDailyRows                = strings.Join(resourceMetricsDailyFieldNames, ",")
	resourceMetricsDailyRowsExpectAutoSet   = strings.Join(stringx.Remove(resourceMetricsDailyFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	resourceMetricsDailyRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(resourceMetricsDailyFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	resourceMetricsDailyModel interface {
		Insert(ctx context.Context, data *ResourceMetricsDaily) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*ResourceMetricsDaily, error)
		FindOneByResourceIdStatDate(ctx context.Context, resourceId string, statDate time.Time) (*ResourceMetricsDaily, error)
		Update(ctx context.Context, data *ResourceMetricsDaily) error
		Delete(ctx context.Context, id string) error
	}

	defaultResourceMetricsDailyModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ResourceMetricsDaily struct {
		Id                  string    `db:"id"`
		ResourceId          string    `db:"resource_id"`
		MerchantId          string    `db:"merchant_id"`
		StatDate            time.Time `db:"stat_date"`
		ExposureCount       int64     `db:"exposure_count"`
		SearchExposureCount int64     `db:"search_exposure_count"`
		ListExposureCount   int64     `db:"list_exposure_count"`
		DetailViewCount     int64     `db:"detail_view_count"`
		ContactClickCount   int64     `db:"contact_click_count"`
		PhoneClickCount     int64     `db:"phone_click_count"`
		WechatCopyCount     int64     `db:"wechat_copy_count"`
		FavoriteCount       int64     `db:"favorite_count"`
		ShareCount          int64     `db:"share_count"`
		DealFeedbackCount   int64     `db:"deal_feedback_count"`
		CreatedAt           time.Time `db:"created_at"`
		UpdatedAt           time.Time `db:"updated_at"`
	}
)

func newResourceMetricsDailyModel(conn sqlx.SqlConn) *defaultResourceMetricsDailyModel {
	return &defaultResourceMetricsDailyModel{
		conn:  conn,
		table: `"public"."resource_metrics_daily"`,
	}
}

func (m *defaultResourceMetricsDailyModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultResourceMetricsDailyModel) FindOne(ctx context.Context, id string) (*ResourceMetricsDaily, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", resourceMetricsDailyRows, m.table)
	var resp ResourceMetricsDaily
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultResourceMetricsDailyModel) FindOneByResourceIdStatDate(ctx context.Context, resourceId string, statDate time.Time) (*ResourceMetricsDaily, error) {
	var resp ResourceMetricsDaily
	query := fmt.Sprintf("select %s from %s where resource_id = $1 and stat_date = $2 limit 1", resourceMetricsDailyRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, resourceId, statDate)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultResourceMetricsDailyModel) Insert(ctx context.Context, data *ResourceMetricsDaily) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)", m.table, resourceMetricsDailyRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.ResourceId, data.MerchantId, data.StatDate, data.ExposureCount, data.SearchExposureCount, data.ListExposureCount, data.DetailViewCount, data.ContactClickCount, data.PhoneClickCount, data.WechatCopyCount, data.FavoriteCount, data.ShareCount, data.DealFeedbackCount)
	return ret, err
}

func (m *defaultResourceMetricsDailyModel) Update(ctx context.Context, newData *ResourceMetricsDaily) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, resourceMetricsDailyRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.ResourceId, newData.MerchantId, newData.StatDate, newData.ExposureCount, newData.SearchExposureCount, newData.ListExposureCount, newData.DetailViewCount, newData.ContactClickCount, newData.PhoneClickCount, newData.WechatCopyCount, newData.FavoriteCount, newData.ShareCount, newData.DealFeedbackCount)
	return err
}

func (m *defaultResourceMetricsDailyModel) tableName() string {
	return m.table
}
