// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.5

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	rolesFieldNames          = builder.RawFieldNames(&Roles{}, true)
	rolesRows                = postgresTextIDRows(rolesFieldNames)
	rolesRowsExpectAutoSet   = strings.Join(stringx.Remove(rolesFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	rolesRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(rolesFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	rolesModel interface {
		Insert(ctx context.Context, data *Roles) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*Roles, error)
		FindOneByCode(ctx context.Context, code string) (*Roles, error)
		Update(ctx context.Context, data *Roles) error
		Delete(ctx context.Context, id string) error
	}

	defaultRolesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Roles struct {
		Id          string         `db:"id"`
		Code        string         `db:"code"`
		Name        string         `db:"name"`
		Description sql.NullString `db:"description"`
		Permissions string         `db:"permissions"`
		CreatedAt   time.Time      `db:"created_at"`
		UpdatedAt   time.Time      `db:"updated_at"`
	}
)

func newRolesModel(conn sqlx.SqlConn) *defaultRolesModel {
	return &defaultRolesModel{
		conn:  conn,
		table: `"public"."roles"`,
	}
}

func (m *defaultRolesModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultRolesModel) FindOne(ctx context.Context, id string) (*Roles, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", rolesRows, m.table)
	var resp Roles
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRolesModel) FindOneByCode(ctx context.Context, code string) (*Roles, error) {
	var resp Roles
	query := fmt.Sprintf("select %s from %s where code = $1 limit 1", rolesRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, code)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRolesModel) Insert(ctx context.Context, data *Roles) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5)", m.table, rolesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.Code, data.Name, data.Description, data.Permissions)
	return ret, err
}

func (m *defaultRolesModel) Update(ctx context.Context, newData *Roles) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, rolesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.Code, newData.Name, newData.Description, newData.Permissions)
	return err
}

func (m *defaultRolesModel) tableName() string {
	return m.table
}
