// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.5

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	searchLogsFieldNames          = builder.RawFieldNames(&SearchLogs{}, true)
	searchLogsRows                = strings.Join(searchLogsFieldNames, ",")
	searchLogsRowsExpectAutoSet   = strings.Join(stringx.Remove(searchLogsFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	searchLogsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(searchLogsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	searchLogsModel interface {
		Insert(ctx context.Context, data *SearchLogs) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*SearchLogs, error)
		Update(ctx context.Context, data *SearchLogs) error
		Delete(ctx context.Context, id string) error
	}

	defaultSearchLogsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SearchLogs struct {
		Id                string         `db:"id"`
		UserId            sql.NullString `db:"user_id"`
		CityStationId     sql.NullString `db:"city_station_id"`
		Keyword           string         `db:"keyword"`
		Filters           string         `db:"filters"`
		ResultCount       int64          `db:"result_count"`
		ClickedResourceId sql.NullString `db:"clicked_resource_id"`
		GeneratedDemandId sql.NullString `db:"generated_demand_id"`
		CreatedAt         time.Time      `db:"created_at"`
	}
)

func newSearchLogsModel(conn sqlx.SqlConn) *defaultSearchLogsModel {
	return &defaultSearchLogsModel{
		conn:  conn,
		table: `"public"."search_logs"`,
	}
}

func (m *defaultSearchLogsModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSearchLogsModel) FindOne(ctx context.Context, id string) (*SearchLogs, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", searchLogsRows, m.table)
	var resp SearchLogs
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSearchLogsModel) Insert(ctx context.Context, data *SearchLogs) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8)", m.table, searchLogsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.UserId, data.CityStationId, data.Keyword, data.Filters, data.ResultCount, data.ClickedResourceId, data.GeneratedDemandId)
	return ret, err
}

func (m *defaultSearchLogsModel) Update(ctx context.Context, data *SearchLogs) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, searchLogsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.UserId, data.CityStationId, data.Keyword, data.Filters, data.ResultCount, data.ClickedResourceId, data.GeneratedDemandId)
	return err
}

func (m *defaultSearchLogsModel) tableName() string {
	return m.table
}
