// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.5

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	topVouchersFieldNames          = builder.RawFieldNames(&TopVouchers{}, true)
	topVouchersRows                = postgresTextIDRows(topVouchersFieldNames)
	topVouchersRowsExpectAutoSet   = strings.Join(stringx.Remove(topVouchersFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	topVouchersRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(topVouchersFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	topVouchersModel interface {
		Insert(ctx context.Context, data *TopVouchers) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*TopVouchers, error)
		Update(ctx context.Context, data *TopVouchers) error
		Delete(ctx context.Context, id string) error
	}

	defaultTopVouchersModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TopVouchers struct {
		Id               string         `db:"id"`
		MerchantId       string         `db:"merchant_id"`
		EntitlementId    sql.NullString `db:"entitlement_id"`
		SourceType       string         `db:"source_type"`
		AllowedTypeCodes string         `db:"allowed_type_codes"`
		TopDurationHours int64          `db:"top_duration_hours"`
		UsedResourceId   sql.NullString `db:"used_resource_id"`
		UsedAt           sql.NullTime   `db:"used_at"`
		ExpiresAt        sql.NullTime   `db:"expires_at"`
		Status           string         `db:"status"`
		CreatedAt        time.Time      `db:"created_at"`
	}
)

func newTopVouchersModel(conn sqlx.SqlConn) *defaultTopVouchersModel {
	return &defaultTopVouchersModel{
		conn:  conn,
		table: `"public"."top_vouchers"`,
	}
}

func (m *defaultTopVouchersModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultTopVouchersModel) FindOne(ctx context.Context, id string) (*TopVouchers, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", topVouchersRows, m.table)
	var resp TopVouchers
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTopVouchersModel) Insert(ctx context.Context, data *TopVouchers) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)", m.table, topVouchersRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.MerchantId, data.EntitlementId, data.SourceType, data.AllowedTypeCodes, data.TopDurationHours, data.UsedResourceId, data.UsedAt, data.ExpiresAt, data.Status)
	return ret, err
}

func (m *defaultTopVouchersModel) Update(ctx context.Context, data *TopVouchers) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, topVouchersRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.MerchantId, data.EntitlementId, data.SourceType, data.AllowedTypeCodes, data.TopDurationHours, data.UsedResourceId, data.UsedAt, data.ExpiresAt, data.Status)
	return err
}

func (m *defaultTopVouchersModel) tableName() string {
	return m.table
}
