// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.5

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userRoleAssignmentsFieldNames          = builder.RawFieldNames(&UserRoleAssignments{}, true)
	userRoleAssignmentsRows                = postgresTextIDRows(userRoleAssignmentsFieldNames)
	userRoleAssignmentsRowsExpectAutoSet   = strings.Join(stringx.Remove(userRoleAssignmentsFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	userRoleAssignmentsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(userRoleAssignmentsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	userRoleAssignmentsModel interface {
		Insert(ctx context.Context, data *UserRoleAssignments) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*UserRoleAssignments, error)
		FindOneByUserIdRoleIdCityStationIdMerchantId(ctx context.Context, userId string, roleId string, cityStationId sql.NullString, merchantId sql.NullString) (*UserRoleAssignments, error)
		Update(ctx context.Context, data *UserRoleAssignments) error
		Delete(ctx context.Context, id string) error
	}

	defaultUserRoleAssignmentsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserRoleAssignments struct {
		Id            string         `db:"id"`
		UserId        string         `db:"user_id"`
		RoleId        string         `db:"role_id"`
		CityStationId sql.NullString `db:"city_station_id"`
		MerchantId    sql.NullString `db:"merchant_id"`
		CreatedAt     time.Time      `db:"created_at"`
	}
)

func newUserRoleAssignmentsModel(conn sqlx.SqlConn) *defaultUserRoleAssignmentsModel {
	return &defaultUserRoleAssignmentsModel{
		conn:  conn,
		table: `"public"."user_role_assignments"`,
	}
}

func (m *defaultUserRoleAssignmentsModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserRoleAssignmentsModel) FindOne(ctx context.Context, id string) (*UserRoleAssignments, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", userRoleAssignmentsRows, m.table)
	var resp UserRoleAssignments
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserRoleAssignmentsModel) FindOneByUserIdRoleIdCityStationIdMerchantId(ctx context.Context, userId string, roleId string, cityStationId sql.NullString, merchantId sql.NullString) (*UserRoleAssignments, error) {
	var resp UserRoleAssignments
	query := fmt.Sprintf("select %s from %s where user_id = $1 and role_id = $2 and city_station_id = $3 and merchant_id = $4 limit 1", userRoleAssignmentsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId, roleId, cityStationId, merchantId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserRoleAssignmentsModel) Insert(ctx context.Context, data *UserRoleAssignments) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5)", m.table, userRoleAssignmentsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.UserId, data.RoleId, data.CityStationId, data.MerchantId)
	return ret, err
}

func (m *defaultUserRoleAssignmentsModel) Update(ctx context.Context, newData *UserRoleAssignments) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, userRoleAssignmentsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.UserId, newData.RoleId, newData.CityStationId, newData.MerchantId)
	return err
}

func (m *defaultUserRoleAssignmentsModel) tableName() string {
	return m.table
}
