// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.5

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	verificationsFieldNames          = builder.RawFieldNames(&Verifications{}, true)
	verificationsRows                = postgresTextIDRows(verificationsFieldNames)
	verificationsRowsExpectAutoSet   = strings.Join(stringx.Remove(verificationsFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	verificationsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(verificationsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	verificationsModel interface {
		Insert(ctx context.Context, data *Verifications) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*Verifications, error)
		Update(ctx context.Context, data *Verifications) error
		Delete(ctx context.Context, id string) error
	}

	defaultVerificationsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Verifications struct {
		Id               string         `db:"id"`
		MerchantId       string         `db:"merchant_id"`
		ResourceId       sql.NullString `db:"resource_id"`
		VerificationType string         `db:"verification_type"`
		Status           string         `db:"status"`
		ApplicantUserId  string         `db:"applicant_user_id"`
		BusinessName     sql.NullString `db:"business_name"`
		LicenseUrl       sql.NullString `db:"license_url"`
		StorefrontUrl    sql.NullString `db:"storefront_url"`
		Materials        string         `db:"materials"`
		ReviewNote       sql.NullString `db:"review_note"`
		ReviewedBy       sql.NullString `db:"reviewed_by"`
		SubmittedAt      time.Time      `db:"submitted_at"`
		ReviewedAt       sql.NullTime   `db:"reviewed_at"`
		CreatedAt        time.Time      `db:"created_at"`
		UpdatedAt        time.Time      `db:"updated_at"`
	}
)

func newVerificationsModel(conn sqlx.SqlConn) *defaultVerificationsModel {
	return &defaultVerificationsModel{
		conn:  conn,
		table: `"public"."verifications"`,
	}
}

func (m *defaultVerificationsModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultVerificationsModel) FindOne(ctx context.Context, id string) (*Verifications, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", verificationsRows, m.table)
	var resp Verifications
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultVerificationsModel) Insert(ctx context.Context, data *Verifications) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)", m.table, verificationsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.MerchantId, data.ResourceId, data.VerificationType, data.Status, data.ApplicantUserId, data.BusinessName, data.LicenseUrl, data.StorefrontUrl, data.Materials, data.ReviewNote, data.ReviewedBy, data.SubmittedAt, data.ReviewedAt)
	return ret, err
}

func (m *defaultVerificationsModel) Update(ctx context.Context, data *Verifications) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, verificationsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.MerchantId, data.ResourceId, data.VerificationType, data.Status, data.ApplicantUserId, data.BusinessName, data.LicenseUrl, data.StorefrontUrl, data.Materials, data.ReviewNote, data.ReviewedBy, data.SubmittedAt, data.ReviewedAt)
	return err
}

func (m *defaultVerificationsModel) tableName() string {
	return m.table
}
